// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.op
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dram_data_caching,hls_ip_2017_4_op,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.997000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6176,HLS_SYN_LUT=690}" *)

module dram_data_caching (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
ap_continue,
        ap_idle,
        ap_ready,
        dramA_read_resp_V_last_dout,
        dramA_read_resp_V_last_empty_n,
        dramA_read_resp_V_last_read,
        dramA_read_resp_V_data_V_dout,
        dramA_read_resp_V_data_V_empty_n,
        dramA_read_resp_V_data_V_read,
        dramB_read_resp_V_last_dout,
        dramB_read_resp_V_last_empty_n,
        dramB_read_resp_V_last_read,
        dramB_read_resp_V_data_V_dout,
        dramB_read_resp_V_data_V_empty_n,
        dramB_read_resp_V_data_V_read,
        cached_dramA_read_resp_V_last_din,
        cached_dramA_read_resp_V_last_full_n,
        cached_dramA_read_resp_V_last_write,
        cached_dramA_read_resp_V_data_V_din,
        cached_dramA_read_resp_V_data_V_full_n,
        cached_dramA_read_resp_V_data_V_write,
        cached_dramB_read_resp_V_last_din,
        cached_dramB_read_resp_V_last_full_n,
        cached_dramB_read_resp_V_last_write,
        cached_dramB_read_resp_V_data_V_din,
        cached_dramB_read_resp_V_data_V_full_n,
        cached_dramB_read_resp_V_data_V_write,
        dramA_write_req_data_V_last_din,
        dramA_write_req_data_V_last_full_n,
        dramA_write_req_data_V_last_write,
        dramA_write_req_data_V_data_V_din,
        dramA_write_req_data_V_data_V_full_n,
        dramA_write_req_data_V_data_V_write,
        dramB_write_req_data_V_last_din,
        dramB_write_req_data_V_last_full_n,
        dramB_write_req_data_V_last_write,
        dramB_write_req_data_V_data_V_din,
        dramB_write_req_data_V_data_V_full_n,
        dramB_write_req_data_V_data_V_write,
        cached_dramA_write_req_data_V_last_dout,
        cached_dramA_write_req_data_V_last_empty_n,
        cached_dramA_write_req_data_V_last_read,
        cached_dramA_write_req_data_V_data_V_dout,
        cached_dramA_write_req_data_V_data_V_empty_n,
        cached_dramA_write_req_data_V_data_V_read,
        cached_dramB_write_req_data_V_last_dout,
        cached_dramB_write_req_data_V_last_empty_n,
        cached_dramB_write_req_data_V_last_read,
        cached_dramB_write_req_data_V_data_V_dout,
        cached_dramB_write_req_data_V_data_V_empty_n,
        cached_dramB_write_req_data_V_data_V_read
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output ap_ready; output ap_continue;
input   dramA_read_resp_V_last_dout;
input   dramA_read_resp_V_last_empty_n;
output   dramA_read_resp_V_last_read;
input  [511:0] dramA_read_resp_V_data_V_dout;
input   dramA_read_resp_V_data_V_empty_n;
output   dramA_read_resp_V_data_V_read;
input   dramB_read_resp_V_last_dout;
input   dramB_read_resp_V_last_empty_n;
output   dramB_read_resp_V_last_read;
input  [511:0] dramB_read_resp_V_data_V_dout;
input   dramB_read_resp_V_data_V_empty_n;
output   dramB_read_resp_V_data_V_read;
output   cached_dramA_read_resp_V_last_din;
input   cached_dramA_read_resp_V_last_full_n;
output   cached_dramA_read_resp_V_last_write;
output  [511:0] cached_dramA_read_resp_V_data_V_din;
input   cached_dramA_read_resp_V_data_V_full_n;
output   cached_dramA_read_resp_V_data_V_write;
output   cached_dramB_read_resp_V_last_din;
input   cached_dramB_read_resp_V_last_full_n;
output   cached_dramB_read_resp_V_last_write;
output  [511:0] cached_dramB_read_resp_V_data_V_din;
input   cached_dramB_read_resp_V_data_V_full_n;
output   cached_dramB_read_resp_V_data_V_write;
output   dramA_write_req_data_V_last_din;
input   dramA_write_req_data_V_last_full_n;
output   dramA_write_req_data_V_last_write;
output  [511:0] dramA_write_req_data_V_data_V_din;
input   dramA_write_req_data_V_data_V_full_n;
output   dramA_write_req_data_V_data_V_write;
output   dramB_write_req_data_V_last_din;
input   dramB_write_req_data_V_last_full_n;
output   dramB_write_req_data_V_last_write;
output  [511:0] dramB_write_req_data_V_data_V_din;
input   dramB_write_req_data_V_data_V_full_n;
output   dramB_write_req_data_V_data_V_write;
input   cached_dramA_write_req_data_V_last_dout;
input   cached_dramA_write_req_data_V_last_empty_n;
output   cached_dramA_write_req_data_V_last_read;
input  [511:0] cached_dramA_write_req_data_V_data_V_dout;
input   cached_dramA_write_req_data_V_data_V_empty_n;
output   cached_dramA_write_req_data_V_data_V_read;
input   cached_dramB_write_req_data_V_last_dout;
input   cached_dramB_write_req_data_V_last_empty_n;
output   cached_dramB_write_req_data_V_last_read;
input  [511:0] cached_dramB_write_req_data_V_data_V_dout;
input   cached_dramB_write_req_data_V_data_V_empty_n;
output   cached_dramB_write_req_data_V_data_V_read;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] has_dramA_read_resp_reg_338;
reg   [0:0] has_dramB_read_resp_reg_350;
reg   [0:0] has_cached_dramA_write_req_data_reg_362;
reg   [0:0] has_cached_dramB_write_req_data_reg_374;
reg   [511:0] data_cached_dramB_write_req_data_1_s_reg_386;
reg   [0:0] data_cached_dramB_write_req_data_0_s_reg_397;
reg   [511:0] data_cached_dramA_write_req_data_1_s_reg_408;
reg   [0:0] data_cached_dramA_write_req_data_0_s_reg_419;
reg   [511:0] data_dramB_read_resp_1_s_reg_430;
reg   [0:0] data_dramB_read_resp_0_s_reg_441;
reg   [511:0] data_dramA_read_resp_1_s_reg_452;
reg   [0:0] data_dramA_read_resp_0_s_reg_463;
wire   [0:0] empty_n_8_fu_742_p1;
reg   [0:0] empty_n_8_reg_842;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] ap_phi_mux_has_dramA_read_resp_phi_fu_342_p4;
wire   [0:0] empty_n_9_fu_754_p1;
reg   [0:0] empty_n_9_reg_860;
reg   [0:0] ap_phi_mux_has_dramB_read_resp_phi_fu_354_p4;
wire   [0:0] empty_n_10_fu_766_p1;
reg   [0:0] empty_n_10_reg_878;
reg   [0:0] ap_phi_mux_has_cached_dramA_write_req_data_phi_fu_366_p4;
wire   [0:0] empty_n_11_fu_778_p1;
reg   [0:0] empty_n_11_reg_896;
reg   [0:0] ap_phi_mux_has_cached_dramB_write_req_data_phi_fu_378_p4;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_has_dramA_read_resp_3_phi_fu_534_p4;
wire    ap_block_pp0_stage0;
reg   [0:0] ap_phi_mux_has_dramB_read_resp_3_phi_fu_601_p4;
reg   [0:0] ap_phi_mux_has_cached_dramA_write_req_data_3_phi_fu_668_p4;
reg   [0:0] ap_phi_mux_has_cached_dramB_write_req_data_3_phi_fu_735_p4;
reg   [511:0] ap_phi_mux_data_cached_dramB_write_req_data_1_2_phi_fu_711_p4;
reg   [0:0] ap_phi_mux_data_cached_dramB_write_req_data_0_2_phi_fu_723_p4;
reg   [511:0] ap_phi_mux_data_cached_dramA_write_req_data_1_2_phi_fu_644_p4;
reg   [0:0] ap_phi_mux_data_cached_dramA_write_req_data_0_2_phi_fu_656_p4;
reg   [511:0] ap_phi_mux_data_dramB_read_resp_1_2_phi_fu_577_p4;
reg   [0:0] ap_phi_mux_data_dramB_read_resp_0_2_phi_fu_589_p4;
reg   [511:0] ap_phi_mux_data_dramA_read_resp_1_2_phi_fu_510_p4;
reg   [0:0] ap_phi_mux_data_dramA_read_resp_0_2_phi_fu_522_p4;
reg   [511:0] ap_phi_mux_tmp_data_V_phi_fu_477_p4;
reg   [511:0] ap_phi_reg_pp0_iter1_tmp_data_V_reg_474;
wire   [511:0] ap_phi_reg_pp0_iter0_tmp_data_V_reg_474;
reg   [0:0] ap_phi_mux_tmp_last_phi_fu_488_p4;
reg   [0:0] ap_phi_reg_pp0_iter1_tmp_last_reg_485;
wire   [0:0] ap_phi_reg_pp0_iter0_tmp_last_reg_485;
reg   [0:0] ap_phi_mux_has_dramA_read_resp_1_phi_fu_499_p4;
reg   [0:0] ap_phi_reg_pp0_iter1_has_dramA_read_resp_1_reg_496;
wire   [0:0] ap_phi_reg_pp0_iter0_has_dramA_read_resp_1_reg_496;
reg   [511:0] ap_phi_reg_pp0_iter1_data_dramA_read_resp_1_2_reg_506;
wire   [511:0] ap_phi_reg_pp0_iter0_data_dramA_read_resp_1_2_reg_506;
reg   [0:0] ap_phi_reg_pp0_iter1_data_dramA_read_resp_0_2_reg_518;
wire   [0:0] ap_phi_reg_pp0_iter0_data_dramA_read_resp_0_2_reg_518;
wire   [0:0] p_has_dramA_read_resp_1_fu_796_p2;
reg   [0:0] ap_phi_reg_pp0_iter1_has_dramA_read_resp_3_reg_530;
wire   [0:0] ap_phi_reg_pp0_iter0_has_dramA_read_resp_3_reg_530;
reg   [511:0] ap_phi_mux_tmp_data_V_2_phi_fu_544_p4;
reg   [511:0] ap_phi_reg_pp0_iter1_tmp_data_V_2_reg_541;
wire   [511:0] ap_phi_reg_pp0_iter0_tmp_data_V_2_reg_541;
reg   [0:0] ap_phi_mux_tmp_last_2_phi_fu_555_p4;
reg   [0:0] ap_phi_reg_pp0_iter1_tmp_last_2_reg_552;
wire   [0:0] ap_phi_reg_pp0_iter0_tmp_last_2_reg_552;
reg   [0:0] ap_phi_mux_has_dramB_read_resp_1_phi_fu_566_p4;
reg   [0:0] ap_phi_reg_pp0_iter1_has_dramB_read_resp_1_reg_563;
wire   [0:0] ap_phi_reg_pp0_iter0_has_dramB_read_resp_1_reg_563;
reg   [511:0] ap_phi_reg_pp0_iter1_data_dramB_read_resp_1_2_reg_573;
wire   [511:0] ap_phi_reg_pp0_iter0_data_dramB_read_resp_1_2_reg_573;
reg   [0:0] ap_phi_reg_pp0_iter1_data_dramB_read_resp_0_2_reg_585;
wire   [0:0] ap_phi_reg_pp0_iter0_data_dramB_read_resp_0_2_reg_585;
wire   [0:0] p_has_dramB_read_resp_1_fu_809_p2;
reg   [0:0] ap_phi_reg_pp0_iter1_has_dramB_read_resp_3_reg_597;
wire   [0:0] ap_phi_reg_pp0_iter0_has_dramB_read_resp_3_reg_597;
reg   [511:0] ap_phi_mux_tmp_data_V_4_phi_fu_611_p4;
reg   [511:0] ap_phi_reg_pp0_iter1_tmp_data_V_4_reg_608;
wire   [511:0] ap_phi_reg_pp0_iter0_tmp_data_V_4_reg_608;
reg   [0:0] ap_phi_mux_tmp_last_4_phi_fu_622_p4;
reg   [0:0] ap_phi_reg_pp0_iter1_tmp_last_4_reg_619;
wire   [0:0] ap_phi_reg_pp0_iter0_tmp_last_4_reg_619;
reg   [0:0] ap_phi_mux_has_cached_dramA_write_req_data_1_phi_fu_633_p4;
reg   [0:0] ap_phi_reg_pp0_iter1_has_cached_dramA_write_req_data_1_reg_630;
wire   [0:0] ap_phi_reg_pp0_iter0_has_cached_dramA_write_req_data_1_reg_630;
reg   [511:0] ap_phi_reg_pp0_iter1_data_cached_dramA_write_req_data_1_2_reg_640;
wire   [511:0] ap_phi_reg_pp0_iter0_data_cached_dramA_write_req_data_1_2_reg_640;
reg   [0:0] ap_phi_reg_pp0_iter1_data_cached_dramA_write_req_data_0_2_reg_652;
wire   [0:0] ap_phi_reg_pp0_iter0_data_cached_dramA_write_req_data_0_2_reg_652;
wire   [0:0] p_has_cached_dramA_write_req_data_1_fu_822_p2;
reg   [0:0] ap_phi_reg_pp0_iter1_has_cached_dramA_write_req_data_3_reg_664;
wire   [0:0] ap_phi_reg_pp0_iter0_has_cached_dramA_write_req_data_3_reg_664;
reg   [511:0] ap_phi_mux_tmp_data_V_6_phi_fu_678_p4;
reg   [511:0] ap_phi_reg_pp0_iter1_tmp_data_V_6_reg_675;
wire   [511:0] ap_phi_reg_pp0_iter0_tmp_data_V_6_reg_675;
reg   [0:0] ap_phi_mux_tmp_last_6_phi_fu_689_p4;
reg   [0:0] ap_phi_reg_pp0_iter1_tmp_last_6_reg_686;
wire   [0:0] ap_phi_reg_pp0_iter0_tmp_last_6_reg_686;
reg   [0:0] ap_phi_mux_has_cached_dramB_write_req_data_1_phi_fu_700_p4;
reg   [0:0] ap_phi_reg_pp0_iter1_has_cached_dramB_write_req_data_1_reg_697;
wire   [0:0] ap_phi_reg_pp0_iter0_has_cached_dramB_write_req_data_1_reg_697;
reg   [511:0] ap_phi_reg_pp0_iter1_data_cached_dramB_write_req_data_1_2_reg_707;
wire   [511:0] ap_phi_reg_pp0_iter0_data_cached_dramB_write_req_data_1_2_reg_707;
reg   [0:0] ap_phi_reg_pp0_iter1_data_cached_dramB_write_req_data_0_2_reg_719;
wire   [0:0] ap_phi_reg_pp0_iter0_data_cached_dramB_write_req_data_0_2_reg_719;
wire   [0:0] p_has_cached_dramB_write_req_data_1_fu_835_p2;
reg   [0:0] ap_phi_reg_pp0_iter1_has_cached_dramB_write_req_data_3_reg_731;
wire   [0:0] ap_phi_reg_pp0_iter0_has_cached_dramB_write_req_data_3_reg_731;
reg    dramA_read_resp_V_last0_update;
wire   [0:0] empty_n_nbread_fu_266_p3_0;
reg    dramB_read_resp_V_last0_update;
wire   [0:0] empty_n_1_nbread_fu_274_p3_0;
reg    cached_dramA_write_req_data_V_last0_update;
wire   [0:0] empty_n_2_nbread_fu_282_p3_0;
reg    cached_dramB_write_req_data_V_last0_update;
wire   [0:0] empty_n_3_nbread_fu_290_p3_0;
reg    cached_dramA_read_resp_V_last1_update;
wire   [0:0] full_n_nbwrite_fu_298_p5;
wire    ap_block_pp0_stage0_01001;
reg    cached_dramB_read_resp_V_last1_update;
wire   [0:0] full_n_1_nbwrite_fu_308_p5;
reg    dramA_write_req_data_V_last1_update;
wire   [0:0] full_n_2_nbwrite_fu_318_p5;
reg    dramB_write_req_data_V_last1_update;
wire   [0:0] full_n_3_nbwrite_fu_328_p5;
wire   [0:0] not_full_n_i_fu_790_p2;
wire   [0:0] not_full_n_i5_fu_803_p2;
wire   [0:0] not_full_n_i9_fu_816_p2;
wire   [0:0] not_full_n_i1_fu_829_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_250;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_cached_dramA_write_req_data_phi_fu_366_p4 == 1'd0) & (empty_n_10_fu_766_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_data_cached_dramA_write_req_data_0_2_reg_652 <= cached_dramA_write_req_data_V_last_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_cached_dramA_write_req_data_0_2_reg_652 <= ap_phi_reg_pp0_iter0_data_cached_dramA_write_req_data_0_2_reg_652;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_cached_dramA_write_req_data_phi_fu_366_p4 == 1'd0) & (empty_n_10_fu_766_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_data_cached_dramA_write_req_data_1_2_reg_640 <= cached_dramA_write_req_data_V_data_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_cached_dramA_write_req_data_1_2_reg_640 <= ap_phi_reg_pp0_iter0_data_cached_dramA_write_req_data_1_2_reg_640;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_cached_dramB_write_req_data_phi_fu_378_p4 == 1'd0) & (empty_n_11_fu_778_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_data_cached_dramB_write_req_data_0_2_reg_719 <= cached_dramB_write_req_data_V_last_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_cached_dramB_write_req_data_0_2_reg_719 <= ap_phi_reg_pp0_iter0_data_cached_dramB_write_req_data_0_2_reg_719;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_cached_dramB_write_req_data_phi_fu_378_p4 == 1'd0) & (empty_n_11_fu_778_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_data_cached_dramB_write_req_data_1_2_reg_707 <= cached_dramB_write_req_data_V_data_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_cached_dramB_write_req_data_1_2_reg_707 <= ap_phi_reg_pp0_iter0_data_cached_dramB_write_req_data_1_2_reg_707;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_dramA_read_resp_phi_fu_342_p4 == 1'd0) & (empty_n_8_fu_742_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_data_dramA_read_resp_0_2_reg_518 <= dramA_read_resp_V_last_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_dramA_read_resp_0_2_reg_518 <= ap_phi_reg_pp0_iter0_data_dramA_read_resp_0_2_reg_518;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_dramA_read_resp_phi_fu_342_p4 == 1'd0) & (empty_n_8_fu_742_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_data_dramA_read_resp_1_2_reg_506 <= dramA_read_resp_V_data_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_dramA_read_resp_1_2_reg_506 <= ap_phi_reg_pp0_iter0_data_dramA_read_resp_1_2_reg_506;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_dramB_read_resp_phi_fu_354_p4 == 1'd0) & (empty_n_9_fu_754_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_data_dramB_read_resp_0_2_reg_585 <= dramB_read_resp_V_last_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_dramB_read_resp_0_2_reg_585 <= ap_phi_reg_pp0_iter0_data_dramB_read_resp_0_2_reg_585;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_dramB_read_resp_phi_fu_354_p4 == 1'd0) & (empty_n_9_fu_754_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_data_dramB_read_resp_1_2_reg_573 <= dramB_read_resp_V_data_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_dramB_read_resp_1_2_reg_573 <= ap_phi_reg_pp0_iter0_data_dramB_read_resp_1_2_reg_573;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((empty_n_10_fu_766_p1 == 1'd1) & (ap_phi_mux_has_cached_dramA_write_req_data_phi_fu_366_p4 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_has_cached_dramA_write_req_data_1_reg_630 <= empty_n_2_nbread_fu_282_p3_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_has_cached_dramA_write_req_data_1_reg_630 <= ap_phi_reg_pp0_iter0_has_cached_dramA_write_req_data_1_reg_630;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_cached_dramA_write_req_data_phi_fu_366_p4 == 1'd0) & (empty_n_10_fu_766_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_has_cached_dramA_write_req_data_3_reg_664 <= empty_n_2_nbread_fu_282_p3_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_has_cached_dramA_write_req_data_3_reg_664 <= ap_phi_reg_pp0_iter0_has_cached_dramA_write_req_data_3_reg_664;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((empty_n_11_fu_778_p1 == 1'd1) & (ap_phi_mux_has_cached_dramB_write_req_data_phi_fu_378_p4 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_has_cached_dramB_write_req_data_1_reg_697 <= empty_n_3_nbread_fu_290_p3_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_has_cached_dramB_write_req_data_1_reg_697 <= ap_phi_reg_pp0_iter0_has_cached_dramB_write_req_data_1_reg_697;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_cached_dramB_write_req_data_phi_fu_378_p4 == 1'd0) & (empty_n_11_fu_778_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_has_cached_dramB_write_req_data_3_reg_731 <= empty_n_3_nbread_fu_290_p3_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_has_cached_dramB_write_req_data_3_reg_731 <= ap_phi_reg_pp0_iter0_has_cached_dramB_write_req_data_3_reg_731;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_dramA_read_resp_phi_fu_342_p4 == 1'd0) & (empty_n_8_fu_742_p1 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_has_dramA_read_resp_1_reg_496 <= empty_n_nbread_fu_266_p3_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_has_dramA_read_resp_1_reg_496 <= ap_phi_reg_pp0_iter0_has_dramA_read_resp_1_reg_496;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_dramA_read_resp_phi_fu_342_p4 == 1'd0) & (empty_n_8_fu_742_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_has_dramA_read_resp_3_reg_530 <= empty_n_nbread_fu_266_p3_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_has_dramA_read_resp_3_reg_530 <= ap_phi_reg_pp0_iter0_has_dramA_read_resp_3_reg_530;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((empty_n_9_fu_754_p1 == 1'd1) & (ap_phi_mux_has_dramB_read_resp_phi_fu_354_p4 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_has_dramB_read_resp_1_reg_563 <= empty_n_1_nbread_fu_274_p3_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_has_dramB_read_resp_1_reg_563 <= ap_phi_reg_pp0_iter0_has_dramB_read_resp_1_reg_563;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_dramB_read_resp_phi_fu_354_p4 == 1'd0) & (empty_n_9_fu_754_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_has_dramB_read_resp_3_reg_597 <= empty_n_1_nbread_fu_274_p3_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_has_dramB_read_resp_3_reg_597 <= ap_phi_reg_pp0_iter0_has_dramB_read_resp_3_reg_597;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((empty_n_9_fu_754_p1 == 1'd1) & (ap_phi_mux_has_dramB_read_resp_phi_fu_354_p4 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_tmp_data_V_2_reg_541 <= dramB_read_resp_V_data_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_tmp_data_V_2_reg_541 <= ap_phi_reg_pp0_iter0_tmp_data_V_2_reg_541;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((empty_n_10_fu_766_p1 == 1'd1) & (ap_phi_mux_has_cached_dramA_write_req_data_phi_fu_366_p4 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_tmp_data_V_4_reg_608 <= cached_dramA_write_req_data_V_data_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_tmp_data_V_4_reg_608 <= ap_phi_reg_pp0_iter0_tmp_data_V_4_reg_608;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((empty_n_11_fu_778_p1 == 1'd1) & (ap_phi_mux_has_cached_dramB_write_req_data_phi_fu_378_p4 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_tmp_data_V_6_reg_675 <= cached_dramB_write_req_data_V_data_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_tmp_data_V_6_reg_675 <= ap_phi_reg_pp0_iter0_tmp_data_V_6_reg_675;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_dramA_read_resp_phi_fu_342_p4 == 1'd0) & (empty_n_8_fu_742_p1 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_tmp_data_V_reg_474 <= dramA_read_resp_V_data_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_tmp_data_V_reg_474 <= ap_phi_reg_pp0_iter0_tmp_data_V_reg_474;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((empty_n_9_fu_754_p1 == 1'd1) & (ap_phi_mux_has_dramB_read_resp_phi_fu_354_p4 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_tmp_last_2_reg_552 <= dramB_read_resp_V_last_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_tmp_last_2_reg_552 <= ap_phi_reg_pp0_iter0_tmp_last_2_reg_552;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((empty_n_10_fu_766_p1 == 1'd1) & (ap_phi_mux_has_cached_dramA_write_req_data_phi_fu_366_p4 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_tmp_last_4_reg_619 <= cached_dramA_write_req_data_V_last_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_tmp_last_4_reg_619 <= ap_phi_reg_pp0_iter0_tmp_last_4_reg_619;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((empty_n_11_fu_778_p1 == 1'd1) & (ap_phi_mux_has_cached_dramB_write_req_data_phi_fu_378_p4 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_tmp_last_6_reg_686 <= cached_dramB_write_req_data_V_last_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_tmp_last_6_reg_686 <= ap_phi_reg_pp0_iter0_tmp_last_6_reg_686;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_250)) begin
        if (((ap_phi_mux_has_dramA_read_resp_phi_fu_342_p4 == 1'd0) & (empty_n_8_fu_742_p1 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_tmp_last_reg_485 <= dramA_read_resp_V_last_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_tmp_last_reg_485 <= ap_phi_reg_pp0_iter0_tmp_last_reg_485;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        has_cached_dramA_write_req_data_reg_362 <= ap_phi_mux_has_cached_dramA_write_req_data_3_phi_fu_668_p4;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        has_cached_dramA_write_req_data_reg_362 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        has_cached_dramB_write_req_data_reg_374 <= ap_phi_mux_has_cached_dramB_write_req_data_3_phi_fu_735_p4;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        has_cached_dramB_write_req_data_reg_374 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        has_dramA_read_resp_reg_338 <= ap_phi_mux_has_dramA_read_resp_3_phi_fu_534_p4;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        has_dramA_read_resp_reg_338 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        has_dramB_read_resp_reg_350 <= ap_phi_mux_has_dramB_read_resp_3_phi_fu_601_p4;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        has_dramB_read_resp_reg_350 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_cached_dramA_write_req_data_0_s_reg_419 <= ap_phi_mux_data_cached_dramA_write_req_data_0_2_phi_fu_656_p4;
        data_cached_dramA_write_req_data_1_s_reg_408 <= ap_phi_mux_data_cached_dramA_write_req_data_1_2_phi_fu_644_p4;
        data_cached_dramB_write_req_data_0_s_reg_397 <= ap_phi_mux_data_cached_dramB_write_req_data_0_2_phi_fu_723_p4;
        data_cached_dramB_write_req_data_1_s_reg_386 <= ap_phi_mux_data_cached_dramB_write_req_data_1_2_phi_fu_711_p4;
        data_dramA_read_resp_0_s_reg_463 <= ap_phi_mux_data_dramA_read_resp_0_2_phi_fu_522_p4;
        data_dramA_read_resp_1_s_reg_452 <= ap_phi_mux_data_dramA_read_resp_1_2_phi_fu_510_p4;
        data_dramB_read_resp_0_s_reg_441 <= ap_phi_mux_data_dramB_read_resp_0_2_phi_fu_589_p4;
        data_dramB_read_resp_1_s_reg_430 <= ap_phi_mux_data_dramB_read_resp_1_2_phi_fu_577_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_cached_dramA_write_req_data_phi_fu_366_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_n_10_reg_878 <= empty_n_2_nbread_fu_282_p3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_cached_dramB_write_req_data_phi_fu_378_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_n_11_reg_896 <= empty_n_3_nbread_fu_290_p3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_dramA_read_resp_phi_fu_342_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_n_8_reg_842 <= empty_n_nbread_fu_266_p3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_dramB_read_resp_phi_fu_354_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_n_9_reg_860 <= empty_n_1_nbread_fu_274_p3_0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((has_cached_dramA_write_req_data_reg_362 == 1'd1) | (empty_n_10_reg_878 == 1'd1)))) begin
        ap_phi_mux_data_cached_dramA_write_req_data_0_2_phi_fu_656_p4 = ap_phi_mux_tmp_last_4_phi_fu_622_p4;
    end else begin
        ap_phi_mux_data_cached_dramA_write_req_data_0_2_phi_fu_656_p4 = ap_phi_reg_pp0_iter1_data_cached_dramA_write_req_data_0_2_reg_652;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((has_cached_dramA_write_req_data_reg_362 == 1'd1) | (empty_n_10_reg_878 == 1'd1)))) begin
        ap_phi_mux_data_cached_dramA_write_req_data_1_2_phi_fu_644_p4 = ap_phi_mux_tmp_data_V_4_phi_fu_611_p4;
    end else begin
        ap_phi_mux_data_cached_dramA_write_req_data_1_2_phi_fu_644_p4 = ap_phi_reg_pp0_iter1_data_cached_dramA_write_req_data_1_2_reg_640;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((has_cached_dramB_write_req_data_reg_374 == 1'd1) | (empty_n_11_reg_896 == 1'd1)))) begin
        ap_phi_mux_data_cached_dramB_write_req_data_0_2_phi_fu_723_p4 = ap_phi_mux_tmp_last_6_phi_fu_689_p4;
    end else begin
        ap_phi_mux_data_cached_dramB_write_req_data_0_2_phi_fu_723_p4 = ap_phi_reg_pp0_iter1_data_cached_dramB_write_req_data_0_2_reg_719;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((has_cached_dramB_write_req_data_reg_374 == 1'd1) | (empty_n_11_reg_896 == 1'd1)))) begin
        ap_phi_mux_data_cached_dramB_write_req_data_1_2_phi_fu_711_p4 = ap_phi_mux_tmp_data_V_6_phi_fu_678_p4;
    end else begin
        ap_phi_mux_data_cached_dramB_write_req_data_1_2_phi_fu_711_p4 = ap_phi_reg_pp0_iter1_data_cached_dramB_write_req_data_1_2_reg_707;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((has_dramA_read_resp_reg_338 == 1'd1) | (empty_n_8_reg_842 == 1'd1)))) begin
        ap_phi_mux_data_dramA_read_resp_0_2_phi_fu_522_p4 = ap_phi_mux_tmp_last_phi_fu_488_p4;
    end else begin
        ap_phi_mux_data_dramA_read_resp_0_2_phi_fu_522_p4 = ap_phi_reg_pp0_iter1_data_dramA_read_resp_0_2_reg_518;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((has_dramA_read_resp_reg_338 == 1'd1) | (empty_n_8_reg_842 == 1'd1)))) begin
        ap_phi_mux_data_dramA_read_resp_1_2_phi_fu_510_p4 = ap_phi_mux_tmp_data_V_phi_fu_477_p4;
    end else begin
        ap_phi_mux_data_dramA_read_resp_1_2_phi_fu_510_p4 = ap_phi_reg_pp0_iter1_data_dramA_read_resp_1_2_reg_506;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((has_dramB_read_resp_reg_350 == 1'd1) | (empty_n_9_reg_860 == 1'd1)))) begin
        ap_phi_mux_data_dramB_read_resp_0_2_phi_fu_589_p4 = ap_phi_mux_tmp_last_2_phi_fu_555_p4;
    end else begin
        ap_phi_mux_data_dramB_read_resp_0_2_phi_fu_589_p4 = ap_phi_reg_pp0_iter1_data_dramB_read_resp_0_2_reg_585;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((has_dramB_read_resp_reg_350 == 1'd1) | (empty_n_9_reg_860 == 1'd1)))) begin
        ap_phi_mux_data_dramB_read_resp_1_2_phi_fu_577_p4 = ap_phi_mux_tmp_data_V_2_phi_fu_544_p4;
    end else begin
        ap_phi_mux_data_dramB_read_resp_1_2_phi_fu_577_p4 = ap_phi_reg_pp0_iter1_data_dramB_read_resp_1_2_reg_573;
    end
end

always @ (*) begin
    if (((has_cached_dramA_write_req_data_reg_362 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_has_cached_dramA_write_req_data_1_phi_fu_633_p4 = has_cached_dramA_write_req_data_reg_362;
    end else begin
        ap_phi_mux_has_cached_dramA_write_req_data_1_phi_fu_633_p4 = ap_phi_reg_pp0_iter1_has_cached_dramA_write_req_data_1_reg_630;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((has_cached_dramA_write_req_data_reg_362 == 1'd1) | (empty_n_10_reg_878 == 1'd1)))) begin
        ap_phi_mux_has_cached_dramA_write_req_data_3_phi_fu_668_p4 = p_has_cached_dramA_write_req_data_1_fu_822_p2;
    end else begin
        ap_phi_mux_has_cached_dramA_write_req_data_3_phi_fu_668_p4 = ap_phi_reg_pp0_iter1_has_cached_dramA_write_req_data_3_reg_664;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_has_cached_dramA_write_req_data_phi_fu_366_p4 = ap_phi_mux_has_cached_dramA_write_req_data_3_phi_fu_668_p4;
    end else begin
        ap_phi_mux_has_cached_dramA_write_req_data_phi_fu_366_p4 = has_cached_dramA_write_req_data_reg_362;
    end
end

always @ (*) begin
    if (((has_cached_dramB_write_req_data_reg_374 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_has_cached_dramB_write_req_data_1_phi_fu_700_p4 = has_cached_dramB_write_req_data_reg_374;
    end else begin
        ap_phi_mux_has_cached_dramB_write_req_data_1_phi_fu_700_p4 = ap_phi_reg_pp0_iter1_has_cached_dramB_write_req_data_1_reg_697;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((has_cached_dramB_write_req_data_reg_374 == 1'd1) | (empty_n_11_reg_896 == 1'd1)))) begin
        ap_phi_mux_has_cached_dramB_write_req_data_3_phi_fu_735_p4 = p_has_cached_dramB_write_req_data_1_fu_835_p2;
    end else begin
        ap_phi_mux_has_cached_dramB_write_req_data_3_phi_fu_735_p4 = ap_phi_reg_pp0_iter1_has_cached_dramB_write_req_data_3_reg_731;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_has_cached_dramB_write_req_data_phi_fu_378_p4 = ap_phi_mux_has_cached_dramB_write_req_data_3_phi_fu_735_p4;
    end else begin
        ap_phi_mux_has_cached_dramB_write_req_data_phi_fu_378_p4 = has_cached_dramB_write_req_data_reg_374;
    end
end

always @ (*) begin
    if (((has_dramA_read_resp_reg_338 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_has_dramA_read_resp_1_phi_fu_499_p4 = has_dramA_read_resp_reg_338;
    end else begin
        ap_phi_mux_has_dramA_read_resp_1_phi_fu_499_p4 = ap_phi_reg_pp0_iter1_has_dramA_read_resp_1_reg_496;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((has_dramA_read_resp_reg_338 == 1'd1) | (empty_n_8_reg_842 == 1'd1)))) begin
        ap_phi_mux_has_dramA_read_resp_3_phi_fu_534_p4 = p_has_dramA_read_resp_1_fu_796_p2;
    end else begin
        ap_phi_mux_has_dramA_read_resp_3_phi_fu_534_p4 = ap_phi_reg_pp0_iter1_has_dramA_read_resp_3_reg_530;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_has_dramA_read_resp_phi_fu_342_p4 = ap_phi_mux_has_dramA_read_resp_3_phi_fu_534_p4;
    end else begin
        ap_phi_mux_has_dramA_read_resp_phi_fu_342_p4 = has_dramA_read_resp_reg_338;
    end
end

always @ (*) begin
    if (((has_dramB_read_resp_reg_350 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_has_dramB_read_resp_1_phi_fu_566_p4 = has_dramB_read_resp_reg_350;
    end else begin
        ap_phi_mux_has_dramB_read_resp_1_phi_fu_566_p4 = ap_phi_reg_pp0_iter1_has_dramB_read_resp_1_reg_563;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((has_dramB_read_resp_reg_350 == 1'd1) | (empty_n_9_reg_860 == 1'd1)))) begin
        ap_phi_mux_has_dramB_read_resp_3_phi_fu_601_p4 = p_has_dramB_read_resp_1_fu_809_p2;
    end else begin
        ap_phi_mux_has_dramB_read_resp_3_phi_fu_601_p4 = ap_phi_reg_pp0_iter1_has_dramB_read_resp_3_reg_597;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_has_dramB_read_resp_phi_fu_354_p4 = ap_phi_mux_has_dramB_read_resp_3_phi_fu_601_p4;
    end else begin
        ap_phi_mux_has_dramB_read_resp_phi_fu_354_p4 = has_dramB_read_resp_reg_350;
    end
end

always @ (*) begin
    if (((has_dramB_read_resp_reg_350 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_tmp_data_V_2_phi_fu_544_p4 = data_dramB_read_resp_1_s_reg_430;
    end else begin
        ap_phi_mux_tmp_data_V_2_phi_fu_544_p4 = ap_phi_reg_pp0_iter1_tmp_data_V_2_reg_541;
    end
end

always @ (*) begin
    if (((has_cached_dramA_write_req_data_reg_362 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_tmp_data_V_4_phi_fu_611_p4 = data_cached_dramA_write_req_data_1_s_reg_408;
    end else begin
        ap_phi_mux_tmp_data_V_4_phi_fu_611_p4 = ap_phi_reg_pp0_iter1_tmp_data_V_4_reg_608;
    end
end

always @ (*) begin
    if (((has_cached_dramB_write_req_data_reg_374 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_tmp_data_V_6_phi_fu_678_p4 = data_cached_dramB_write_req_data_1_s_reg_386;
    end else begin
        ap_phi_mux_tmp_data_V_6_phi_fu_678_p4 = ap_phi_reg_pp0_iter1_tmp_data_V_6_reg_675;
    end
end

always @ (*) begin
    if (((has_dramA_read_resp_reg_338 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_tmp_data_V_phi_fu_477_p4 = data_dramA_read_resp_1_s_reg_452;
    end else begin
        ap_phi_mux_tmp_data_V_phi_fu_477_p4 = ap_phi_reg_pp0_iter1_tmp_data_V_reg_474;
    end
end

always @ (*) begin
    if (((has_dramB_read_resp_reg_350 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_tmp_last_2_phi_fu_555_p4 = data_dramB_read_resp_0_s_reg_441;
    end else begin
        ap_phi_mux_tmp_last_2_phi_fu_555_p4 = ap_phi_reg_pp0_iter1_tmp_last_2_reg_552;
    end
end

always @ (*) begin
    if (((has_cached_dramA_write_req_data_reg_362 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_tmp_last_4_phi_fu_622_p4 = data_cached_dramA_write_req_data_0_s_reg_419;
    end else begin
        ap_phi_mux_tmp_last_4_phi_fu_622_p4 = ap_phi_reg_pp0_iter1_tmp_last_4_reg_619;
    end
end

always @ (*) begin
    if (((has_cached_dramB_write_req_data_reg_374 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_tmp_last_6_phi_fu_689_p4 = data_cached_dramB_write_req_data_0_s_reg_397;
    end else begin
        ap_phi_mux_tmp_last_6_phi_fu_689_p4 = ap_phi_reg_pp0_iter1_tmp_last_6_reg_686;
    end
end

always @ (*) begin
    if (((has_dramA_read_resp_reg_338 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_tmp_last_phi_fu_488_p4 = data_dramA_read_resp_0_s_reg_463;
    end else begin
        ap_phi_mux_tmp_last_phi_fu_488_p4 = ap_phi_reg_pp0_iter1_tmp_last_reg_485;
    end
end

always @ (*) begin
    if ((((cached_dramA_read_resp_V_last_full_n & cached_dramA_read_resp_V_data_V_full_n) == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & ((has_dramA_read_resp_reg_338 == 1'd1) | (empty_n_8_reg_842 == 1'd1)))) begin
        cached_dramA_read_resp_V_last1_update = 1'b1;
    end else begin
        cached_dramA_read_resp_V_last1_update = 1'b0;
    end
end

always @ (*) begin
    if ((((cached_dramA_write_req_data_V_last_empty_n & cached_dramA_write_req_data_V_data_V_empty_n) == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_cached_dramA_write_req_data_phi_fu_366_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cached_dramA_write_req_data_V_last0_update = 1'b1;
    end else begin
        cached_dramA_write_req_data_V_last0_update = 1'b0;
    end
end

always @ (*) begin
    if ((((cached_dramB_read_resp_V_last_full_n & cached_dramB_read_resp_V_data_V_full_n) == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & ((has_dramB_read_resp_reg_350 == 1'd1) | (empty_n_9_reg_860 == 1'd1)))) begin
        cached_dramB_read_resp_V_last1_update = 1'b1;
    end else begin
        cached_dramB_read_resp_V_last1_update = 1'b0;
    end
end

always @ (*) begin
    if ((((cached_dramB_write_req_data_V_last_empty_n & cached_dramB_write_req_data_V_data_V_empty_n) == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_cached_dramB_write_req_data_phi_fu_378_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cached_dramB_write_req_data_V_last0_update = 1'b1;
    end else begin
        cached_dramB_write_req_data_V_last0_update = 1'b0;
    end
end

always @ (*) begin
    if ((((dramA_read_resp_V_last_empty_n & dramA_read_resp_V_data_V_empty_n) == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_dramA_read_resp_phi_fu_342_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        dramA_read_resp_V_last0_update = 1'b1;
    end else begin
        dramA_read_resp_V_last0_update = 1'b0;
    end
end

always @ (*) begin
    if ((((dramA_write_req_data_V_last_full_n & dramA_write_req_data_V_data_V_full_n) == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & ((has_cached_dramA_write_req_data_reg_362 == 1'd1) | (empty_n_10_reg_878 == 1'd1)))) begin
        dramA_write_req_data_V_last1_update = 1'b1;
    end else begin
        dramA_write_req_data_V_last1_update = 1'b0;
    end
end

always @ (*) begin
    if ((((dramB_read_resp_V_last_empty_n & dramB_read_resp_V_data_V_empty_n) == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_dramB_read_resp_phi_fu_354_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        dramB_read_resp_V_last0_update = 1'b1;
    end else begin
        dramB_read_resp_V_last0_update = 1'b0;
    end
end

always @ (*) begin
    if ((((dramB_write_req_data_V_last_full_n & dramB_write_req_data_V_data_V_full_n) == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & ((has_cached_dramB_write_req_data_reg_374 == 1'd1) | (empty_n_11_reg_896 == 1'd1)))) begin
        dramB_write_req_data_V_last1_update = 1'b1;
    end else begin
        dramB_write_req_data_V_last1_update = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_250 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_done = 1'b0;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_data_cached_dramA_write_req_data_0_2_reg_652 = 'bx;

assign ap_phi_reg_pp0_iter0_data_cached_dramA_write_req_data_1_2_reg_640 = 'bx;

assign ap_phi_reg_pp0_iter0_data_cached_dramB_write_req_data_0_2_reg_719 = 'bx;

assign ap_phi_reg_pp0_iter0_data_cached_dramB_write_req_data_1_2_reg_707 = 'bx;

assign ap_phi_reg_pp0_iter0_data_dramA_read_resp_0_2_reg_518 = 'bx;

assign ap_phi_reg_pp0_iter0_data_dramA_read_resp_1_2_reg_506 = 'bx;

assign ap_phi_reg_pp0_iter0_data_dramB_read_resp_0_2_reg_585 = 'bx;

assign ap_phi_reg_pp0_iter0_data_dramB_read_resp_1_2_reg_573 = 'bx;

assign ap_phi_reg_pp0_iter0_has_cached_dramA_write_req_data_1_reg_630 = 'bx;

assign ap_phi_reg_pp0_iter0_has_cached_dramA_write_req_data_3_reg_664 = 'bx;

assign ap_phi_reg_pp0_iter0_has_cached_dramB_write_req_data_1_reg_697 = 'bx;

assign ap_phi_reg_pp0_iter0_has_cached_dramB_write_req_data_3_reg_731 = 'bx;

assign ap_phi_reg_pp0_iter0_has_dramA_read_resp_1_reg_496 = 'bx;

assign ap_phi_reg_pp0_iter0_has_dramA_read_resp_3_reg_530 = 'bx;

assign ap_phi_reg_pp0_iter0_has_dramB_read_resp_1_reg_563 = 'bx;

assign ap_phi_reg_pp0_iter0_has_dramB_read_resp_3_reg_597 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_data_V_2_reg_541 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_data_V_4_reg_608 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_data_V_6_reg_675 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_data_V_reg_474 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_last_2_reg_552 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_last_4_reg_619 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_last_6_reg_686 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_last_reg_485 = 'bx;

assign ap_ready = 1'b0;

assign cached_dramA_read_resp_V_data_V_din = ap_phi_mux_tmp_data_V_phi_fu_477_p4;

assign cached_dramA_read_resp_V_data_V_write = cached_dramA_read_resp_V_last1_update;

assign cached_dramA_read_resp_V_last_din = ap_phi_mux_tmp_last_phi_fu_488_p4;

assign cached_dramA_read_resp_V_last_write = cached_dramA_read_resp_V_last1_update;

assign cached_dramA_write_req_data_V_data_V_read = cached_dramA_write_req_data_V_last0_update;

assign cached_dramA_write_req_data_V_last_read = cached_dramA_write_req_data_V_last0_update;

assign cached_dramB_read_resp_V_data_V_din = ap_phi_mux_tmp_data_V_2_phi_fu_544_p4;

assign cached_dramB_read_resp_V_data_V_write = cached_dramB_read_resp_V_last1_update;

assign cached_dramB_read_resp_V_last_din = ap_phi_mux_tmp_last_2_phi_fu_555_p4;

assign cached_dramB_read_resp_V_last_write = cached_dramB_read_resp_V_last1_update;

assign cached_dramB_write_req_data_V_data_V_read = cached_dramB_write_req_data_V_last0_update;

assign cached_dramB_write_req_data_V_last_read = cached_dramB_write_req_data_V_last0_update;

assign dramA_read_resp_V_data_V_read = dramA_read_resp_V_last0_update;

assign dramA_read_resp_V_last_read = dramA_read_resp_V_last0_update;

assign dramA_write_req_data_V_data_V_din = ap_phi_mux_tmp_data_V_4_phi_fu_611_p4;

assign dramA_write_req_data_V_data_V_write = dramA_write_req_data_V_last1_update;

assign dramA_write_req_data_V_last_din = ap_phi_mux_tmp_last_4_phi_fu_622_p4;

assign dramA_write_req_data_V_last_write = dramA_write_req_data_V_last1_update;

assign dramB_read_resp_V_data_V_read = dramB_read_resp_V_last0_update;

assign dramB_read_resp_V_last_read = dramB_read_resp_V_last0_update;

assign dramB_write_req_data_V_data_V_din = ap_phi_mux_tmp_data_V_6_phi_fu_678_p4;

assign dramB_write_req_data_V_data_V_write = dramB_write_req_data_V_last1_update;

assign dramB_write_req_data_V_last_din = ap_phi_mux_tmp_last_6_phi_fu_689_p4;

assign dramB_write_req_data_V_last_write = dramB_write_req_data_V_last1_update;

assign empty_n_10_fu_766_p1 = empty_n_2_nbread_fu_282_p3_0;

assign empty_n_11_fu_778_p1 = empty_n_3_nbread_fu_290_p3_0;

assign empty_n_1_nbread_fu_274_p3_0 = (dramB_read_resp_V_last_empty_n & dramB_read_resp_V_data_V_empty_n);

assign empty_n_2_nbread_fu_282_p3_0 = (cached_dramA_write_req_data_V_last_empty_n & cached_dramA_write_req_data_V_data_V_empty_n);

assign empty_n_3_nbread_fu_290_p3_0 = (cached_dramB_write_req_data_V_last_empty_n & cached_dramB_write_req_data_V_data_V_empty_n);

assign empty_n_8_fu_742_p1 = empty_n_nbread_fu_266_p3_0;

assign empty_n_9_fu_754_p1 = empty_n_1_nbread_fu_274_p3_0;

assign empty_n_nbread_fu_266_p3_0 = (dramA_read_resp_V_last_empty_n & dramA_read_resp_V_data_V_empty_n);

assign full_n_1_nbwrite_fu_308_p5 = (cached_dramB_read_resp_V_last_full_n & cached_dramB_read_resp_V_data_V_full_n);

assign full_n_2_nbwrite_fu_318_p5 = (dramA_write_req_data_V_last_full_n & dramA_write_req_data_V_data_V_full_n);

assign full_n_3_nbwrite_fu_328_p5 = (dramB_write_req_data_V_last_full_n & dramB_write_req_data_V_data_V_full_n);

assign full_n_nbwrite_fu_298_p5 = (cached_dramA_read_resp_V_last_full_n & cached_dramA_read_resp_V_data_V_full_n);

assign not_full_n_i1_fu_829_p2 = (full_n_3_nbwrite_fu_328_p5 ^ 1'd1);

assign not_full_n_i5_fu_803_p2 = (full_n_1_nbwrite_fu_308_p5 ^ 1'd1);

assign not_full_n_i9_fu_816_p2 = (full_n_2_nbwrite_fu_318_p5 ^ 1'd1);

assign not_full_n_i_fu_790_p2 = (full_n_nbwrite_fu_298_p5 ^ 1'd1);

assign p_has_cached_dramA_write_req_data_1_fu_822_p2 = (not_full_n_i9_fu_816_p2 & ap_phi_mux_has_cached_dramA_write_req_data_1_phi_fu_633_p4);

assign p_has_cached_dramB_write_req_data_1_fu_835_p2 = (not_full_n_i1_fu_829_p2 & ap_phi_mux_has_cached_dramB_write_req_data_1_phi_fu_700_p4);

assign p_has_dramA_read_resp_1_fu_796_p2 = (not_full_n_i_fu_790_p2 & ap_phi_mux_has_dramA_read_resp_1_phi_fu_499_p4);

assign p_has_dramB_read_resp_1_fu_809_p2 = (not_full_n_i5_fu_803_p2 & ap_phi_mux_has_dramB_read_resp_1_phi_fu_566_p4);

endmodule //dram_data_caching
