// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.op
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="peek_handler,hls_ip_2017_4_op,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.047500,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=216,HLS_SYN_LUT=563}" *)

module peek_handler (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
ap_continue,
        ap_idle,
        ap_ready,
        peek_req_V_dout,
        peek_req_V_empty_n,
        peek_req_V_read,
        peek_resp_V_din,
        peek_resp_V_full_n,
        peek_resp_V_write,
        peek_real_written_bytes_req_V_din,
        peek_real_written_bytes_req_V_full_n,
        peek_real_written_bytes_req_V_write,
        peek_real_written_bytes_resp_V_dout,
        peek_real_written_bytes_resp_V_empty_n,
        peek_real_written_bytes_resp_V_read,
        peek_write_finished_req_V_din,
        peek_write_finished_req_V_full_n,
        peek_write_finished_req_V_write,
        peek_write_finished_resp_V_dout,
        peek_write_finished_resp_V_empty_n,
        peek_write_finished_resp_V_read,
        peek_virt_written_bytes_req_V_din,
        peek_virt_written_bytes_req_V_full_n,
        peek_virt_written_bytes_req_V_write,
        peek_virt_written_bytes_resp_V_dout,
        peek_virt_written_bytes_resp_V_empty_n,
        peek_virt_written_bytes_resp_V_read,
        dbg_peek_resp_V_dout,
        dbg_peek_resp_V_empty_n,
        dbg_peek_resp_V_read
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output ap_ready; output ap_continue;
input  [31:0] peek_req_V_dout;
input   peek_req_V_empty_n;
output   peek_req_V_read;
output  [31:0] peek_resp_V_din;
input   peek_resp_V_full_n;
output   peek_resp_V_write;
output  [31:0] peek_real_written_bytes_req_V_din;
input   peek_real_written_bytes_req_V_full_n;
output   peek_real_written_bytes_req_V_write;
input  [31:0] peek_real_written_bytes_resp_V_dout;
input   peek_real_written_bytes_resp_V_empty_n;
output   peek_real_written_bytes_resp_V_read;
output  [31:0] peek_write_finished_req_V_din;
input   peek_write_finished_req_V_full_n;
output   peek_write_finished_req_V_write;
input  [31:0] peek_write_finished_resp_V_dout;
input   peek_write_finished_resp_V_empty_n;
output   peek_write_finished_resp_V_read;
output  [31:0] peek_virt_written_bytes_req_V_din;
input   peek_virt_written_bytes_req_V_full_n;
output   peek_virt_written_bytes_req_V_write;
input  [31:0] peek_virt_written_bytes_resp_V_dout;
input   peek_virt_written_bytes_resp_V_empty_n;
output   peek_virt_written_bytes_resp_V_read;
input  [31:0] dbg_peek_resp_V_dout;
input   dbg_peek_resp_V_empty_n;
output   dbg_peek_resp_V_read;

reg ap_idle;
reg peek_req_V_read;
reg[31:0] peek_resp_V_din;
reg peek_resp_V_write;
reg peek_real_written_bytes_req_V_write;
reg peek_real_written_bytes_resp_V_read;
reg peek_write_finished_req_V_write;
reg peek_write_finished_resp_V_read;
reg peek_virt_written_bytes_req_V_write;
reg peek_virt_written_bytes_resp_V_read;
reg dbg_peek_resp_V_read;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    peek_resp_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] has_inflight_req_reg_255;
reg   [0:0] ap_reg_pp0_iter1_has_inflight_req_reg_255;
reg   [0:0] tmp_7_reg_569;
reg   [0:0] tmp_10_reg_573;
reg   [0:0] tmp_reg_589;
reg   [0:0] empty_n_1_reg_632;
reg   [0:0] tmp_3_reg_593;
reg   [0:0] empty_n_2_reg_623;
reg   [0:0] tmp_8_reg_597;
reg   [0:0] empty_n_3_reg_614;
reg   [0:0] tmp_s_reg_601;
reg   [0:0] empty_n_4_reg_605;
reg    peek_real_written_bytes_req_V_blk_n;
reg   [0:0] tmp_12_reg_577;
reg    peek_write_finished_req_V_blk_n;
reg   [0:0] tmp_14_reg_581;
reg    peek_virt_written_bytes_req_V_blk_n;
reg   [0:0] tmp_17_reg_585;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_predicate_op98_write_state4;
reg    ap_predicate_op101_write_state4;
reg    ap_predicate_op104_write_state4;
reg    ap_predicate_op106_write_state4;
reg    ap_predicate_op107_write_state4;
reg    ap_predicate_op108_write_state4;
reg    ap_predicate_op109_write_state4;
reg    ap_predicate_op110_write_state4;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] empty_n_reg_551;
reg   [0:0] ap_phi_mux_has_inflight_req_phi_fu_259_p4;
reg   [31:0] tmp_15_reg_558;
reg   [31:0] ap_reg_pp0_iter1_tmp_15_reg_558;
wire   [0:0] tmp_7_fu_427_p2;
wire   [0:0] tmp_10_fu_433_p2;
wire   [0:0] tmp_12_fu_439_p2;
wire   [0:0] tmp_14_fu_445_p2;
wire   [0:0] tmp_17_fu_451_p2;
wire   [0:0] tmp_fu_465_p2;
wire   [0:0] tmp_3_fu_471_p2;
wire   [0:0] tmp_8_fu_477_p2;
wire   [0:0] tmp_s_fu_483_p2;
wire   [0:0] empty_n_4_fu_489_p1;
reg   [31:0] tmp_18_reg_609;
wire   [0:0] empty_n_3_fu_502_p1;
reg   [31:0] tmp_16_reg_618;
wire   [0:0] empty_n_2_fu_515_p1;
reg   [31:0] tmp_13_reg_627;
wire   [0:0] empty_n_1_fu_528_p1;
reg   [31:0] tmp_11_reg_636;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_has_inflight_req_s_phi_fu_271_p24;
wire   [0:0] ap_phi_reg_pp0_iter1_has_inflight_req_s_reg_267;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] inflight_req_state_s_fu_192;
wire   [7:0] inflight_req_state_cast_fu_423_p1;
wire   [0:0] tmp_2_fu_333_p2;
wire   [2:0] state_fu_338_p3;
wire   [0:0] tmp_4_fu_318_p2;
wire   [0:0] sel_tmp2_fu_353_p2;
wire   [2:0] sel_tmp1_fu_346_p3;
wire   [0:0] sel_tmp4_fu_366_p2;
wire   [0:0] sel_tmp5_fu_372_p2;
wire   [0:0] tmp_9_fu_323_p2;
wire   [0:0] tmp_1_fu_328_p2;
wire   [0:0] sel_tmp_fu_383_p2;
wire   [0:0] tmp2_fu_389_p2;
wire   [0:0] sel_tmp8_fu_395_p2;
wire   [0:0] sel_tmp6_fu_377_p2;
wire   [0:0] tmp_5_fu_409_p2;
wire   [2:0] sel_tmp7_fu_401_p3;
wire   [2:0] sel_tmp3_fu_358_p3;
wire   [2:0] inflight_req_state_fu_415_p3;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_207;
reg    ap_condition_234;
reg    ap_condition_240;
reg    ap_condition_246;
reg    ap_condition_266;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        has_inflight_req_reg_255 <= ap_phi_mux_has_inflight_req_s_phi_fu_271_p24;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        has_inflight_req_reg_255 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_266)) begin
        if (((tmp_fu_465_p2 == 1'd1) & (has_inflight_req_reg_255 == 1'd1))) begin
                        inflight_req_state_s_fu_192[0] <= 1'b0;
            inflight_req_state_s_fu_192[1] <= 1'b1;
            inflight_req_state_s_fu_192[2] <= 1'b0;
        end else if ((1'b1 == ap_condition_246)) begin
                        inflight_req_state_s_fu_192[0] <= 1'b1;
            inflight_req_state_s_fu_192[1] <= 1'b1;
            inflight_req_state_s_fu_192[2] <= 1'b0;
        end else if ((1'b1 == ap_condition_240)) begin
                        inflight_req_state_s_fu_192[0] <= 1'b0;
            inflight_req_state_s_fu_192[1] <= 1'b0;
            inflight_req_state_s_fu_192[2] <= 1'b1;
        end else if ((1'b1 == ap_condition_234)) begin
                        inflight_req_state_s_fu_192[0] <= 1'b1;
            inflight_req_state_s_fu_192[1] <= 1'b0;
            inflight_req_state_s_fu_192[2] <= 1'b1;
        end else if ((1'b1 == ap_condition_207)) begin
                        inflight_req_state_s_fu_192[2 : 0] <= inflight_req_state_cast_fu_423_p1[2 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_reg_pp0_iter1_has_inflight_req_reg_255 <= has_inflight_req_reg_255;
        ap_reg_pp0_iter1_tmp_15_reg_558 <= tmp_15_reg_558;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_465_p2 == 1'd1) & (has_inflight_req_reg_255 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_n_1_reg_632 <= peek_real_written_bytes_resp_V_empty_n;
        tmp_11_reg_636 <= peek_real_written_bytes_resp_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_471_p2 == 1'd1) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_n_2_reg_623 <= peek_write_finished_resp_V_empty_n;
        tmp_13_reg_627 <= peek_write_finished_resp_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_8_fu_477_p2 == 1'd1) & (tmp_3_fu_471_p2 == 1'd0) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_n_3_reg_614 <= peek_virt_written_bytes_resp_V_empty_n;
        tmp_16_reg_618 <= peek_virt_written_bytes_resp_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_483_p2 == 1'd1) & (tmp_8_fu_477_p2 == 1'd0) & (tmp_3_fu_471_p2 == 1'd0) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_n_4_reg_605 <= dbg_peek_resp_V_empty_n;
        tmp_18_reg_609 <= dbg_peek_resp_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_has_inflight_req_phi_fu_259_p4 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_n_reg_551 <= peek_req_V_empty_n;
        tmp_15_reg_558 <= peek_req_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_427_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_10_reg_573 <= tmp_10_fu_433_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_10_fu_433_p2 == 1'd0) & (tmp_7_fu_427_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_12_reg_577 <= tmp_12_fu_439_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_fu_439_p2 == 1'd0) & (tmp_10_fu_433_p2 == 1'd0) & (tmp_7_fu_427_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_14_reg_581 <= tmp_14_fu_445_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_14_fu_445_p2 == 1'd0) & (tmp_12_fu_439_p2 == 1'd0) & (tmp_10_fu_433_p2 == 1'd0) & (tmp_7_fu_427_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_17_reg_585 <= tmp_17_fu_451_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_3_reg_593 <= tmp_3_fu_471_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((has_inflight_req_reg_255 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_7_reg_569 <= tmp_7_fu_427_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_471_p2 == 1'd0) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_8_reg_597 <= tmp_8_fu_477_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((has_inflight_req_reg_255 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_reg_589 <= tmp_fu_465_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_8_fu_477_p2 == 1'd0) & (tmp_3_fu_471_p2 == 1'd0) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_s_reg_601 <= tmp_s_fu_483_p2;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_has_inflight_req_phi_fu_259_p4 = ap_phi_mux_has_inflight_req_s_phi_fu_271_p24;
    end else begin
        ap_phi_mux_has_inflight_req_phi_fu_259_p4 = has_inflight_req_reg_255;
    end
end

always @ (*) begin
    if ((((tmp_fu_465_p2 == 1'd1) & (empty_n_1_fu_528_p1 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_3_fu_471_p2 == 1'd1) & (empty_n_2_fu_515_p1 == 1'd0) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_8_fu_477_p2 == 1'd1) & (empty_n_3_fu_502_p1 == 1'd0) & (tmp_3_fu_471_p2 == 1'd0) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_s_fu_483_p2 == 1'd0) & (tmp_8_fu_477_p2 == 1'd0) & (tmp_3_fu_471_p2 == 1'd0) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_s_fu_483_p2 == 1'd1) & (empty_n_4_fu_489_p1 == 1'd0) & (tmp_8_fu_477_p2 == 1'd0) & (tmp_3_fu_471_p2 == 1'd0) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_10_fu_433_p2 == 1'd0) & (tmp_7_fu_427_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_mux_has_inflight_req_s_phi_fu_271_p24 = 1'd1;
    end else if ((((empty_n_1_fu_528_p1 == 1'd1) & (tmp_fu_465_p2 == 1'd1) & (has_inflight_req_reg_255 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_2_fu_515_p1 == 1'd1) & (tmp_3_fu_471_p2 == 1'd1) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_3_fu_502_p1 == 1'd1) & (tmp_8_fu_477_p2 == 1'd1) & (tmp_3_fu_471_p2 == 1'd0) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((empty_n_4_fu_489_p1 == 1'd1) & (tmp_s_fu_483_p2 == 1'd1) & (tmp_8_fu_477_p2 == 1'd0) & (tmp_3_fu_471_p2 == 1'd0) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_7_fu_427_p2 == 1'd1) & (has_inflight_req_reg_255 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_10_fu_433_p2 == 1'd1) & (tmp_7_fu_427_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_mux_has_inflight_req_s_phi_fu_271_p24 = 1'd0;
    end else begin
        ap_phi_mux_has_inflight_req_s_phi_fu_271_p24 = ap_phi_reg_pp0_iter1_has_inflight_req_s_reg_267;
    end
end

always @ (*) begin
    if (((tmp_s_fu_483_p2 == 1'd1) & (tmp_8_fu_477_p2 == 1'd0) & (tmp_3_fu_471_p2 == 1'd0) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (dbg_peek_resp_V_empty_n == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        dbg_peek_resp_V_read = 1'b1;
    end else begin
        dbg_peek_resp_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_12_reg_577 == 1'd1) & (tmp_10_reg_573 == 1'd0) & (tmp_7_reg_569 == 1'd0) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        peek_real_written_bytes_req_V_blk_n = peek_real_written_bytes_req_V_full_n;
    end else begin
        peek_real_written_bytes_req_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op104_write_state4 == 1'b1))) begin
        peek_real_written_bytes_req_V_write = 1'b1;
    end else begin
        peek_real_written_bytes_req_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_465_p2 == 1'd1) & (has_inflight_req_reg_255 == 1'd1) & (peek_real_written_bytes_resp_V_empty_n == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        peek_real_written_bytes_resp_V_read = 1'b1;
    end else begin
        peek_real_written_bytes_resp_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_has_inflight_req_phi_fu_259_p4 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (peek_req_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        peek_req_V_read = 1'b1;
    end else begin
        peek_req_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((empty_n_4_reg_605 == 1'd1) & (tmp_s_reg_601 == 1'd1) & (tmp_8_reg_597 == 1'd0) & (tmp_3_reg_593 == 1'd0) & (tmp_reg_589 == 1'd0) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_8_reg_597 == 1'd1) & (empty_n_3_reg_614 == 1'd1) & (tmp_3_reg_593 == 1'd0) & (tmp_reg_589 == 1'd0) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((empty_n_2_reg_623 == 1'd1) & (tmp_3_reg_593 == 1'd1) & (tmp_reg_589 == 1'd0) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((empty_n_1_reg_632 == 1'd1) & (tmp_reg_589 == 1'd1) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_10_reg_573 == 1'd1) & (tmp_7_reg_569 == 1'd0) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        peek_resp_V_blk_n = peek_resp_V_full_n;
    end else begin
        peek_resp_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op110_write_state4 == 1'b1)) begin
            peek_resp_V_din = tmp_11_reg_636;
        end else if ((ap_predicate_op109_write_state4 == 1'b1)) begin
            peek_resp_V_din = tmp_13_reg_627;
        end else if ((ap_predicate_op108_write_state4 == 1'b1)) begin
            peek_resp_V_din = tmp_16_reg_618;
        end else if ((ap_predicate_op107_write_state4 == 1'b1)) begin
            peek_resp_V_din = tmp_18_reg_609;
        end else if ((ap_predicate_op106_write_state4 == 1'b1)) begin
            peek_resp_V_din = 32'd0;
        end else begin
            peek_resp_V_din = 'bx;
        end
    end else begin
        peek_resp_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op110_write_state4 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op109_write_state4 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op108_write_state4 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op107_write_state4 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op106_write_state4 == 1'b1)))) begin
        peek_resp_V_write = 1'b1;
    end else begin
        peek_resp_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_17_reg_585 == 1'd1) & (tmp_10_reg_573 == 1'd0) & (tmp_7_reg_569 == 1'd0) & (tmp_14_reg_581 == 1'd0) & (tmp_12_reg_577 == 1'd0) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        peek_virt_written_bytes_req_V_blk_n = peek_virt_written_bytes_req_V_full_n;
    end else begin
        peek_virt_written_bytes_req_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op98_write_state4 == 1'b1))) begin
        peek_virt_written_bytes_req_V_write = 1'b1;
    end else begin
        peek_virt_written_bytes_req_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_8_fu_477_p2 == 1'd1) & (tmp_3_fu_471_p2 == 1'd0) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (peek_virt_written_bytes_resp_V_empty_n == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        peek_virt_written_bytes_resp_V_read = 1'b1;
    end else begin
        peek_virt_written_bytes_resp_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_14_reg_581 == 1'd1) & (tmp_10_reg_573 == 1'd0) & (tmp_7_reg_569 == 1'd0) & (tmp_12_reg_577 == 1'd0) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        peek_write_finished_req_V_blk_n = peek_write_finished_req_V_full_n;
    end else begin
        peek_write_finished_req_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op101_write_state4 == 1'b1))) begin
        peek_write_finished_req_V_write = 1'b1;
    end else begin
        peek_write_finished_req_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_3_fu_471_p2 == 1'd1) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1) & (peek_write_finished_resp_V_empty_n == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        peek_write_finished_resp_V_read = 1'b1;
    end else begin
        peek_write_finished_resp_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((peek_resp_V_full_n == 1'b0) & (ap_predicate_op110_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op109_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op108_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op107_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op106_write_state4 == 1'b1)) | ((peek_real_written_bytes_req_V_full_n == 1'b0) & (ap_predicate_op104_write_state4 == 1'b1)) | ((peek_write_finished_req_V_full_n == 1'b0) & (ap_predicate_op101_write_state4 == 1'b1)) | ((peek_virt_written_bytes_req_V_full_n == 1'b0) & (ap_predicate_op98_write_state4 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((peek_resp_V_full_n == 1'b0) & (ap_predicate_op110_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op109_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op108_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op107_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op106_write_state4 == 1'b1)) | ((peek_real_written_bytes_req_V_full_n == 1'b0) & (ap_predicate_op104_write_state4 == 1'b1)) | ((peek_write_finished_req_V_full_n == 1'b0) & (ap_predicate_op101_write_state4 == 1'b1)) | ((peek_virt_written_bytes_req_V_full_n == 1'b0) & (ap_predicate_op98_write_state4 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((peek_resp_V_full_n == 1'b0) & (ap_predicate_op110_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op109_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op108_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op107_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op106_write_state4 == 1'b1)) | ((peek_real_written_bytes_req_V_full_n == 1'b0) & (ap_predicate_op104_write_state4 == 1'b1)) | ((peek_write_finished_req_V_full_n == 1'b0) & (ap_predicate_op101_write_state4 == 1'b1)) | ((peek_virt_written_bytes_req_V_full_n == 1'b0) & (ap_predicate_op98_write_state4 == 1'b1))));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = (((peek_resp_V_full_n == 1'b0) & (ap_predicate_op110_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op109_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op108_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op107_write_state4 == 1'b1)) | ((peek_resp_V_full_n == 1'b0) & (ap_predicate_op106_write_state4 == 1'b1)) | ((peek_real_written_bytes_req_V_full_n == 1'b0) & (ap_predicate_op104_write_state4 == 1'b1)) | ((peek_write_finished_req_V_full_n == 1'b0) & (ap_predicate_op101_write_state4 == 1'b1)) | ((peek_virt_written_bytes_req_V_full_n == 1'b0) & (ap_predicate_op98_write_state4 == 1'b1)));
end

always @ (*) begin
    ap_condition_207 = ((tmp_10_fu_433_p2 == 1'd0) & (tmp_7_fu_427_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd0));
end

always @ (*) begin
    ap_condition_234 = ((tmp_s_fu_483_p2 == 1'd1) & (tmp_8_fu_477_p2 == 1'd0) & (tmp_3_fu_471_p2 == 1'd0) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1));
end

always @ (*) begin
    ap_condition_240 = ((tmp_8_fu_477_p2 == 1'd1) & (tmp_3_fu_471_p2 == 1'd0) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1));
end

always @ (*) begin
    ap_condition_246 = ((tmp_3_fu_471_p2 == 1'd1) & (tmp_fu_465_p2 == 1'd0) & (has_inflight_req_reg_255 == 1'd1));
end

always @ (*) begin
    ap_condition_266 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_done = 1'b0;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter1_has_inflight_req_s_reg_267 = 'bx;

always @ (*) begin
    ap_predicate_op101_write_state4 = ((tmp_14_reg_581 == 1'd1) & (tmp_10_reg_573 == 1'd0) & (tmp_7_reg_569 == 1'd0) & (tmp_12_reg_577 == 1'd0) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd0));
end

always @ (*) begin
    ap_predicate_op104_write_state4 = ((tmp_12_reg_577 == 1'd1) & (tmp_10_reg_573 == 1'd0) & (tmp_7_reg_569 == 1'd0) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd0));
end

always @ (*) begin
    ap_predicate_op106_write_state4 = ((tmp_10_reg_573 == 1'd1) & (tmp_7_reg_569 == 1'd0) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd0));
end

always @ (*) begin
    ap_predicate_op107_write_state4 = ((empty_n_4_reg_605 == 1'd1) & (tmp_s_reg_601 == 1'd1) & (tmp_8_reg_597 == 1'd0) & (tmp_3_reg_593 == 1'd0) & (tmp_reg_589 == 1'd0) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd1));
end

always @ (*) begin
    ap_predicate_op108_write_state4 = ((tmp_8_reg_597 == 1'd1) & (empty_n_3_reg_614 == 1'd1) & (tmp_3_reg_593 == 1'd0) & (tmp_reg_589 == 1'd0) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd1));
end

always @ (*) begin
    ap_predicate_op109_write_state4 = ((empty_n_2_reg_623 == 1'd1) & (tmp_3_reg_593 == 1'd1) & (tmp_reg_589 == 1'd0) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd1));
end

always @ (*) begin
    ap_predicate_op110_write_state4 = ((empty_n_1_reg_632 == 1'd1) & (tmp_reg_589 == 1'd1) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd1));
end

always @ (*) begin
    ap_predicate_op98_write_state4 = ((tmp_17_reg_585 == 1'd1) & (tmp_10_reg_573 == 1'd0) & (tmp_7_reg_569 == 1'd0) & (tmp_14_reg_581 == 1'd0) & (tmp_12_reg_577 == 1'd0) & (ap_reg_pp0_iter1_has_inflight_req_reg_255 == 1'd0));
end

assign ap_ready = 1'b0;

assign empty_n_1_fu_528_p1 = peek_real_written_bytes_resp_V_empty_n;

assign empty_n_2_fu_515_p1 = peek_write_finished_resp_V_empty_n;

assign empty_n_3_fu_502_p1 = peek_virt_written_bytes_resp_V_empty_n;

assign empty_n_4_fu_489_p1 = dbg_peek_resp_V_empty_n;

assign inflight_req_state_cast_fu_423_p1 = inflight_req_state_fu_415_p3;

assign inflight_req_state_fu_415_p3 = ((tmp_5_fu_409_p2[0:0] === 1'b1) ? sel_tmp7_fu_401_p3 : sel_tmp3_fu_358_p3);

assign peek_real_written_bytes_req_V_din = ap_reg_pp0_iter1_tmp_15_reg_558;

assign peek_virt_written_bytes_req_V_din = ap_reg_pp0_iter1_tmp_15_reg_558;

assign peek_write_finished_req_V_din = ap_reg_pp0_iter1_tmp_15_reg_558;

assign sel_tmp1_fu_346_p3 = ((empty_n_reg_551[0:0] === 1'b1) ? state_fu_338_p3 : 3'd0);

assign sel_tmp2_fu_353_p2 = (tmp_4_fu_318_p2 & empty_n_reg_551);

assign sel_tmp3_fu_358_p3 = ((sel_tmp2_fu_353_p2[0:0] === 1'b1) ? 3'd2 : sel_tmp1_fu_346_p3);

assign sel_tmp4_fu_366_p2 = (tmp_4_fu_318_p2 ^ 1'd1);

assign sel_tmp5_fu_372_p2 = (sel_tmp4_fu_366_p2 & empty_n_reg_551);

assign sel_tmp6_fu_377_p2 = (tmp_9_fu_323_p2 & sel_tmp5_fu_372_p2);

assign sel_tmp7_fu_401_p3 = ((sel_tmp8_fu_395_p2[0:0] === 1'b1) ? 3'd4 : 3'd3);

assign sel_tmp8_fu_395_p2 = (tmp2_fu_389_p2 & sel_tmp5_fu_372_p2);

assign sel_tmp_fu_383_p2 = (tmp_9_fu_323_p2 ^ 1'd1);

assign state_fu_338_p3 = ((tmp_2_fu_333_p2[0:0] === 1'b1) ? 3'd5 : 3'd1);

assign tmp2_fu_389_p2 = (tmp_1_fu_328_p2 & sel_tmp_fu_383_p2);

assign tmp_10_fu_433_p2 = ((inflight_req_state_fu_415_p3 == 3'd1) ? 1'b1 : 1'b0);

assign tmp_12_fu_439_p2 = ((inflight_req_state_fu_415_p3 == 3'd2) ? 1'b1 : 1'b0);

assign tmp_14_fu_445_p2 = ((inflight_req_state_fu_415_p3 == 3'd3) ? 1'b1 : 1'b0);

assign tmp_17_fu_451_p2 = ((inflight_req_state_fu_415_p3 == 3'd4) ? 1'b1 : 1'b0);

assign tmp_1_fu_328_p2 = ((tmp_15_reg_558 == 32'd84) ? 1'b1 : 1'b0);

assign tmp_2_fu_333_p2 = ((tmp_15_reg_558 == 32'd88) ? 1'b1 : 1'b0);

assign tmp_3_fu_471_p2 = ((inflight_req_state_s_fu_192 == 8'd3) ? 1'b1 : 1'b0);

assign tmp_4_fu_318_p2 = ((tmp_15_reg_558 == 32'd76) ? 1'b1 : 1'b0);

assign tmp_5_fu_409_p2 = (sel_tmp8_fu_395_p2 | sel_tmp6_fu_377_p2);

assign tmp_7_fu_427_p2 = ((inflight_req_state_fu_415_p3 == 3'd0) ? 1'b1 : 1'b0);

assign tmp_8_fu_477_p2 = ((inflight_req_state_s_fu_192 == 8'd4) ? 1'b1 : 1'b0);

assign tmp_9_fu_323_p2 = ((tmp_15_reg_558 == 32'd80) ? 1'b1 : 1'b0);

assign tmp_fu_465_p2 = ((inflight_req_state_s_fu_192 == 8'd2) ? 1'b1 : 1'b0);

assign tmp_s_fu_483_p2 = ((inflight_req_state_s_fu_192 == 8'd5) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    inflight_req_state_s_fu_192[7:3] <= 5'b00000;
end

endmodule //peek_handler
