// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.op
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pipe0_dram_dispatcher,hls_ip_2017_4_op,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.609000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=814,HLS_SYN_LUT=1647}" *)

module pipe0_dram_dispatcher (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
ap_continue,
        ap_idle,
        ap_ready,
        after_delay_unified_dram_read_req_V_num_dout,
        after_delay_unified_dram_read_req_V_num_empty_n,
        after_delay_unified_dram_read_req_V_num_read,
        after_delay_unified_dram_read_req_V_addr_dout,
        after_delay_unified_dram_read_req_V_addr_empty_n,
        after_delay_unified_dram_read_req_V_addr_read,
        after_throttle_unified_dram_write_req_apply_V_num_dout,
        after_throttle_unified_dram_write_req_apply_V_num_empty_n,
        after_throttle_unified_dram_write_req_apply_V_num_read,
        after_throttle_unified_dram_write_req_apply_V_addr_dout,
        after_throttle_unified_dram_write_req_apply_V_addr_empty_n,
        after_throttle_unified_dram_write_req_apply_V_addr_read,
        dramA_read_req_V_num_din,
        dramA_read_req_V_num_full_n,
        dramA_read_req_V_num_write,
        dramA_read_req_V_addr_din,
        dramA_read_req_V_addr_full_n,
        dramA_read_req_V_addr_write,
        dramA_write_req_apply_V_num_din,
        dramA_write_req_apply_V_num_full_n,
        dramA_write_req_apply_V_num_write,
        dramA_write_req_apply_V_addr_din,
        dramA_write_req_apply_V_addr_full_n,
        dramA_write_req_apply_V_addr_write,
        dramB_read_req_V_num_din,
        dramB_read_req_V_num_full_n,
        dramB_read_req_V_num_write,
        dramB_read_req_V_addr_din,
        dramB_read_req_V_addr_full_n,
        dramB_read_req_V_addr_write,
        dramB_write_req_apply_V_num_din,
        dramB_write_req_apply_V_num_full_n,
        dramB_write_req_apply_V_num_write,
        dramB_write_req_apply_V_addr_din,
        dramB_write_req_apply_V_addr_full_n,
        dramB_write_req_apply_V_addr_write,
        unified_dram_dispatcher_write_context_V_bank_id_din,
        unified_dram_dispatcher_write_context_V_bank_id_full_n,
        unified_dram_dispatcher_write_context_V_bank_id_write,
        unified_dram_dispatcher_write_context_V_end_bank_id_din,
        unified_dram_dispatcher_write_context_V_end_bank_id_full_n,
        unified_dram_dispatcher_write_context_V_end_bank_id_write,
        unified_dram_dispatcher_write_context_V_before_boundry_num_din,
        unified_dram_dispatcher_write_context_V_before_boundry_num_full_n,
        unified_dram_dispatcher_write_context_V_before_boundry_num_write,
        unified_dram_dispatcher_write_context_V_cmd_num_din,
        unified_dram_dispatcher_write_context_V_cmd_num_full_n,
        unified_dram_dispatcher_write_context_V_cmd_num_write,
        unified_dram_dispatcher_read_context_V_bank_id_din,
        unified_dram_dispatcher_read_context_V_bank_id_full_n,
        unified_dram_dispatcher_read_context_V_bank_id_write,
        unified_dram_dispatcher_read_context_V_end_bank_id_din,
        unified_dram_dispatcher_read_context_V_end_bank_id_full_n,
        unified_dram_dispatcher_read_context_V_end_bank_id_write,
        unified_dram_dispatcher_read_context_V_cmd_num_din,
        unified_dram_dispatcher_read_context_V_cmd_num_full_n,
        unified_dram_dispatcher_read_context_V_cmd_num_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output ap_ready; output ap_continue;
input  [7:0] after_delay_unified_dram_read_req_V_num_dout;
input   after_delay_unified_dram_read_req_V_num_empty_n;
output   after_delay_unified_dram_read_req_V_num_read;
input  [63:0] after_delay_unified_dram_read_req_V_addr_dout;
input   after_delay_unified_dram_read_req_V_addr_empty_n;
output   after_delay_unified_dram_read_req_V_addr_read;
input  [7:0] after_throttle_unified_dram_write_req_apply_V_num_dout;
input   after_throttle_unified_dram_write_req_apply_V_num_empty_n;
output   after_throttle_unified_dram_write_req_apply_V_num_read;
input  [63:0] after_throttle_unified_dram_write_req_apply_V_addr_dout;
input   after_throttle_unified_dram_write_req_apply_V_addr_empty_n;
output   after_throttle_unified_dram_write_req_apply_V_addr_read;
output  [7:0] dramA_read_req_V_num_din;
input   dramA_read_req_V_num_full_n;
output   dramA_read_req_V_num_write;
output  [63:0] dramA_read_req_V_addr_din;
input   dramA_read_req_V_addr_full_n;
output   dramA_read_req_V_addr_write;
output  [7:0] dramA_write_req_apply_V_num_din;
input   dramA_write_req_apply_V_num_full_n;
output   dramA_write_req_apply_V_num_write;
output  [63:0] dramA_write_req_apply_V_addr_din;
input   dramA_write_req_apply_V_addr_full_n;
output   dramA_write_req_apply_V_addr_write;
output  [7:0] dramB_read_req_V_num_din;
input   dramB_read_req_V_num_full_n;
output   dramB_read_req_V_num_write;
output  [63:0] dramB_read_req_V_addr_din;
input   dramB_read_req_V_addr_full_n;
output   dramB_read_req_V_addr_write;
output  [7:0] dramB_write_req_apply_V_num_din;
input   dramB_write_req_apply_V_num_full_n;
output   dramB_write_req_apply_V_num_write;
output  [63:0] dramB_write_req_apply_V_addr_din;
input   dramB_write_req_apply_V_addr_full_n;
output   dramB_write_req_apply_V_addr_write;
output  [7:0] unified_dram_dispatcher_write_context_V_bank_id_din;
input   unified_dram_dispatcher_write_context_V_bank_id_full_n;
output   unified_dram_dispatcher_write_context_V_bank_id_write;
output  [7:0] unified_dram_dispatcher_write_context_V_end_bank_id_din;
input   unified_dram_dispatcher_write_context_V_end_bank_id_full_n;
output   unified_dram_dispatcher_write_context_V_end_bank_id_write;
output  [31:0] unified_dram_dispatcher_write_context_V_before_boundry_num_din;
input   unified_dram_dispatcher_write_context_V_before_boundry_num_full_n;
output   unified_dram_dispatcher_write_context_V_before_boundry_num_write;
output  [31:0] unified_dram_dispatcher_write_context_V_cmd_num_din;
input   unified_dram_dispatcher_write_context_V_cmd_num_full_n;
output   unified_dram_dispatcher_write_context_V_cmd_num_write;
output  [7:0] unified_dram_dispatcher_read_context_V_bank_id_din;
input   unified_dram_dispatcher_read_context_V_bank_id_full_n;
output   unified_dram_dispatcher_read_context_V_bank_id_write;
output  [7:0] unified_dram_dispatcher_read_context_V_end_bank_id_din;
input   unified_dram_dispatcher_read_context_V_end_bank_id_full_n;
output   unified_dram_dispatcher_read_context_V_end_bank_id_write;
output  [31:0] unified_dram_dispatcher_read_context_V_cmd_num_din;
input   unified_dram_dispatcher_read_context_V_cmd_num_full_n;
output   unified_dram_dispatcher_read_context_V_cmd_num_write;

reg ap_idle;
reg[7:0] unified_dram_dispatcher_write_context_V_end_bank_id_din;
reg[31:0] unified_dram_dispatcher_write_context_V_before_boundry_num_din;
reg[7:0] unified_dram_dispatcher_read_context_V_end_bank_id_din;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    dramA_read_req_V_num_blk_n;
reg    ap_enable_reg_pp0_iter3;
wire    ap_block_pp0_stage0;
reg   [0:0] brmerge_reg_1507;
reg    dramA_read_req_V_addr_blk_n;
reg    dramA_write_req_apply_V_num_blk_n;
reg   [0:0] brmerge2_reg_1515;
reg    dramA_write_req_apply_V_addr_blk_n;
reg    dramB_read_req_V_num_blk_n;
reg   [0:0] brmerge1_reg_1511;
reg    dramB_read_req_V_addr_blk_n;
reg    dramB_write_req_apply_V_num_blk_n;
reg   [0:0] brmerge3_reg_1519;
reg    dramB_write_req_apply_V_addr_blk_n;
reg    unified_dram_dispatcher_write_context_V_bank_id_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] empty_n_5_reg_1385;
reg   [0:0] ap_reg_pp0_iter1_empty_n_5_reg_1385;
reg   [0:0] tmp_25tmp_reg_1498;
reg    unified_dram_dispatcher_write_context_V_end_bank_id_blk_n;
reg    unified_dram_dispatcher_write_context_V_before_boundry_num_blk_n;
reg    unified_dram_dispatcher_write_context_V_cmd_num_blk_n;
reg    unified_dram_dispatcher_read_context_V_bank_id_blk_n;
reg   [0:0] empty_n_4_reg_1359;
reg   [0:0] ap_reg_pp0_iter1_empty_n_4_reg_1359;
reg   [0:0] tmp_10tmp_reg_1450;
reg    unified_dram_dispatcher_read_context_V_end_bank_id_blk_n;
reg    unified_dram_dispatcher_read_context_V_cmd_num_blk_n;
wire   [0:0] empty_n_4_fu_511_p1;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    unified_dram_dispatcher_read_context_V_bank_id1_status;
reg    ap_predicate_op132_write_state4;
reg    ap_predicate_op147_write_state4;
wire    unified_dram_dispatcher_write_context_V_bank_id1_status;
reg    ap_predicate_op180_write_state4;
reg    ap_predicate_op196_write_state4;
reg    ap_block_state4_pp0_stage0_iter2;
wire    dramA_read_req_V_num1_status;
wire    dramB_read_req_V_num1_status;
wire    dramA_write_req_apply_V_num1_status;
wire    dramB_write_req_apply_V_num1_status;
reg    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] tmp_num_7_reg_1364;
reg   [7:0] ap_reg_pp0_iter1_tmp_num_7_reg_1364;
reg   [63:0] tmp_addr_7_reg_1372;
wire   [11:0] tmp_6_fu_523_p1;
reg   [11:0] tmp_6_reg_1379;
reg   [11:0] ap_reg_pp0_iter1_tmp_6_reg_1379;
wire   [0:0] empty_n_5_fu_527_p1;
reg   [7:0] tmp_num_8_reg_1390;
reg   [7:0] ap_reg_pp0_iter1_tmp_num_8_reg_1390;
reg   [63:0] tmp_addr_8_reg_1398;
wire   [11:0] tmp_14_fu_539_p1;
reg   [11:0] tmp_14_reg_1405;
reg   [11:0] ap_reg_pp0_iter1_tmp_14_reg_1405;
wire   [0:0] read_bank_id_fu_543_p3;
reg   [0:0] read_bank_id_reg_1411;
wire   [7:0] tmp_bank_id_10_fu_550_p1;
reg   [7:0] tmp_bank_id_10_reg_1421;
reg   [50:0] tmp_1_reg_1427;
wire   [0:0] read_end_bank_id_fu_593_p3;
reg   [0:0] read_end_bank_id_reg_1432;
wire   [7:0] tmp_end_bank_id_1_fu_601_p1;
reg   [7:0] tmp_end_bank_id_1_reg_1440;
reg   [22:0] tmp_2_reg_1445;
wire   [0:0] tmp_10tmp_fu_615_p2;
reg   [5:0] ddr_read_req_0_num_1_reg_1454;
wire   [0:0] write_bank_id_fu_656_p3;
reg   [0:0] write_bank_id_reg_1459;
wire   [7:0] tmp_bank_id_11_fu_663_p1;
reg   [7:0] tmp_bank_id_11_reg_1469;
reg   [50:0] tmp_4_reg_1475;
wire   [0:0] write_end_bank_id_fu_706_p3;
reg   [0:0] write_end_bank_id_reg_1480;
wire   [7:0] tmp_end_bank_id_4_fu_714_p1;
reg   [7:0] tmp_end_bank_id_4_reg_1488;
reg   [22:0] tmp_9_reg_1493;
wire   [0:0] tmp_25tmp_fu_728_p2;
reg   [5:0] ddr_write_apply_0_num_1_reg_1502;
wire   [0:0] brmerge_fu_970_p2;
wire   [0:0] brmerge1_fu_994_p2;
wire   [0:0] brmerge2_fu_1207_p2;
wire   [0:0] brmerge3_fu_1231_p2;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] ap_phi_reg_pp0_iter0_has_read_req1_reg_483;
reg   [0:0] ap_phi_reg_pp0_iter1_has_read_req1_reg_483;
reg   [0:0] ap_phi_reg_pp0_iter2_has_read_req1_reg_483;
wire   [0:0] ap_phi_reg_pp0_iter0_has_write_req1_reg_497;
reg   [0:0] ap_phi_reg_pp0_iter1_has_write_req1_reg_497;
reg   [0:0] ap_phi_reg_pp0_iter2_has_write_req1_reg_497;
reg    after_delay_unified_dram_read_req_V_num0_update;
wire   [0:0] empty_n_nbread_fu_398_p3_0;
reg    after_throttle_unified_dram_write_req_apply_V_num0_update;
wire   [0:0] empty_n_1_nbread_fu_406_p3_0;
reg    unified_dram_dispatcher_read_context_V_bank_id1_update;
reg    ap_block_pp0_stage0_01001;
reg    unified_dram_dispatcher_write_context_V_bank_id1_update;
wire   [31:0] before_boundry_len_fu_1019_p1;
wire   [31:0] tmp_before_boundry_num_fu_1152_p1;
reg    dramA_read_req_V_num1_update;
reg    dramB_read_req_V_num1_update;
reg    dramA_write_req_apply_V_num1_update;
reg    dramB_write_req_apply_V_num1_update;
reg   [7:0] tmp_bank_id_fu_350;
reg   [7:0] tmp_bank_id_1_fu_354;
reg   [7:0] tmp_bank_id_2_fu_358;
reg   [7:0] tmp_bank_id_3_fu_362;
reg   [7:0] tmp_num_fu_366;
wire   [7:0] ddr_read_req_1_num_2_fu_829_p3;
wire   [7:0] ddr_read_req_1_num_7_fu_913_p3;
reg   [7:0] tmp_num_1_fu_370;
wire   [7:0] ddr_read_req_1_num_1_fu_823_p3;
wire   [7:0] ddr_read_req_1_num_6_fu_906_p3;
reg   [63:0] tmp_addr_fu_374;
wire   [63:0] ddr_read_req_1_addr_2_fu_810_p3;
wire   [63:0] ddr_read_req_1_addr_5_fu_896_p3;
reg   [63:0] tmp_addr_1_fu_378;
wire   [63:0] ddr_read_req_1_addr_1_fu_803_p3;
wire   [63:0] ddr_read_req_1_addr_4_fu_889_p3;
reg   [7:0] tmp_num_2_fu_382;
wire   [7:0] ddr_write_apply_1_num_2_fu_1061_p3;
wire   [7:0] ddr_write_apply_1_num_7_fu_1145_p3;
reg   [7:0] tmp_num_3_fu_386;
wire   [7:0] ddr_write_apply_1_num_1_fu_1055_p3;
wire   [7:0] ddr_write_apply_1_num_6_fu_1138_p3;
reg   [63:0] tmp_addr_2_fu_390;
wire   [63:0] ddr_write_apply_1_addr_2_fu_1042_p3;
wire   [63:0] ddr_write_apply_1_addr_5_fu_1128_p3;
reg   [63:0] tmp_addr_3_fu_394;
wire   [63:0] ddr_write_apply_1_addr_1_fu_1035_p3;
wire   [63:0] ddr_write_apply_1_addr_4_fu_1121_p3;
wire   [13:0] tmp_7_fu_563_p3;
wire   [14:0] tmp_9_cast_fu_573_p1;
wire   [14:0] tmp1_fu_577_p2;
wire   [35:0] tmp_12_fu_570_p1;
wire  signed [35:0] tmp1_cast_fu_583_p1;
wire   [35:0] end_addr_V_fu_587_p2;
wire   [36:0] lhs_V_cast_fu_631_p1;
wire   [36:0] r_V_fu_635_p2;
wire   [13:0] tmp_5_fu_676_p3;
wire   [14:0] tmp_22_cast_fu_686_p1;
wire   [14:0] tmp2_fu_690_p2;
wire   [35:0] tmp_16_fu_683_p1;
wire  signed [35:0] tmp2_cast_fu_696_p1;
wire   [35:0] end_addr_V_1_fu_700_p2;
wire   [36:0] lhs_V_2_cast_fu_744_p1;
wire   [36:0] r_V_1_fu_748_p2;
wire   [62:0] dram_start_addr_fu_778_p3;
wire   [34:0] end_dram_start_addr_fu_792_p3;
wire   [63:0] dram_start_addr_cast_fu_784_p1;
wire   [12:0] tmp_5_cast_fu_775_p1;
wire   [12:0] tmp_s_fu_855_p2;
wire   [6:0] tmp_3_fu_861_p4;
wire   [7:0] ddr_read_req_0_num_fu_871_p1;
wire   [63:0] end_dram_start_addr_cast_fu_799_p1;
wire   [7:0] ddr_read_req_0_num_3_cast_fu_903_p1;
wire   [7:0] ddr_read_req_1_num_3_fu_875_p3;
wire   [7:0] ddr_read_req_1_num_4_fu_882_p3;
wire   [0:0] notrhs_fu_952_p2;
wire   [0:0] notlhs_fu_946_p2;
wire   [0:0] or_cond_not_fu_958_p2;
wire   [0:0] has_read_req_0_not_fu_964_p2;
wire   [0:0] notrhs1_fu_982_p2;
wire   [0:0] notlhs1_fu_976_p2;
wire   [0:0] or_cond275_not_fu_988_p2;
wire   [62:0] dram_start_addr_1_fu_1009_p3;
wire   [34:0] end_dram_start_addr_1_fu_1024_p3;
wire   [63:0] dram_start_addr_1_cast_fu_1015_p1;
wire   [12:0] tmp_19_cast_fu_1006_p1;
wire   [12:0] tmp_8_fu_1087_p2;
wire   [6:0] tmp_10_fu_1093_p4;
wire   [7:0] ddr_write_apply_0_num_fu_1103_p1;
wire   [63:0] end_dram_start_addr_1_cast_fu_1031_p1;
wire   [7:0] ddr_write_apply_0_num_3_cast_fu_1135_p1;
wire   [7:0] ddr_write_apply_1_num_3_fu_1107_p3;
wire   [7:0] ddr_write_apply_1_num_4_fu_1114_p3;
wire   [0:0] notrhs2_fu_1189_p2;
wire   [0:0] notlhs2_fu_1183_p2;
wire   [0:0] or_cond278_not_fu_1195_p2;
wire   [0:0] has_write_req_0_not_fu_1201_p2;
wire   [0:0] notrhs3_fu_1219_p2;
wire   [0:0] notlhs3_fu_1213_p2;
wire   [0:0] or_cond280_not_fu_1225_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_298;
reg    ap_condition_862;
reg    ap_condition_391;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_298)) begin
        if ((empty_n_4_fu_511_p1 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_has_read_req1_reg_483 <= empty_n_nbread_fu_398_p3_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_has_read_req1_reg_483 <= ap_phi_reg_pp0_iter0_has_read_req1_reg_483;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_298)) begin
        if ((empty_n_5_fu_527_p1 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_has_write_req1_reg_497 <= empty_n_1_nbread_fu_406_p3_0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_has_write_req1_reg_497 <= ap_phi_reg_pp0_iter0_has_write_req1_reg_497;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (empty_n_4_reg_1359 == 1'd1) & (tmp_10tmp_fu_615_p2 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_10tmp_fu_615_p2 == 1'd1) & (empty_n_4_reg_1359 == 1'd1)))) begin
        ap_phi_reg_pp0_iter2_has_read_req1_reg_483 <= 1'd1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_has_read_req1_reg_483 <= ap_phi_reg_pp0_iter1_has_read_req1_reg_483;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (empty_n_5_reg_1385 == 1'd1) & (tmp_25tmp_fu_728_p2 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_25tmp_fu_728_p2 == 1'd1) & (empty_n_5_reg_1385 == 1'd1)))) begin
        ap_phi_reg_pp0_iter2_has_write_req1_reg_497 <= 1'd1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_has_write_req1_reg_497 <= ap_phi_reg_pp0_iter1_has_write_req1_reg_497;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op147_write_state4 == 1'b1)) begin
            tmp_addr_1_fu_378 <= ddr_read_req_1_addr_4_fu_889_p3;
        end else if ((ap_predicate_op132_write_state4 == 1'b1)) begin
            tmp_addr_1_fu_378 <= ddr_read_req_1_addr_1_fu_803_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op196_write_state4 == 1'b1)) begin
            tmp_addr_2_fu_390 <= ddr_write_apply_1_addr_5_fu_1128_p3;
        end else if ((ap_predicate_op180_write_state4 == 1'b1)) begin
            tmp_addr_2_fu_390 <= ddr_write_apply_1_addr_2_fu_1042_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op196_write_state4 == 1'b1)) begin
            tmp_addr_3_fu_394 <= ddr_write_apply_1_addr_4_fu_1121_p3;
        end else if ((ap_predicate_op180_write_state4 == 1'b1)) begin
            tmp_addr_3_fu_394 <= ddr_write_apply_1_addr_1_fu_1035_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op147_write_state4 == 1'b1)) begin
            tmp_addr_fu_374 <= ddr_read_req_1_addr_5_fu_896_p3;
        end else if ((ap_predicate_op132_write_state4 == 1'b1)) begin
            tmp_addr_fu_374 <= ddr_read_req_1_addr_2_fu_810_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_862)) begin
        if ((tmp_10tmp_fu_615_p2 == 1'd1)) begin
                        tmp_bank_id_2_fu_358[0] <= tmp_end_bank_id_1_fu_601_p1[0];
        end else if ((tmp_10tmp_fu_615_p2 == 1'd0)) begin
                        tmp_bank_id_2_fu_358[0] <= tmp_bank_id_10_fu_550_p1[0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_391)) begin
        if ((tmp_25tmp_fu_728_p2 == 1'd1)) begin
                        tmp_bank_id_fu_350[0] <= tmp_end_bank_id_4_fu_714_p1[0];
        end else if ((tmp_25tmp_fu_728_p2 == 1'd0)) begin
                        tmp_bank_id_fu_350[0] <= tmp_bank_id_11_fu_663_p1[0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op147_write_state4 == 1'b1)) begin
            tmp_num_1_fu_370 <= ddr_read_req_1_num_6_fu_906_p3;
        end else if ((ap_predicate_op132_write_state4 == 1'b1)) begin
            tmp_num_1_fu_370 <= ddr_read_req_1_num_1_fu_823_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op196_write_state4 == 1'b1)) begin
            tmp_num_2_fu_382 <= ddr_write_apply_1_num_7_fu_1145_p3;
        end else if ((ap_predicate_op180_write_state4 == 1'b1)) begin
            tmp_num_2_fu_382 <= ddr_write_apply_1_num_2_fu_1061_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op196_write_state4 == 1'b1)) begin
            tmp_num_3_fu_386 <= ddr_write_apply_1_num_6_fu_1138_p3;
        end else if ((ap_predicate_op180_write_state4 == 1'b1)) begin
            tmp_num_3_fu_386 <= ddr_write_apply_1_num_1_fu_1055_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op147_write_state4 == 1'b1)) begin
            tmp_num_fu_366 <= ddr_read_req_1_num_7_fu_913_p3;
        end else if ((ap_predicate_op132_write_state4 == 1'b1)) begin
            tmp_num_fu_366 <= ddr_read_req_1_num_2_fu_829_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_reg_pp0_iter1_empty_n_4_reg_1359 <= empty_n_4_reg_1359;
        ap_reg_pp0_iter1_empty_n_5_reg_1385 <= empty_n_5_reg_1385;
        ap_reg_pp0_iter1_tmp_14_reg_1405 <= tmp_14_reg_1405;
        ap_reg_pp0_iter1_tmp_6_reg_1379 <= tmp_6_reg_1379;
        ap_reg_pp0_iter1_tmp_num_7_reg_1364 <= tmp_num_7_reg_1364;
        ap_reg_pp0_iter1_tmp_num_8_reg_1390 <= tmp_num_8_reg_1390;
        empty_n_4_reg_1359 <= empty_n_nbread_fu_398_p3_0;
        empty_n_5_reg_1385 <= empty_n_1_nbread_fu_406_p3_0;
        read_bank_id_reg_1411 <= tmp_addr_7_reg_1372[32'd12];
        read_end_bank_id_reg_1432 <= end_addr_V_fu_587_p2[32'd12];
        tmp_10tmp_reg_1450 <= tmp_10tmp_fu_615_p2;
        tmp_14_reg_1405 <= tmp_14_fu_539_p1;
        tmp_1_reg_1427 <= {{tmp_addr_7_reg_1372[63:13]}};
        tmp_2_reg_1445 <= {{end_addr_V_fu_587_p2[35:13]}};
        tmp_6_reg_1379 <= tmp_6_fu_523_p1;
        tmp_addr_7_reg_1372 <= after_delay_unified_dram_read_req_V_addr_dout;
        tmp_addr_8_reg_1398 <= after_throttle_unified_dram_write_req_apply_V_addr_dout;
        tmp_bank_id_10_reg_1421[0] <= tmp_bank_id_10_fu_550_p1[0];
        tmp_end_bank_id_1_reg_1440[0] <= tmp_end_bank_id_1_fu_601_p1[0];
        tmp_num_7_reg_1364 <= after_delay_unified_dram_read_req_V_num_dout;
        tmp_num_8_reg_1390 <= after_throttle_unified_dram_write_req_apply_V_num_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        brmerge1_reg_1511 <= brmerge1_fu_994_p2;
        brmerge2_reg_1515 <= brmerge2_fu_1207_p2;
        brmerge3_reg_1519 <= brmerge3_fu_1231_p2;
        brmerge_reg_1507 <= brmerge_fu_970_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_10tmp_fu_615_p2 == 1'd1) & (empty_n_4_reg_1359 == 1'd1))) begin
        ddr_read_req_0_num_1_reg_1454 <= {{r_V_fu_635_p2[11:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_25tmp_fu_728_p2 == 1'd1) & (empty_n_5_reg_1385 == 1'd1))) begin
        ddr_write_apply_0_num_1_reg_1502 <= {{r_V_1_fu_748_p2[11:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (empty_n_5_reg_1385 == 1'd1))) begin
        tmp_25tmp_reg_1498 <= tmp_25tmp_fu_728_p2;
        tmp_4_reg_1475 <= {{tmp_addr_8_reg_1398[63:13]}};
        tmp_9_reg_1493 <= {{end_addr_V_1_fu_700_p2[35:13]}};
        tmp_bank_id_11_reg_1469[0] <= tmp_bank_id_11_fu_663_p1[0];
        tmp_end_bank_id_4_reg_1488[0] <= tmp_end_bank_id_4_fu_714_p1[0];
        write_bank_id_reg_1459 <= tmp_addr_8_reg_1398[32'd12];
        write_end_bank_id_reg_1480 <= end_addr_V_1_fu_700_p2[32'd12];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (empty_n_5_reg_1385 == 1'd1))) begin
        tmp_bank_id_1_fu_354[0] <= tmp_bank_id_11_fu_663_p1[0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_bank_id_3_fu_362[0] <= tmp_bank_id_10_fu_550_p1[0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & ((after_delay_unified_dram_read_req_V_num_empty_n & after_delay_unified_dram_read_req_V_addr_empty_n) == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        after_delay_unified_dram_read_req_V_num0_update = 1'b1;
    end else begin
        after_delay_unified_dram_read_req_V_num0_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & ((after_throttle_unified_dram_write_req_apply_V_num_empty_n & after_throttle_unified_dram_write_req_apply_V_addr_empty_n) == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        after_throttle_unified_dram_write_req_apply_V_num0_update = 1'b1;
    end else begin
        after_throttle_unified_dram_write_req_apply_V_num0_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (brmerge_reg_1507 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        dramA_read_req_V_addr_blk_n = dramA_read_req_V_addr_full_n;
    end else begin
        dramA_read_req_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (brmerge_reg_1507 == 1'd0))) begin
        dramA_read_req_V_num1_update = 1'b1;
    end else begin
        dramA_read_req_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (brmerge_reg_1507 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        dramA_read_req_V_num_blk_n = dramA_read_req_V_num_full_n;
    end else begin
        dramA_read_req_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (brmerge2_reg_1515 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        dramA_write_req_apply_V_addr_blk_n = dramA_write_req_apply_V_addr_full_n;
    end else begin
        dramA_write_req_apply_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (brmerge2_reg_1515 == 1'd0))) begin
        dramA_write_req_apply_V_num1_update = 1'b1;
    end else begin
        dramA_write_req_apply_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (brmerge2_reg_1515 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        dramA_write_req_apply_V_num_blk_n = dramA_write_req_apply_V_num_full_n;
    end else begin
        dramA_write_req_apply_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (brmerge1_reg_1511 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        dramB_read_req_V_addr_blk_n = dramB_read_req_V_addr_full_n;
    end else begin
        dramB_read_req_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (brmerge1_reg_1511 == 1'd0))) begin
        dramB_read_req_V_num1_update = 1'b1;
    end else begin
        dramB_read_req_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (brmerge1_reg_1511 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        dramB_read_req_V_num_blk_n = dramB_read_req_V_num_full_n;
    end else begin
        dramB_read_req_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (brmerge3_reg_1519 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        dramB_write_req_apply_V_addr_blk_n = dramB_write_req_apply_V_addr_full_n;
    end else begin
        dramB_write_req_apply_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (brmerge3_reg_1519 == 1'd0))) begin
        dramB_write_req_apply_V_num1_update = 1'b1;
    end else begin
        dramB_write_req_apply_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (brmerge3_reg_1519 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        dramB_write_req_apply_V_num_blk_n = dramB_write_req_apply_V_num_full_n;
    end else begin
        dramB_write_req_apply_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op147_write_state4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op132_write_state4 == 1'b1)))) begin
        unified_dram_dispatcher_read_context_V_bank_id1_update = 1'b1;
    end else begin
        unified_dram_dispatcher_read_context_V_bank_id1_update = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_10tmp_reg_1450 == 1'd1) & (ap_reg_pp0_iter1_empty_n_4_reg_1359 == 1'd1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_empty_n_4_reg_1359 == 1'd1) & (tmp_10tmp_reg_1450 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        unified_dram_dispatcher_read_context_V_bank_id_blk_n = unified_dram_dispatcher_read_context_V_bank_id_full_n;
    end else begin
        unified_dram_dispatcher_read_context_V_bank_id_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_10tmp_reg_1450 == 1'd1) & (ap_reg_pp0_iter1_empty_n_4_reg_1359 == 1'd1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_empty_n_4_reg_1359 == 1'd1) & (tmp_10tmp_reg_1450 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        unified_dram_dispatcher_read_context_V_cmd_num_blk_n = unified_dram_dispatcher_read_context_V_cmd_num_full_n;
    end else begin
        unified_dram_dispatcher_read_context_V_cmd_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_10tmp_reg_1450 == 1'd1) & (ap_reg_pp0_iter1_empty_n_4_reg_1359 == 1'd1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_empty_n_4_reg_1359 == 1'd1) & (tmp_10tmp_reg_1450 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        unified_dram_dispatcher_read_context_V_end_bank_id_blk_n = unified_dram_dispatcher_read_context_V_end_bank_id_full_n;
    end else begin
        unified_dram_dispatcher_read_context_V_end_bank_id_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op147_write_state4 == 1'b1)) begin
            unified_dram_dispatcher_read_context_V_end_bank_id_din = tmp_end_bank_id_1_reg_1440;
        end else if ((ap_predicate_op132_write_state4 == 1'b1)) begin
            unified_dram_dispatcher_read_context_V_end_bank_id_din = tmp_bank_id_10_reg_1421;
        end else begin
            unified_dram_dispatcher_read_context_V_end_bank_id_din = 'bx;
        end
    end else begin
        unified_dram_dispatcher_read_context_V_end_bank_id_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op196_write_state4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op180_write_state4 == 1'b1)))) begin
        unified_dram_dispatcher_write_context_V_bank_id1_update = 1'b1;
    end else begin
        unified_dram_dispatcher_write_context_V_bank_id1_update = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_25tmp_reg_1498 == 1'd1) & (ap_reg_pp0_iter1_empty_n_5_reg_1385 == 1'd1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_empty_n_5_reg_1385 == 1'd1) & (tmp_25tmp_reg_1498 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        unified_dram_dispatcher_write_context_V_bank_id_blk_n = unified_dram_dispatcher_write_context_V_bank_id_full_n;
    end else begin
        unified_dram_dispatcher_write_context_V_bank_id_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_25tmp_reg_1498 == 1'd1) & (ap_reg_pp0_iter1_empty_n_5_reg_1385 == 1'd1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_empty_n_5_reg_1385 == 1'd1) & (tmp_25tmp_reg_1498 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        unified_dram_dispatcher_write_context_V_before_boundry_num_blk_n = unified_dram_dispatcher_write_context_V_before_boundry_num_full_n;
    end else begin
        unified_dram_dispatcher_write_context_V_before_boundry_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op196_write_state4 == 1'b1)) begin
            unified_dram_dispatcher_write_context_V_before_boundry_num_din = tmp_before_boundry_num_fu_1152_p1;
        end else if ((ap_predicate_op180_write_state4 == 1'b1)) begin
            unified_dram_dispatcher_write_context_V_before_boundry_num_din = before_boundry_len_fu_1019_p1;
        end else begin
            unified_dram_dispatcher_write_context_V_before_boundry_num_din = 'bx;
        end
    end else begin
        unified_dram_dispatcher_write_context_V_before_boundry_num_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_25tmp_reg_1498 == 1'd1) & (ap_reg_pp0_iter1_empty_n_5_reg_1385 == 1'd1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_empty_n_5_reg_1385 == 1'd1) & (tmp_25tmp_reg_1498 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        unified_dram_dispatcher_write_context_V_cmd_num_blk_n = unified_dram_dispatcher_write_context_V_cmd_num_full_n;
    end else begin
        unified_dram_dispatcher_write_context_V_cmd_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_25tmp_reg_1498 == 1'd1) & (ap_reg_pp0_iter1_empty_n_5_reg_1385 == 1'd1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_empty_n_5_reg_1385 == 1'd1) & (tmp_25tmp_reg_1498 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        unified_dram_dispatcher_write_context_V_end_bank_id_blk_n = unified_dram_dispatcher_write_context_V_end_bank_id_full_n;
    end else begin
        unified_dram_dispatcher_write_context_V_end_bank_id_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op196_write_state4 == 1'b1)) begin
            unified_dram_dispatcher_write_context_V_end_bank_id_din = tmp_end_bank_id_4_reg_1488;
        end else if ((ap_predicate_op180_write_state4 == 1'b1)) begin
            unified_dram_dispatcher_write_context_V_end_bank_id_din = tmp_bank_id_11_reg_1469;
        end else begin
            unified_dram_dispatcher_write_context_V_end_bank_id_din = 'bx;
        end
    end else begin
        unified_dram_dispatcher_write_context_V_end_bank_id_din = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign after_delay_unified_dram_read_req_V_addr_read = after_delay_unified_dram_read_req_V_num0_update;

assign after_delay_unified_dram_read_req_V_num_read = after_delay_unified_dram_read_req_V_num0_update;

assign after_throttle_unified_dram_write_req_apply_V_addr_read = after_throttle_unified_dram_write_req_apply_V_num0_update;

assign after_throttle_unified_dram_write_req_apply_V_num_read = after_throttle_unified_dram_write_req_apply_V_num0_update;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((unified_dram_dispatcher_write_context_V_bank_id1_status == 1'b0) & (ap_predicate_op196_write_state4 == 1'b1)) | ((unified_dram_dispatcher_write_context_V_bank_id1_status == 1'b0) & (ap_predicate_op180_write_state4 == 1'b1)) | ((unified_dram_dispatcher_read_context_V_bank_id1_status == 1'b0) & (ap_predicate_op147_write_state4 == 1'b1)) | ((unified_dram_dispatcher_read_context_V_bank_id1_status == 1'b0) & (ap_predicate_op132_write_state4 == 1'b1)))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (((dramB_write_req_apply_V_num1_status == 1'b0) & (brmerge3_reg_1519 == 1'd0)) | ((dramB_read_req_V_num1_status == 1'b0) & (brmerge1_reg_1511 == 1'd0)) | ((dramA_write_req_apply_V_num1_status == 1'b0) & (brmerge2_reg_1515 == 1'd0)) | ((dramA_read_req_V_num1_status == 1'b0) & (brmerge_reg_1507 == 1'd0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((unified_dram_dispatcher_write_context_V_bank_id1_status == 1'b0) & (ap_predicate_op196_write_state4 == 1'b1)) | ((unified_dram_dispatcher_write_context_V_bank_id1_status == 1'b0) & (ap_predicate_op180_write_state4 == 1'b1)) | ((unified_dram_dispatcher_read_context_V_bank_id1_status == 1'b0) & (ap_predicate_op147_write_state4 == 1'b1)) | ((unified_dram_dispatcher_read_context_V_bank_id1_status == 1'b0) & (ap_predicate_op132_write_state4 == 1'b1)))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (((dramB_write_req_apply_V_num1_status == 1'b0) & (brmerge3_reg_1519 == 1'd0)) | ((dramB_read_req_V_num1_status == 1'b0) & (brmerge1_reg_1511 == 1'd0)) | ((dramA_write_req_apply_V_num1_status == 1'b0) & (brmerge2_reg_1515 == 1'd0)) | ((dramA_read_req_V_num1_status == 1'b0) & (brmerge_reg_1507 == 1'd0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((unified_dram_dispatcher_write_context_V_bank_id1_status == 1'b0) & (ap_predicate_op196_write_state4 == 1'b1)) | ((unified_dram_dispatcher_write_context_V_bank_id1_status == 1'b0) & (ap_predicate_op180_write_state4 == 1'b1)) | ((unified_dram_dispatcher_read_context_V_bank_id1_status == 1'b0) & (ap_predicate_op147_write_state4 == 1'b1)) | ((unified_dram_dispatcher_read_context_V_bank_id1_status == 1'b0) & (ap_predicate_op132_write_state4 == 1'b1)))) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (((dramB_write_req_apply_V_num1_status == 1'b0) & (brmerge3_reg_1519 == 1'd0)) | ((dramB_read_req_V_num1_status == 1'b0) & (brmerge1_reg_1511 == 1'd0)) | ((dramA_write_req_apply_V_num1_status == 1'b0) & (brmerge2_reg_1515 == 1'd0)) | ((dramA_read_req_V_num1_status == 1'b0) & (brmerge_reg_1507 == 1'd0)))));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = (((unified_dram_dispatcher_write_context_V_bank_id1_status == 1'b0) & (ap_predicate_op196_write_state4 == 1'b1)) | ((unified_dram_dispatcher_write_context_V_bank_id1_status == 1'b0) & (ap_predicate_op180_write_state4 == 1'b1)) | ((unified_dram_dispatcher_read_context_V_bank_id1_status == 1'b0) & (ap_predicate_op147_write_state4 == 1'b1)) | ((unified_dram_dispatcher_read_context_V_bank_id1_status == 1'b0) & (ap_predicate_op132_write_state4 == 1'b1)));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter3 = (((dramB_write_req_apply_V_num1_status == 1'b0) & (brmerge3_reg_1519 == 1'd0)) | ((dramB_read_req_V_num1_status == 1'b0) & (brmerge1_reg_1511 == 1'd0)) | ((dramA_write_req_apply_V_num1_status == 1'b0) & (brmerge2_reg_1515 == 1'd0)) | ((dramA_read_req_V_num1_status == 1'b0) & (brmerge_reg_1507 == 1'd0)));
end

always @ (*) begin
    ap_condition_298 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_391 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (empty_n_5_reg_1385 == 1'd1));
end

always @ (*) begin
    ap_condition_862 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (empty_n_4_reg_1359 == 1'd1));
end

assign ap_done = 1'b0;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_has_read_req1_reg_483 = 'bx;

assign ap_phi_reg_pp0_iter0_has_write_req1_reg_497 = 'bx;

always @ (*) begin
    ap_predicate_op132_write_state4 = ((ap_reg_pp0_iter1_empty_n_4_reg_1359 == 1'd1) & (tmp_10tmp_reg_1450 == 1'd0));
end

always @ (*) begin
    ap_predicate_op147_write_state4 = ((tmp_10tmp_reg_1450 == 1'd1) & (ap_reg_pp0_iter1_empty_n_4_reg_1359 == 1'd1));
end

always @ (*) begin
    ap_predicate_op180_write_state4 = ((ap_reg_pp0_iter1_empty_n_5_reg_1385 == 1'd1) & (tmp_25tmp_reg_1498 == 1'd0));
end

always @ (*) begin
    ap_predicate_op196_write_state4 = ((tmp_25tmp_reg_1498 == 1'd1) & (ap_reg_pp0_iter1_empty_n_5_reg_1385 == 1'd1));
end

assign ap_ready = 1'b0;

assign before_boundry_len_fu_1019_p1 = ap_reg_pp0_iter1_tmp_num_8_reg_1390;

assign brmerge1_fu_994_p2 = (or_cond275_not_fu_988_p2 | has_read_req_0_not_fu_964_p2);

assign brmerge2_fu_1207_p2 = (or_cond278_not_fu_1195_p2 | has_write_req_0_not_fu_1201_p2);

assign brmerge3_fu_1231_p2 = (or_cond280_not_fu_1225_p2 | has_write_req_0_not_fu_1201_p2);

assign brmerge_fu_970_p2 = (or_cond_not_fu_958_p2 | has_read_req_0_not_fu_964_p2);

assign ddr_read_req_0_num_3_cast_fu_903_p1 = ddr_read_req_0_num_1_reg_1454;

assign ddr_read_req_0_num_fu_871_p1 = tmp_3_fu_861_p4;

assign ddr_read_req_1_addr_1_fu_803_p3 = ((read_bank_id_reg_1411[0:0] === 1'b1) ? dram_start_addr_cast_fu_784_p1 : tmp_addr_1_fu_378);

assign ddr_read_req_1_addr_2_fu_810_p3 = ((read_bank_id_reg_1411[0:0] === 1'b1) ? tmp_addr_fu_374 : dram_start_addr_cast_fu_784_p1);

assign ddr_read_req_1_addr_4_fu_889_p3 = ((read_end_bank_id_reg_1432[0:0] === 1'b1) ? end_dram_start_addr_cast_fu_799_p1 : ddr_read_req_1_addr_1_fu_803_p3);

assign ddr_read_req_1_addr_5_fu_896_p3 = ((read_end_bank_id_reg_1432[0:0] === 1'b1) ? ddr_read_req_1_addr_2_fu_810_p3 : end_dram_start_addr_cast_fu_799_p1);

assign ddr_read_req_1_num_1_fu_823_p3 = ((read_bank_id_reg_1411[0:0] === 1'b1) ? ap_reg_pp0_iter1_tmp_num_7_reg_1364 : tmp_num_1_fu_370);

assign ddr_read_req_1_num_2_fu_829_p3 = ((read_bank_id_reg_1411[0:0] === 1'b1) ? tmp_num_fu_366 : ap_reg_pp0_iter1_tmp_num_7_reg_1364);

assign ddr_read_req_1_num_3_fu_875_p3 = ((read_bank_id_reg_1411[0:0] === 1'b1) ? ddr_read_req_0_num_fu_871_p1 : tmp_num_1_fu_370);

assign ddr_read_req_1_num_4_fu_882_p3 = ((read_bank_id_reg_1411[0:0] === 1'b1) ? tmp_num_fu_366 : ddr_read_req_0_num_fu_871_p1);

assign ddr_read_req_1_num_6_fu_906_p3 = ((read_end_bank_id_reg_1432[0:0] === 1'b1) ? ddr_read_req_0_num_3_cast_fu_903_p1 : ddr_read_req_1_num_3_fu_875_p3);

assign ddr_read_req_1_num_7_fu_913_p3 = ((read_end_bank_id_reg_1432[0:0] === 1'b1) ? ddr_read_req_1_num_4_fu_882_p3 : ddr_read_req_0_num_3_cast_fu_903_p1);

assign ddr_write_apply_0_num_3_cast_fu_1135_p1 = ddr_write_apply_0_num_1_reg_1502;

assign ddr_write_apply_0_num_fu_1103_p1 = tmp_10_fu_1093_p4;

assign ddr_write_apply_1_addr_1_fu_1035_p3 = ((write_bank_id_reg_1459[0:0] === 1'b1) ? dram_start_addr_1_cast_fu_1015_p1 : tmp_addr_3_fu_394);

assign ddr_write_apply_1_addr_2_fu_1042_p3 = ((write_bank_id_reg_1459[0:0] === 1'b1) ? tmp_addr_2_fu_390 : dram_start_addr_1_cast_fu_1015_p1);

assign ddr_write_apply_1_addr_4_fu_1121_p3 = ((write_end_bank_id_reg_1480[0:0] === 1'b1) ? end_dram_start_addr_1_cast_fu_1031_p1 : ddr_write_apply_1_addr_1_fu_1035_p3);

assign ddr_write_apply_1_addr_5_fu_1128_p3 = ((write_end_bank_id_reg_1480[0:0] === 1'b1) ? ddr_write_apply_1_addr_2_fu_1042_p3 : end_dram_start_addr_1_cast_fu_1031_p1);

assign ddr_write_apply_1_num_1_fu_1055_p3 = ((write_bank_id_reg_1459[0:0] === 1'b1) ? ap_reg_pp0_iter1_tmp_num_8_reg_1390 : tmp_num_3_fu_386);

assign ddr_write_apply_1_num_2_fu_1061_p3 = ((write_bank_id_reg_1459[0:0] === 1'b1) ? tmp_num_2_fu_382 : ap_reg_pp0_iter1_tmp_num_8_reg_1390);

assign ddr_write_apply_1_num_3_fu_1107_p3 = ((write_bank_id_reg_1459[0:0] === 1'b1) ? ddr_write_apply_0_num_fu_1103_p1 : tmp_num_3_fu_386);

assign ddr_write_apply_1_num_4_fu_1114_p3 = ((write_bank_id_reg_1459[0:0] === 1'b1) ? tmp_num_2_fu_382 : ddr_write_apply_0_num_fu_1103_p1);

assign ddr_write_apply_1_num_6_fu_1138_p3 = ((write_end_bank_id_reg_1480[0:0] === 1'b1) ? ddr_write_apply_0_num_3_cast_fu_1135_p1 : ddr_write_apply_1_num_3_fu_1107_p3);

assign ddr_write_apply_1_num_7_fu_1145_p3 = ((write_end_bank_id_reg_1480[0:0] === 1'b1) ? ddr_write_apply_1_num_4_fu_1114_p3 : ddr_write_apply_0_num_3_cast_fu_1135_p1);

assign dramA_read_req_V_addr_din = tmp_addr_fu_374;

assign dramA_read_req_V_addr_write = dramA_read_req_V_num1_update;

assign dramA_read_req_V_num1_status = (dramA_read_req_V_num_full_n & dramA_read_req_V_addr_full_n);

assign dramA_read_req_V_num_din = tmp_num_fu_366;

assign dramA_read_req_V_num_write = dramA_read_req_V_num1_update;

assign dramA_write_req_apply_V_addr_din = tmp_addr_2_fu_390;

assign dramA_write_req_apply_V_addr_write = dramA_write_req_apply_V_num1_update;

assign dramA_write_req_apply_V_num1_status = (dramA_write_req_apply_V_num_full_n & dramA_write_req_apply_V_addr_full_n);

assign dramA_write_req_apply_V_num_din = tmp_num_2_fu_382;

assign dramA_write_req_apply_V_num_write = dramA_write_req_apply_V_num1_update;

assign dramB_read_req_V_addr_din = tmp_addr_1_fu_378;

assign dramB_read_req_V_addr_write = dramB_read_req_V_num1_update;

assign dramB_read_req_V_num1_status = (dramB_read_req_V_num_full_n & dramB_read_req_V_addr_full_n);

assign dramB_read_req_V_num_din = tmp_num_1_fu_370;

assign dramB_read_req_V_num_write = dramB_read_req_V_num1_update;

assign dramB_write_req_apply_V_addr_din = tmp_addr_3_fu_394;

assign dramB_write_req_apply_V_addr_write = dramB_write_req_apply_V_num1_update;

assign dramB_write_req_apply_V_num1_status = (dramB_write_req_apply_V_num_full_n & dramB_write_req_apply_V_addr_full_n);

assign dramB_write_req_apply_V_num_din = tmp_num_3_fu_386;

assign dramB_write_req_apply_V_num_write = dramB_write_req_apply_V_num1_update;

assign dram_start_addr_1_cast_fu_1015_p1 = dram_start_addr_1_fu_1009_p3;

assign dram_start_addr_1_fu_1009_p3 = {{tmp_4_reg_1475}, {ap_reg_pp0_iter1_tmp_14_reg_1405}};

assign dram_start_addr_cast_fu_784_p1 = dram_start_addr_fu_778_p3;

assign dram_start_addr_fu_778_p3 = {{tmp_1_reg_1427}, {ap_reg_pp0_iter1_tmp_6_reg_1379}};

assign empty_n_1_nbread_fu_406_p3_0 = (after_throttle_unified_dram_write_req_apply_V_num_empty_n & after_throttle_unified_dram_write_req_apply_V_addr_empty_n);

assign empty_n_4_fu_511_p1 = empty_n_nbread_fu_398_p3_0;

assign empty_n_5_fu_527_p1 = empty_n_1_nbread_fu_406_p3_0;

assign empty_n_nbread_fu_398_p3_0 = (after_delay_unified_dram_read_req_V_num_empty_n & after_delay_unified_dram_read_req_V_addr_empty_n);

assign end_addr_V_1_fu_700_p2 = ($signed(tmp_16_fu_683_p1) + $signed(tmp2_cast_fu_696_p1));

assign end_addr_V_fu_587_p2 = ($signed(tmp_12_fu_570_p1) + $signed(tmp1_cast_fu_583_p1));

assign end_dram_start_addr_1_cast_fu_1031_p1 = end_dram_start_addr_1_fu_1024_p3;

assign end_dram_start_addr_1_fu_1024_p3 = {{tmp_9_reg_1493}, {12'd0}};

assign end_dram_start_addr_cast_fu_799_p1 = end_dram_start_addr_fu_792_p3;

assign end_dram_start_addr_fu_792_p3 = {{tmp_2_reg_1445}, {12'd0}};

assign has_read_req_0_not_fu_964_p2 = (ap_phi_reg_pp0_iter2_has_read_req1_reg_483 ^ 1'd1);

assign has_write_req_0_not_fu_1201_p2 = (ap_phi_reg_pp0_iter2_has_write_req1_reg_497 ^ 1'd1);

assign lhs_V_2_cast_fu_744_p1 = end_addr_V_1_fu_700_p2;

assign lhs_V_cast_fu_631_p1 = end_addr_V_fu_587_p2;

assign notlhs1_fu_976_p2 = ((tmp_bank_id_3_fu_362 != 8'd1) ? 1'b1 : 1'b0);

assign notlhs2_fu_1183_p2 = ((tmp_bank_id_1_fu_354 != 8'd0) ? 1'b1 : 1'b0);

assign notlhs3_fu_1213_p2 = ((tmp_bank_id_1_fu_354 != 8'd1) ? 1'b1 : 1'b0);

assign notlhs_fu_946_p2 = ((tmp_bank_id_3_fu_362 != 8'd0) ? 1'b1 : 1'b0);

assign notrhs1_fu_982_p2 = ((tmp_bank_id_2_fu_358 != 8'd1) ? 1'b1 : 1'b0);

assign notrhs2_fu_1189_p2 = ((tmp_bank_id_fu_350 != 8'd0) ? 1'b1 : 1'b0);

assign notrhs3_fu_1219_p2 = ((tmp_bank_id_fu_350 != 8'd1) ? 1'b1 : 1'b0);

assign notrhs_fu_952_p2 = ((tmp_bank_id_2_fu_358 != 8'd0) ? 1'b1 : 1'b0);

assign or_cond275_not_fu_988_p2 = (notrhs1_fu_982_p2 & notlhs1_fu_976_p2);

assign or_cond278_not_fu_1195_p2 = (notrhs2_fu_1189_p2 & notlhs2_fu_1183_p2);

assign or_cond280_not_fu_1225_p2 = (notrhs3_fu_1219_p2 & notlhs3_fu_1213_p2);

assign or_cond_not_fu_958_p2 = (notrhs_fu_952_p2 & notlhs_fu_946_p2);

assign r_V_1_fu_748_p2 = (lhs_V_2_cast_fu_744_p1 + 37'd1);

assign r_V_fu_635_p2 = (lhs_V_cast_fu_631_p1 + 37'd1);

assign read_bank_id_fu_543_p3 = tmp_addr_7_reg_1372[32'd12];

assign read_end_bank_id_fu_593_p3 = end_addr_V_fu_587_p2[32'd12];

assign tmp1_cast_fu_583_p1 = $signed(tmp1_fu_577_p2);

assign tmp1_fu_577_p2 = ($signed(15'd32767) + $signed(tmp_9_cast_fu_573_p1));

assign tmp2_cast_fu_696_p1 = $signed(tmp2_fu_690_p2);

assign tmp2_fu_690_p2 = ($signed(15'd32767) + $signed(tmp_22_cast_fu_686_p1));

assign tmp_10_fu_1093_p4 = {{tmp_8_fu_1087_p2[12:6]}};

assign tmp_10tmp_fu_615_p2 = (read_end_bank_id_fu_593_p3 ^ read_bank_id_fu_543_p3);

assign tmp_12_fu_570_p1 = tmp_addr_7_reg_1372[35:0];

assign tmp_14_fu_539_p1 = after_throttle_unified_dram_write_req_apply_V_addr_dout[11:0];

assign tmp_16_fu_683_p1 = tmp_addr_8_reg_1398[35:0];

assign tmp_19_cast_fu_1006_p1 = ap_reg_pp0_iter1_tmp_14_reg_1405;

assign tmp_22_cast_fu_686_p1 = tmp_5_fu_676_p3;

assign tmp_25tmp_fu_728_p2 = (write_end_bank_id_fu_706_p3 ^ write_bank_id_fu_656_p3);

assign tmp_3_fu_861_p4 = {{tmp_s_fu_855_p2[12:6]}};

assign tmp_5_cast_fu_775_p1 = ap_reg_pp0_iter1_tmp_6_reg_1379;

assign tmp_5_fu_676_p3 = {{tmp_num_8_reg_1390}, {6'd0}};

assign tmp_6_fu_523_p1 = after_delay_unified_dram_read_req_V_addr_dout[11:0];

assign tmp_7_fu_563_p3 = {{tmp_num_7_reg_1364}, {6'd0}};

assign tmp_8_fu_1087_p2 = ($signed(13'd4096) - $signed(tmp_19_cast_fu_1006_p1));

assign tmp_9_cast_fu_573_p1 = tmp_7_fu_563_p3;

assign tmp_bank_id_10_fu_550_p1 = read_bank_id_fu_543_p3;

assign tmp_bank_id_11_fu_663_p1 = write_bank_id_fu_656_p3;

assign tmp_before_boundry_num_fu_1152_p1 = tmp_10_fu_1093_p4;

assign tmp_end_bank_id_1_fu_601_p1 = read_end_bank_id_fu_593_p3;

assign tmp_end_bank_id_4_fu_714_p1 = write_end_bank_id_fu_706_p3;

assign tmp_s_fu_855_p2 = ($signed(13'd4096) - $signed(tmp_5_cast_fu_775_p1));

assign unified_dram_dispatcher_read_context_V_bank_id1_status = (unified_dram_dispatcher_read_context_V_end_bank_id_full_n & unified_dram_dispatcher_read_context_V_cmd_num_full_n & unified_dram_dispatcher_read_context_V_bank_id_full_n);

assign unified_dram_dispatcher_read_context_V_bank_id_din = tmp_bank_id_10_reg_1421;

assign unified_dram_dispatcher_read_context_V_bank_id_write = unified_dram_dispatcher_read_context_V_bank_id1_update;

assign unified_dram_dispatcher_read_context_V_cmd_num_din = ap_reg_pp0_iter1_tmp_num_7_reg_1364;

assign unified_dram_dispatcher_read_context_V_cmd_num_write = unified_dram_dispatcher_read_context_V_bank_id1_update;

assign unified_dram_dispatcher_read_context_V_end_bank_id_write = unified_dram_dispatcher_read_context_V_bank_id1_update;

assign unified_dram_dispatcher_write_context_V_bank_id1_status = (unified_dram_dispatcher_write_context_V_end_bank_id_full_n & unified_dram_dispatcher_write_context_V_cmd_num_full_n & unified_dram_dispatcher_write_context_V_before_boundry_num_full_n & unified_dram_dispatcher_write_context_V_bank_id_full_n);

assign unified_dram_dispatcher_write_context_V_bank_id_din = tmp_bank_id_11_reg_1469;

assign unified_dram_dispatcher_write_context_V_bank_id_write = unified_dram_dispatcher_write_context_V_bank_id1_update;

assign unified_dram_dispatcher_write_context_V_before_boundry_num_write = unified_dram_dispatcher_write_context_V_bank_id1_update;

assign unified_dram_dispatcher_write_context_V_cmd_num_din = ap_reg_pp0_iter1_tmp_num_8_reg_1390;

assign unified_dram_dispatcher_write_context_V_cmd_num_write = unified_dram_dispatcher_write_context_V_bank_id1_update;

assign unified_dram_dispatcher_write_context_V_end_bank_id_write = unified_dram_dispatcher_write_context_V_bank_id1_update;

assign write_bank_id_fu_656_p3 = tmp_addr_8_reg_1398[32'd12];

assign write_end_bank_id_fu_706_p3 = end_addr_V_1_fu_700_p2[32'd12];

always @ (posedge ap_clk) begin
    tmp_bank_id_10_reg_1421[7:1] <= 7'b0000000;
    tmp_end_bank_id_1_reg_1440[7:1] <= 7'b0000000;
    tmp_bank_id_11_reg_1469[7:1] <= 7'b0000000;
    tmp_end_bank_id_4_reg_1488[7:1] <= 7'b0000000;
    tmp_bank_id_fu_350[7:1] <= 7'b0000000;
    tmp_bank_id_1_fu_354[7:1] <= 7'b0000000;
    tmp_bank_id_2_fu_358[7:1] <= 7'b0000000;
    tmp_bank_id_3_fu_362[7:1] <= 7'b0000000;
end

endmodule //pipe0_dram_dispatcher
