// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.op
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="poke_handler,hls_ip_2017_4_op,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.225000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=245,HLS_SYN_LUT=1335}" *)

module poke_handler (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
ap_continue,
        ap_idle,
        ap_ready,
        poke_V_tag_dout,
        poke_V_tag_empty_n,
        poke_V_tag_read,
        poke_V_data_dout,
        poke_V_data_empty_n,
        poke_V_data_read,
        dbg_peek_req_V_din,
        dbg_peek_req_V_full_n,
        dbg_peek_req_V_write,
        reqs_incoming_V_sector_off_din,
        reqs_incoming_V_sector_off_full_n,
        reqs_incoming_V_sector_off_write,
        reqs_incoming_V_sector_num_din,
        reqs_incoming_V_sector_num_full_n,
        reqs_incoming_V_sector_num_write,
        reqs_incoming_V_tag_din,
        reqs_incoming_V_tag_full_n,
        reqs_incoming_V_tag_write,
        reqs_incoming_V_rw_din,
        reqs_incoming_V_rw_full_n,
        reqs_incoming_V_rw_write,
        kbuf_addrs_V_din,
        kbuf_addrs_V_full_n,
        kbuf_addrs_V_write,
        dma_read_throttle_params_V_din,
        dma_read_throttle_params_V_full_n,
        dma_read_throttle_params_V_write,
        dma_write_throttle_params_V_din,
        dma_write_throttle_params_V_full_n,
        dma_write_throttle_params_V_write,
        device_read_delay_cycle_cnts_V_din,
        device_read_delay_cycle_cnts_V_full_n,
        device_read_delay_cycle_cnts_V_write,
        device_write_delay_cycle_cnts_V_din,
        device_write_delay_cycle_cnts_V_full_n,
        device_write_delay_cycle_cnts_V_write,
        drive_read_throttle_params_V_din,
        drive_read_throttle_params_V_full_n,
        drive_read_throttle_params_V_write,
        drive_write_throttle_params_V_din,
        drive_write_throttle_params_V_full_n,
        drive_write_throttle_params_V_write,
        app_file_infos_0_V_din,
        app_file_infos_0_V_full_n,
        app_file_infos_0_V_write,
        app_file_infos_1_V_din,
        app_file_infos_1_V_full_n,
        app_file_infos_1_V_write,
        read_mode_app_buf_addrs_V_din,
        read_mode_app_buf_addrs_V_full_n,
        read_mode_app_buf_addrs_V_write,
        write_mode_app_buf_addrs_V_din,
        write_mode_app_buf_addrs_V_full_n,
        write_mode_app_buf_addrs_V_write,
        app_free_buf_V_din,
        app_free_buf_V_full_n,
        app_free_buf_V_write,
        app_write_total_len_V_din,
        app_write_total_len_V_full_n,
        app_write_total_len_V_write,
        app_input_params_V_din,
        app_input_params_V_full_n,
        app_input_params_V_write,
        app_commit_write_buf_V_din,
        app_commit_write_buf_V_full_n,
        app_commit_write_buf_V_write,
        app_is_write_mode_0_V_din,
        app_is_write_mode_0_V_full_n,
        app_is_write_mode_0_V_write,
        app_is_write_mode_1_V_din,
        app_is_write_mode_1_V_full_n,
        app_is_write_mode_1_V_write,
        app_is_write_mode_2_V_din,
        app_is_write_mode_2_V_full_n,
        app_is_write_mode_2_V_write,
        reset_sigs_V_din,
        reset_sigs_V_full_n,
        reset_sigs_V_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output ap_ready; output ap_continue;
input  [31:0] poke_V_tag_dout;
input   poke_V_tag_empty_n;
output   poke_V_tag_read;
input  [31:0] poke_V_data_dout;
input   poke_V_data_empty_n;
output   poke_V_data_read;
output  [31:0] dbg_peek_req_V_din;
input   dbg_peek_req_V_full_n;
output   dbg_peek_req_V_write;
output  [31:0] reqs_incoming_V_sector_off_din;
input   reqs_incoming_V_sector_off_full_n;
output   reqs_incoming_V_sector_off_write;
output  [31:0] reqs_incoming_V_sector_num_din;
input   reqs_incoming_V_sector_num_full_n;
output   reqs_incoming_V_sector_num_write;
output  [31:0] reqs_incoming_V_tag_din;
input   reqs_incoming_V_tag_full_n;
output   reqs_incoming_V_tag_write;
output   reqs_incoming_V_rw_din;
input   reqs_incoming_V_rw_full_n;
output   reqs_incoming_V_rw_write;
output  [31:0] kbuf_addrs_V_din;
input   kbuf_addrs_V_full_n;
output   kbuf_addrs_V_write;
output  [31:0] dma_read_throttle_params_V_din;
input   dma_read_throttle_params_V_full_n;
output   dma_read_throttle_params_V_write;
output  [31:0] dma_write_throttle_params_V_din;
input   dma_write_throttle_params_V_full_n;
output   dma_write_throttle_params_V_write;
output  [31:0] device_read_delay_cycle_cnts_V_din;
input   device_read_delay_cycle_cnts_V_full_n;
output   device_read_delay_cycle_cnts_V_write;
output  [31:0] device_write_delay_cycle_cnts_V_din;
input   device_write_delay_cycle_cnts_V_full_n;
output   device_write_delay_cycle_cnts_V_write;
output  [31:0] drive_read_throttle_params_V_din;
input   drive_read_throttle_params_V_full_n;
output   drive_read_throttle_params_V_write;
output  [31:0] drive_write_throttle_params_V_din;
input   drive_write_throttle_params_V_full_n;
output   drive_write_throttle_params_V_write;
output  [31:0] app_file_infos_0_V_din;
input   app_file_infos_0_V_full_n;
output   app_file_infos_0_V_write;
output  [31:0] app_file_infos_1_V_din;
input   app_file_infos_1_V_full_n;
output   app_file_infos_1_V_write;
output  [31:0] read_mode_app_buf_addrs_V_din;
input   read_mode_app_buf_addrs_V_full_n;
output   read_mode_app_buf_addrs_V_write;
output  [31:0] write_mode_app_buf_addrs_V_din;
input   write_mode_app_buf_addrs_V_full_n;
output   write_mode_app_buf_addrs_V_write;
output   app_free_buf_V_din;
input   app_free_buf_V_full_n;
output   app_free_buf_V_write;
output  [63:0] app_write_total_len_V_din;
input   app_write_total_len_V_full_n;
output   app_write_total_len_V_write;
output  [31:0] app_input_params_V_din;
input   app_input_params_V_full_n;
output   app_input_params_V_write;
output  [31:0] app_commit_write_buf_V_din;
input   app_commit_write_buf_V_full_n;
output   app_commit_write_buf_V_write;
output   app_is_write_mode_0_V_din;
input   app_is_write_mode_0_V_full_n;
output   app_is_write_mode_0_V_write;
output   app_is_write_mode_1_V_din;
input   app_is_write_mode_1_V_full_n;
output   app_is_write_mode_1_V_write;
output   app_is_write_mode_2_V_din;
input   app_is_write_mode_2_V_full_n;
output   app_is_write_mode_2_V_write;
output   reset_sigs_V_din;
input   reset_sigs_V_full_n;
output   reset_sigs_V_write;

reg ap_idle;
reg dbg_peek_req_V_write;
reg[31:0] reqs_incoming_V_sector_off_din;
reg[31:0] reqs_incoming_V_sector_num_din;
reg[31:0] reqs_incoming_V_tag_din;
reg reqs_incoming_V_rw_din;
reg kbuf_addrs_V_write;
reg dma_read_throttle_params_V_write;
reg dma_write_throttle_params_V_write;
reg device_read_delay_cycle_cnts_V_write;
reg device_write_delay_cycle_cnts_V_write;
reg drive_read_throttle_params_V_write;
reg drive_write_throttle_params_V_write;
reg app_file_infos_0_V_write;
reg app_file_infos_1_V_write;
reg read_mode_app_buf_addrs_V_write;
reg write_mode_app_buf_addrs_V_write;
reg app_free_buf_V_write;
reg app_write_total_len_V_write;
reg app_input_params_V_write;
reg app_commit_write_buf_V_write;
reg app_is_write_mode_0_V_write;
reg app_is_write_mode_1_V_write;
reg app_is_write_mode_2_V_write;
reg reset_sigs_V_write;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    dbg_peek_req_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_15_reg_1290;
reg   [0:0] tmp_16_reg_1294;
reg   [0:0] tmp_18_reg_1298;
reg   [0:0] tmp_19_reg_1302;
reg   [0:0] tmp_21_reg_1306;
reg   [0:0] tmp_22_reg_1310;
reg   [0:0] tmp_23_reg_1314;
reg   [0:0] tmp_24_reg_1318;
reg   [0:0] tmp_28_reg_1322;
reg   [0:0] tmp_29_reg_1326;
reg   [0:0] tmp_30_reg_1330;
reg   [0:0] tmp_31_reg_1334;
reg   [0:0] tmp_32_reg_1338;
reg   [0:0] tmp_33_reg_1342;
reg   [0:0] tmp_34_reg_1346;
reg   [0:0] tmp_40_reg_1350;
reg    reqs_incoming_V_sector_off_blk_n;
reg    reqs_incoming_V_sector_num_blk_n;
reg    reqs_incoming_V_tag_blk_n;
reg    reqs_incoming_V_rw_blk_n;
reg    kbuf_addrs_V_blk_n;
reg    dma_read_throttle_params_V_blk_n;
reg   [0:0] is_read_host_throttle_params_load_reg_1362;
reg    dma_write_throttle_params_V_blk_n;
reg    device_read_delay_cycle_cnts_V_blk_n;
reg    device_write_delay_cycle_cnts_V_blk_n;
reg    drive_read_throttle_params_V_blk_n;
reg   [0:0] is_read_device_throttle_params_load_reg_1358;
reg    drive_write_throttle_params_V_blk_n;
reg    read_mode_app_buf_addrs_V_blk_n;
reg    write_mode_app_buf_addrs_V_blk_n;
reg    app_free_buf_V_blk_n;
reg    app_write_total_len_V_blk_n;
reg   [0:0] has_half_write_total_len_load_reg_1354;
reg    app_input_params_V_blk_n;
reg    app_commit_write_buf_V_blk_n;
reg    app_is_write_mode_0_V_blk_n;
reg    app_is_write_mode_1_V_blk_n;
reg    app_is_write_mode_2_V_blk_n;
reg    reset_sigs_V_blk_n;
wire   [0:0] empty_n_1_fu_789_p1;
reg   [0:0] empty_n_1_reg_1196;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_predicate_op173_write_state4;
reg    ap_predicate_op176_write_state4;
reg    ap_predicate_op187_write_state4;
reg    ap_predicate_op189_write_state4;
reg    ap_predicate_op190_write_state4;
reg    ap_predicate_op191_write_state4;
reg    ap_predicate_op192_write_state4;
reg    ap_predicate_op193_write_state4;
reg    ap_predicate_op195_write_state4;
reg    ap_predicate_op196_write_state4;
reg    ap_predicate_op197_write_state4;
reg    ap_predicate_op199_write_state4;
reg    ap_predicate_op200_write_state4;
reg    ap_predicate_op201_write_state4;
wire    reqs_incoming_V_rw1_status;
reg    ap_predicate_op211_write_state4;
reg    ap_predicate_op221_write_state4;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] tmp_tag_4_reg_1200;
reg   [31:0] ap_reg_pp0_iter1_tmp_tag_4_reg_1200;
reg   [31:0] tmp_data_reg_1206;
reg   [31:0] ap_reg_pp0_iter1_tmp_data_reg_1206;
wire   [2:0] tmp_2_fu_801_p1;
reg   [2:0] tmp_2_reg_1228;
reg   [2:0] ap_reg_pp0_iter1_tmp_2_reg_1228;
wire   [0:0] icmp_fu_815_p2;
reg   [0:0] icmp_reg_1234;
wire   [0:0] icmp3_fu_831_p2;
reg   [0:0] icmp3_reg_1238;
wire   [0:0] tmp_3_fu_837_p2;
reg   [0:0] tmp_3_reg_1242;
wire   [0:0] tmp_4_fu_843_p2;
reg   [0:0] tmp_4_reg_1246;
wire   [0:0] tmp_5_fu_849_p2;
reg   [0:0] tmp_5_reg_1250;
wire   [0:0] tmp_6_fu_855_p2;
reg   [0:0] tmp_6_reg_1254;
wire   [0:0] tmp_7_fu_861_p2;
reg   [0:0] tmp_7_reg_1258;
wire   [0:0] tmp_8_fu_867_p2;
reg   [0:0] tmp_8_reg_1262;
wire   [0:0] tmp_9_fu_873_p2;
reg   [0:0] tmp_9_reg_1266;
wire   [0:0] tmp_s_fu_879_p2;
reg   [0:0] tmp_s_reg_1270;
wire   [0:0] tmp_10_fu_885_p2;
reg   [0:0] tmp_10_reg_1274;
wire   [0:0] tmp_11_fu_891_p2;
reg   [0:0] tmp_11_reg_1278;
wire   [0:0] tmp_12_fu_897_p2;
reg   [0:0] tmp_12_reg_1282;
wire   [0:0] tmp_13_fu_903_p2;
reg   [0:0] tmp_13_reg_1286;
wire   [0:0] tmp_15_fu_923_p2;
wire   [0:0] tmp_16_fu_929_p2;
wire   [0:0] tmp_18_fu_935_p2;
wire   [0:0] tmp_19_fu_941_p2;
wire   [0:0] tmp_21_fu_947_p2;
wire   [0:0] tmp_22_fu_953_p2;
wire   [0:0] tmp_23_fu_959_p2;
wire   [0:0] tmp_24_fu_965_p2;
wire   [0:0] tmp_28_fu_971_p2;
wire   [0:0] tmp_29_fu_977_p2;
wire   [0:0] tmp_30_fu_983_p2;
wire   [0:0] tmp_31_fu_989_p2;
wire   [0:0] tmp_32_fu_995_p2;
wire   [0:0] tmp_33_fu_1001_p2;
wire   [0:0] tmp_34_fu_1007_p2;
wire   [0:0] tmp_40_fu_1013_p2;
wire   [0:0] has_half_write_total_len_load_load_fu_1019_p1;
wire   [0:0] is_read_device_throttle_params_load_load_fu_1027_p1;
wire   [0:0] is_read_host_throttle_params_load_load_fu_1035_p1;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg   [4:0] ap_phi_mux_state_s_phi_fu_702_p32;
wire   [4:0] p_s_fu_914_p3;
reg   [4:0] ap_phi_reg_pp0_iter1_state_s_reg_684;
wire   [4:0] ap_phi_reg_pp0_iter0_state_s_reg_684;
reg    poke_V_tag0_update;
wire   [0:0] empty_n_nbread_fu_516_p3_0;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] tmp_39_fu_1043_p2;
wire   [63:0] write_total_len_2_fu_1085_p3;
reg    reqs_incoming_V_rw1_update;
wire   [31:0] req_sector_off_5_fu_1099_p1;
wire   [31:0] req_sector_off_4_fu_1133_p1;
wire   [31:0] tmp_sector_num_3_fu_1113_p1;
wire   [31:0] tmp_sector_num_1_fu_1147_p1;
wire  signed [31:0] tmp_tag_3_fu_1128_p1;
wire  signed [31:0] tmp_tag_1_fu_1162_p1;
reg   [0:0] has_half_write_total_len_fu_500;
reg   [0:0] is_read_device_throttle_params_fu_504;
reg   [0:0] is_read_host_throttle_params_fu_508;
reg   [63:0] tmp_fu_512;
wire   [63:0] write_total_len_fu_1051_p3;
wire   [22:0] tmp_17_fu_805_p4;
wire   [23:0] tmp_25_fu_821_p4;
wire   [0:0] tmp_14_fu_909_p2;
wire   [31:0] tmp_35_fu_1066_p1;
wire   [31:0] tmp_37_fu_1075_p4;
wire   [31:0] tmp_36_fu_1070_p2;
wire   [28:0] grp_fu_766_p4;
wire   [3:0] tmp_20_cast_fu_1104_p1;
wire   [3:0] req_sector_num_1_fu_1107_p2;
wire   [29:0] grp_fu_775_p4;
wire   [30:0] tmp_21_cast_fu_1118_p1;
wire   [30:0] req_tag_1_fu_1122_p2;
wire   [3:0] tmp_17_cast_fu_1138_p1;
wire   [3:0] req_sector_num_fu_1141_p2;
wire   [30:0] tmp_18_cast_fu_1152_p1;
wire   [30:0] req_tag_fu_1156_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_610;
reg    ap_condition_616;
reg    ap_condition_623;
reg    ap_condition_631;
reg    ap_condition_640;
reg    ap_condition_650;
reg    ap_condition_661;
reg    ap_condition_673;
reg    ap_condition_686;
reg    ap_condition_700;
reg    ap_condition_715;
reg    ap_condition_731;
reg    ap_condition_748;
reg    ap_condition_600;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_600)) begin
        if ((1'b1 == ap_condition_748)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd16;
        end else if ((1'b1 == ap_condition_731)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd15;
        end else if ((1'b1 == ap_condition_715)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd14;
        end else if ((1'b1 == ap_condition_700)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd13;
        end else if ((1'b1 == ap_condition_686)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd12;
        end else if ((1'b1 == ap_condition_673)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd11;
        end else if ((1'b1 == ap_condition_661)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd10;
        end else if ((1'b1 == ap_condition_650)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd9;
        end else if ((1'b1 == ap_condition_640)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd7;
        end else if ((1'b1 == ap_condition_631)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd6;
        end else if ((1'b1 == ap_condition_623)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd5;
        end else if ((1'b1 == ap_condition_616)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd3;
        end else if ((1'b1 == ap_condition_610)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd2;
        end else if (((empty_n_1_fu_789_p1 == 1'd1) & (icmp_fu_815_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd1;
        end else if ((empty_n_1_fu_789_p1 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= 5'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_state_s_reg_684 <= ap_phi_reg_pp0_iter0_state_s_reg_684;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_33_fu_1001_p2 == 1'd1) & (has_half_write_total_len_load_load_fu_1019_p1 == 1'd0) & (tmp_32_fu_995_p2 == 1'd0) & (tmp_31_fu_989_p2 == 1'd0) & (tmp_30_fu_983_p2 == 1'd0) & (tmp_29_fu_977_p2 == 1'd0) & (tmp_28_fu_971_p2 == 1'd0) & (tmp_24_fu_965_p2 == 1'd0) & (tmp_23_fu_959_p2 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        has_half_write_total_len_fu_500 <= 1'd1;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (has_half_write_total_len_load_load_fu_1019_p1 == 1'd1) & (tmp_33_fu_1001_p2 == 1'd1) & (tmp_32_fu_995_p2 == 1'd0) & (tmp_31_fu_989_p2 == 1'd0) & (tmp_30_fu_983_p2 == 1'd0) & (tmp_29_fu_977_p2 == 1'd0) & (tmp_28_fu_971_p2 == 1'd0) & (tmp_24_fu_965_p2 == 1'd0) & (tmp_23_fu_959_p2 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        has_half_write_total_len_fu_500 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (is_read_device_throttle_params_load_load_fu_1027_p1 == 1'd1) & (tmp_23_fu_959_p2 == 1'd1) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        is_read_device_throttle_params_fu_504 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_23_fu_959_p2 == 1'd1) & (is_read_device_throttle_params_load_load_fu_1027_p1 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        is_read_device_throttle_params_fu_504 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (is_read_host_throttle_params_load_load_fu_1035_p1 == 1'd1) & (tmp_21_fu_947_p2 == 1'd1) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        is_read_host_throttle_params_fu_508 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_21_fu_947_p2 == 1'd1) & (is_read_host_throttle_params_load_load_fu_1035_p1 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        is_read_host_throttle_params_fu_508 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op187_write_state4 == 1'b1))) begin
        tmp_fu_512 <= write_total_len_2_fu_1085_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_33_reg_1342 == 1'd1) & (has_half_write_total_len_load_reg_1354 == 1'd0) & (tmp_32_reg_1338 == 1'd0) & (tmp_31_reg_1334 == 1'd0) & (tmp_30_reg_1330 == 1'd0) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0))) begin
        tmp_fu_512 <= write_total_len_fu_1051_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_fu_512 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_reg_pp0_iter1_tmp_2_reg_1228 <= tmp_2_reg_1228;
        ap_reg_pp0_iter1_tmp_data_reg_1206 <= tmp_data_reg_1206;
        ap_reg_pp0_iter1_tmp_tag_4_reg_1200 <= tmp_tag_4_reg_1200;
        empty_n_1_reg_1196 <= empty_n_nbread_fu_516_p3_0;
        tmp_15_reg_1290 <= tmp_15_fu_923_p2;
        tmp_2_reg_1228 <= tmp_2_fu_801_p1;
        tmp_data_reg_1206 <= poke_V_data_dout;
        tmp_tag_4_reg_1200 <= poke_V_tag_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_33_fu_1001_p2 == 1'd1) & (tmp_32_fu_995_p2 == 1'd0) & (tmp_31_fu_989_p2 == 1'd0) & (tmp_30_fu_983_p2 == 1'd0) & (tmp_29_fu_977_p2 == 1'd0) & (tmp_28_fu_971_p2 == 1'd0) & (tmp_24_fu_965_p2 == 1'd0) & (tmp_23_fu_959_p2 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        has_half_write_total_len_load_reg_1354 <= has_half_write_total_len_fu_500;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1))) begin
        icmp3_reg_1238 <= icmp3_fu_831_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (empty_n_1_fu_789_p1 == 1'd1))) begin
        icmp_reg_1234 <= icmp_fu_815_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_23_fu_959_p2 == 1'd1) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        is_read_device_throttle_params_load_reg_1358 <= is_read_device_throttle_params_fu_504;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_21_fu_947_p2 == 1'd1) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        is_read_host_throttle_params_load_reg_1362 <= is_read_host_throttle_params_fu_508;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_s_fu_879_p2 == 1'd0) & (tmp_9_fu_873_p2 == 1'd0) & (tmp_8_fu_867_p2 == 1'd0) & (tmp_7_fu_861_p2 == 1'd0) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0))) begin
        tmp_10_reg_1274 <= tmp_10_fu_885_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_10_fu_885_p2 == 1'd0) & (tmp_s_fu_879_p2 == 1'd0) & (tmp_9_fu_873_p2 == 1'd0) & (tmp_8_fu_867_p2 == 1'd0) & (tmp_7_fu_861_p2 == 1'd0) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0))) begin
        tmp_11_reg_1278 <= tmp_11_fu_891_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_11_fu_891_p2 == 1'd0) & (tmp_10_fu_885_p2 == 1'd0) & (tmp_s_fu_879_p2 == 1'd0) & (tmp_9_fu_873_p2 == 1'd0) & (tmp_8_fu_867_p2 == 1'd0) & (tmp_7_fu_861_p2 == 1'd0) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0))) begin
        tmp_12_reg_1282 <= tmp_12_fu_897_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_12_fu_897_p2 == 1'd0) & (tmp_11_fu_891_p2 == 1'd0) & (tmp_10_fu_885_p2 == 1'd0) & (tmp_s_fu_879_p2 == 1'd0) & (tmp_9_fu_873_p2 == 1'd0) & (tmp_8_fu_867_p2 == 1'd0) & (tmp_7_fu_861_p2 == 1'd0) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0))) begin
        tmp_13_reg_1286 <= tmp_13_fu_903_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_16_reg_1294 <= tmp_16_fu_929_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_18_reg_1298 <= tmp_18_fu_935_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_19_reg_1302 <= tmp_19_fu_941_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_21_reg_1306 <= tmp_21_fu_947_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_22_reg_1310 <= tmp_22_fu_953_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_23_reg_1314 <= tmp_23_fu_959_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_23_fu_959_p2 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_24_reg_1318 <= tmp_24_fu_965_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_24_fu_965_p2 == 1'd0) & (tmp_23_fu_959_p2 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_28_reg_1322 <= tmp_28_fu_971_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_28_fu_971_p2 == 1'd0) & (tmp_24_fu_965_p2 == 1'd0) & (tmp_23_fu_959_p2 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_29_reg_1326 <= tmp_29_fu_977_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_29_fu_977_p2 == 1'd0) & (tmp_28_fu_971_p2 == 1'd0) & (tmp_24_fu_965_p2 == 1'd0) & (tmp_23_fu_959_p2 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_30_reg_1330 <= tmp_30_fu_983_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_30_fu_983_p2 == 1'd0) & (tmp_29_fu_977_p2 == 1'd0) & (tmp_28_fu_971_p2 == 1'd0) & (tmp_24_fu_965_p2 == 1'd0) & (tmp_23_fu_959_p2 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_31_reg_1334 <= tmp_31_fu_989_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_31_fu_989_p2 == 1'd0) & (tmp_30_fu_983_p2 == 1'd0) & (tmp_29_fu_977_p2 == 1'd0) & (tmp_28_fu_971_p2 == 1'd0) & (tmp_24_fu_965_p2 == 1'd0) & (tmp_23_fu_959_p2 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_32_reg_1338 <= tmp_32_fu_995_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_32_fu_995_p2 == 1'd0) & (tmp_31_fu_989_p2 == 1'd0) & (tmp_30_fu_983_p2 == 1'd0) & (tmp_29_fu_977_p2 == 1'd0) & (tmp_28_fu_971_p2 == 1'd0) & (tmp_24_fu_965_p2 == 1'd0) & (tmp_23_fu_959_p2 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_33_reg_1342 <= tmp_33_fu_1001_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_33_fu_1001_p2 == 1'd0) & (tmp_32_fu_995_p2 == 1'd0) & (tmp_31_fu_989_p2 == 1'd0) & (tmp_30_fu_983_p2 == 1'd0) & (tmp_29_fu_977_p2 == 1'd0) & (tmp_28_fu_971_p2 == 1'd0) & (tmp_24_fu_965_p2 == 1'd0) & (tmp_23_fu_959_p2 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_34_reg_1346 <= tmp_34_fu_1007_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1))) begin
        tmp_3_reg_1242 <= tmp_3_fu_837_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_34_fu_1007_p2 == 1'd0) & (tmp_33_fu_1001_p2 == 1'd0) & (tmp_32_fu_995_p2 == 1'd0) & (tmp_31_fu_989_p2 == 1'd0) & (tmp_30_fu_983_p2 == 1'd0) & (tmp_29_fu_977_p2 == 1'd0) & (tmp_28_fu_971_p2 == 1'd0) & (tmp_24_fu_965_p2 == 1'd0) & (tmp_23_fu_959_p2 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        tmp_40_reg_1350 <= tmp_40_fu_1013_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_3_fu_837_p2 == 1'd0))) begin
        tmp_4_reg_1246 <= tmp_4_fu_843_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0))) begin
        tmp_5_reg_1250 <= tmp_5_fu_849_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0))) begin
        tmp_6_reg_1254 <= tmp_6_fu_855_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0))) begin
        tmp_7_reg_1258 <= tmp_7_fu_861_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_7_fu_861_p2 == 1'd0) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0))) begin
        tmp_8_reg_1262 <= tmp_8_fu_867_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_8_fu_867_p2 == 1'd0) & (tmp_7_fu_861_p2 == 1'd0) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0))) begin
        tmp_9_reg_1266 <= tmp_9_fu_873_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_9_fu_873_p2 == 1'd0) & (tmp_8_fu_867_p2 == 1'd0) & (tmp_7_fu_861_p2 == 1'd0) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0))) begin
        tmp_s_reg_1270 <= tmp_s_fu_879_p2;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp3_reg_1238 == 1'd1) & (icmp_reg_1234 == 1'd1) & (empty_n_1_reg_1196 == 1'd1) & (tmp_13_reg_1286 == 1'd0) & (tmp_12_reg_1282 == 1'd0) & (tmp_11_reg_1278 == 1'd0) & (tmp_10_reg_1274 == 1'd0) & (tmp_s_reg_1270 == 1'd0) & (tmp_9_reg_1266 == 1'd0) & (tmp_8_reg_1262 == 1'd0) & (tmp_7_reg_1258 == 1'd0) & (tmp_6_reg_1254 == 1'd0) & (tmp_5_reg_1250 == 1'd0) & (tmp_4_reg_1246 == 1'd0) & (tmp_3_reg_1242 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_state_s_phi_fu_702_p32 = p_s_fu_914_p3;
    end else begin
        ap_phi_mux_state_s_phi_fu_702_p32 = ap_phi_reg_pp0_iter1_state_s_reg_684;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_32_reg_1338 == 1'd1) & (tmp_31_reg_1334 == 1'd0) & (tmp_30_reg_1330 == 1'd0) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        app_commit_write_buf_V_blk_n = app_commit_write_buf_V_full_n;
    end else begin
        app_commit_write_buf_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op189_write_state4 == 1'b1))) begin
        app_commit_write_buf_V_write = 1'b1;
    end else begin
        app_commit_write_buf_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (app_file_infos_0_V_full_n == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_24_fu_965_p2 == 1'd1) & (tmp_23_fu_959_p2 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        app_file_infos_0_V_write = 1'b1;
    end else begin
        app_file_infos_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (app_file_infos_1_V_full_n == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_24_fu_965_p2 == 1'd1) & (tmp_23_fu_959_p2 == 1'd0) & (tmp_22_fu_953_p2 == 1'd0) & (tmp_21_fu_947_p2 == 1'd0) & (tmp_19_fu_941_p2 == 1'd0) & (tmp_18_fu_935_p2 == 1'd0) & (tmp_16_fu_929_p2 == 1'd0) & (tmp_15_fu_923_p2 == 1'd0))) begin
        app_file_infos_1_V_write = 1'b1;
    end else begin
        app_file_infos_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_29_reg_1326 == 1'd1) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        app_free_buf_V_blk_n = app_free_buf_V_full_n;
    end else begin
        app_free_buf_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op192_write_state4 == 1'b1))) begin
        app_free_buf_V_write = 1'b1;
    end else begin
        app_free_buf_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_30_reg_1330 == 1'd1) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        app_input_params_V_blk_n = app_input_params_V_full_n;
    end else begin
        app_input_params_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op191_write_state4 == 1'b1))) begin
        app_input_params_V_write = 1'b1;
    end else begin
        app_input_params_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_34_reg_1346 == 1'd1) & (tmp_33_reg_1342 == 1'd0) & (tmp_32_reg_1338 == 1'd0) & (tmp_31_reg_1334 == 1'd0) & (tmp_30_reg_1330 == 1'd0) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        app_is_write_mode_0_V_blk_n = app_is_write_mode_0_V_full_n;
    end else begin
        app_is_write_mode_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op176_write_state4 == 1'b1))) begin
        app_is_write_mode_0_V_write = 1'b1;
    end else begin
        app_is_write_mode_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_34_reg_1346 == 1'd1) & (tmp_33_reg_1342 == 1'd0) & (tmp_32_reg_1338 == 1'd0) & (tmp_31_reg_1334 == 1'd0) & (tmp_30_reg_1330 == 1'd0) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        app_is_write_mode_1_V_blk_n = app_is_write_mode_1_V_full_n;
    end else begin
        app_is_write_mode_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op176_write_state4 == 1'b1))) begin
        app_is_write_mode_1_V_write = 1'b1;
    end else begin
        app_is_write_mode_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_34_reg_1346 == 1'd1) & (tmp_33_reg_1342 == 1'd0) & (tmp_32_reg_1338 == 1'd0) & (tmp_31_reg_1334 == 1'd0) & (tmp_30_reg_1330 == 1'd0) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        app_is_write_mode_2_V_blk_n = app_is_write_mode_2_V_full_n;
    end else begin
        app_is_write_mode_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op176_write_state4 == 1'b1))) begin
        app_is_write_mode_2_V_write = 1'b1;
    end else begin
        app_is_write_mode_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (has_half_write_total_len_load_reg_1354 == 1'd1) & (tmp_33_reg_1342 == 1'd1) & (tmp_32_reg_1338 == 1'd0) & (tmp_31_reg_1334 == 1'd0) & (tmp_30_reg_1330 == 1'd0) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        app_write_total_len_V_blk_n = app_write_total_len_V_full_n;
    end else begin
        app_write_total_len_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op187_write_state4 == 1'b1))) begin
        app_write_total_len_V_write = 1'b1;
    end else begin
        app_write_total_len_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_40_reg_1350 == 1'd1) & (tmp_34_reg_1346 == 1'd0) & (tmp_33_reg_1342 == 1'd0) & (tmp_32_reg_1338 == 1'd0) & (tmp_31_reg_1334 == 1'd0) & (tmp_30_reg_1330 == 1'd0) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        dbg_peek_req_V_blk_n = dbg_peek_req_V_full_n;
    end else begin
        dbg_peek_req_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op173_write_state4 == 1'b1))) begin
        dbg_peek_req_V_write = 1'b1;
    end else begin
        dbg_peek_req_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_22_reg_1310 == 1'd1) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        device_read_delay_cycle_cnts_V_blk_n = device_read_delay_cycle_cnts_V_full_n;
    end else begin
        device_read_delay_cycle_cnts_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op197_write_state4 == 1'b1))) begin
        device_read_delay_cycle_cnts_V_write = 1'b1;
    end else begin
        device_read_delay_cycle_cnts_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_22_reg_1310 == 1'd1) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        device_write_delay_cycle_cnts_V_blk_n = device_write_delay_cycle_cnts_V_full_n;
    end else begin
        device_write_delay_cycle_cnts_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op197_write_state4 == 1'b1))) begin
        device_write_delay_cycle_cnts_V_write = 1'b1;
    end else begin
        device_write_delay_cycle_cnts_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (is_read_host_throttle_params_load_reg_1362 == 1'd1) & (tmp_21_reg_1306 == 1'd1) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        dma_read_throttle_params_V_blk_n = dma_read_throttle_params_V_full_n;
    end else begin
        dma_read_throttle_params_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op200_write_state4 == 1'b1))) begin
        dma_read_throttle_params_V_write = 1'b1;
    end else begin
        dma_read_throttle_params_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_21_reg_1306 == 1'd1) & (is_read_host_throttle_params_load_reg_1362 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        dma_write_throttle_params_V_blk_n = dma_write_throttle_params_V_full_n;
    end else begin
        dma_write_throttle_params_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op199_write_state4 == 1'b1))) begin
        dma_write_throttle_params_V_write = 1'b1;
    end else begin
        dma_write_throttle_params_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (is_read_device_throttle_params_load_reg_1358 == 1'd1) & (tmp_23_reg_1314 == 1'd1) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        drive_read_throttle_params_V_blk_n = drive_read_throttle_params_V_full_n;
    end else begin
        drive_read_throttle_params_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op196_write_state4 == 1'b1))) begin
        drive_read_throttle_params_V_write = 1'b1;
    end else begin
        drive_read_throttle_params_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_23_reg_1314 == 1'd1) & (is_read_device_throttle_params_load_reg_1358 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        drive_write_throttle_params_V_blk_n = drive_write_throttle_params_V_full_n;
    end else begin
        drive_write_throttle_params_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op195_write_state4 == 1'b1))) begin
        drive_write_throttle_params_V_write = 1'b1;
    end else begin
        drive_write_throttle_params_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_19_reg_1302 == 1'd1) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        kbuf_addrs_V_blk_n = kbuf_addrs_V_full_n;
    end else begin
        kbuf_addrs_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op201_write_state4 == 1'b1))) begin
        kbuf_addrs_V_write = 1'b1;
    end else begin
        kbuf_addrs_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & ((poke_V_tag_empty_n & poke_V_data_empty_n) == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        poke_V_tag0_update = 1'b1;
    end else begin
        poke_V_tag0_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_28_reg_1322 == 1'd1) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        read_mode_app_buf_addrs_V_blk_n = read_mode_app_buf_addrs_V_full_n;
    end else begin
        read_mode_app_buf_addrs_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op193_write_state4 == 1'b1))) begin
        read_mode_app_buf_addrs_V_write = 1'b1;
    end else begin
        read_mode_app_buf_addrs_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op221_write_state4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op211_write_state4 == 1'b1)))) begin
        reqs_incoming_V_rw1_update = 1'b1;
    end else begin
        reqs_incoming_V_rw1_update = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_16_reg_1294 == 1'd1) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_18_reg_1298 == 1'd1) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        reqs_incoming_V_rw_blk_n = reqs_incoming_V_rw_full_n;
    end else begin
        reqs_incoming_V_rw_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op221_write_state4 == 1'b1)) begin
            reqs_incoming_V_rw_din = 1'd1;
        end else if ((ap_predicate_op211_write_state4 == 1'b1)) begin
            reqs_incoming_V_rw_din = 1'd0;
        end else begin
            reqs_incoming_V_rw_din = 'bx;
        end
    end else begin
        reqs_incoming_V_rw_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_16_reg_1294 == 1'd1) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_18_reg_1298 == 1'd1) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        reqs_incoming_V_sector_num_blk_n = reqs_incoming_V_sector_num_full_n;
    end else begin
        reqs_incoming_V_sector_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op221_write_state4 == 1'b1)) begin
            reqs_incoming_V_sector_num_din = tmp_sector_num_1_fu_1147_p1;
        end else if ((ap_predicate_op211_write_state4 == 1'b1)) begin
            reqs_incoming_V_sector_num_din = tmp_sector_num_3_fu_1113_p1;
        end else begin
            reqs_incoming_V_sector_num_din = 'bx;
        end
    end else begin
        reqs_incoming_V_sector_num_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_16_reg_1294 == 1'd1) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_18_reg_1298 == 1'd1) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        reqs_incoming_V_sector_off_blk_n = reqs_incoming_V_sector_off_full_n;
    end else begin
        reqs_incoming_V_sector_off_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op221_write_state4 == 1'b1)) begin
            reqs_incoming_V_sector_off_din = req_sector_off_4_fu_1133_p1;
        end else if ((ap_predicate_op211_write_state4 == 1'b1)) begin
            reqs_incoming_V_sector_off_din = req_sector_off_5_fu_1099_p1;
        end else begin
            reqs_incoming_V_sector_off_din = 'bx;
        end
    end else begin
        reqs_incoming_V_sector_off_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_16_reg_1294 == 1'd1) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_18_reg_1298 == 1'd1) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        reqs_incoming_V_tag_blk_n = reqs_incoming_V_tag_full_n;
    end else begin
        reqs_incoming_V_tag_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op221_write_state4 == 1'b1)) begin
            reqs_incoming_V_tag_din = tmp_tag_1_fu_1162_p1;
        end else if ((ap_predicate_op211_write_state4 == 1'b1)) begin
            reqs_incoming_V_tag_din = tmp_tag_3_fu_1128_p1;
        end else begin
            reqs_incoming_V_tag_din = 'bx;
        end
    end else begin
        reqs_incoming_V_tag_din = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_31_reg_1334 == 1'd1) & (tmp_30_reg_1330 == 1'd0) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        reset_sigs_V_blk_n = reset_sigs_V_full_n;
    end else begin
        reset_sigs_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op190_write_state4 == 1'b1))) begin
        reset_sigs_V_write = 1'b1;
    end else begin
        reset_sigs_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (tmp_28_reg_1322 == 1'd1) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        write_mode_app_buf_addrs_V_blk_n = write_mode_app_buf_addrs_V_full_n;
    end else begin
        write_mode_app_buf_addrs_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op193_write_state4 == 1'b1))) begin
        write_mode_app_buf_addrs_V_write = 1'b1;
    end else begin
        write_mode_app_buf_addrs_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op221_write_state4 == 1'b1)) | ((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op211_write_state4 == 1'b1)) | ((kbuf_addrs_V_full_n == 1'b0) & (ap_predicate_op201_write_state4 == 1'b1)) | ((dma_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op200_write_state4 == 1'b1)) | ((dma_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op199_write_state4 == 1'b1)) | ((device_write_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op197_write_state4 == 1'b1)) | ((device_read_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op197_write_state4 == 1'b1)) | ((drive_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op196_write_state4 == 1'b1)) | ((drive_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op195_write_state4 == 1'b1)) | ((write_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op193_write_state4 == 1'b1)) | ((read_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op193_write_state4 == 1'b1)) | ((app_free_buf_V_full_n == 1'b0) & (ap_predicate_op192_write_state4 == 1'b1)) | ((app_input_params_V_full_n == 1'b0) & (ap_predicate_op191_write_state4 == 1'b1)) | ((reset_sigs_V_full_n == 1'b0) & (ap_predicate_op190_write_state4 == 1'b1)) | ((app_commit_write_buf_V_full_n == 1'b0) & (ap_predicate_op189_write_state4 == 1'b1)) | ((app_write_total_len_V_full_n == 1'b0) & (ap_predicate_op187_write_state4 == 1'b1)) | ((app_is_write_mode_2_V_full_n == 1'b0) & (ap_predicate_op176_write_state4 == 1'b1)) | ((app_is_write_mode_1_V_full_n == 1'b0) & (ap_predicate_op176_write_state4 == 1'b1)) | ((app_is_write_mode_0_V_full_n == 1'b0) & (ap_predicate_op176_write_state4 == 1'b1)) | ((dbg_peek_req_V_full_n == 1'b0) & (ap_predicate_op173_write_state4 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op221_write_state4 == 1'b1)) | ((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op211_write_state4 == 1'b1)) | ((kbuf_addrs_V_full_n == 1'b0) & (ap_predicate_op201_write_state4 == 1'b1)) | ((dma_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op200_write_state4 == 1'b1)) | ((dma_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op199_write_state4 == 1'b1)) | ((device_write_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op197_write_state4 == 1'b1)) | ((device_read_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op197_write_state4 == 1'b1)) | ((drive_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op196_write_state4 == 1'b1)) | ((drive_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op195_write_state4 == 1'b1)) | ((write_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op193_write_state4 == 1'b1)) | ((read_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op193_write_state4 == 1'b1)) | ((app_free_buf_V_full_n == 1'b0) & (ap_predicate_op192_write_state4 == 1'b1)) | ((app_input_params_V_full_n == 1'b0) & (ap_predicate_op191_write_state4 == 1'b1)) | ((reset_sigs_V_full_n == 1'b0) & (ap_predicate_op190_write_state4 == 1'b1)) | ((app_commit_write_buf_V_full_n == 1'b0) & (ap_predicate_op189_write_state4 == 1'b1)) | ((app_write_total_len_V_full_n == 1'b0) & (ap_predicate_op187_write_state4 == 1'b1)) | ((app_is_write_mode_2_V_full_n == 1'b0) & (ap_predicate_op176_write_state4 == 1'b1)) | ((app_is_write_mode_1_V_full_n == 1'b0) & (ap_predicate_op176_write_state4 == 1'b1)) | ((app_is_write_mode_0_V_full_n == 1'b0) & (ap_predicate_op176_write_state4 == 1'b1)) | ((dbg_peek_req_V_full_n == 1'b0) & (ap_predicate_op173_write_state4 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op221_write_state4 == 1'b1)) | ((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op211_write_state4 == 1'b1)) | ((kbuf_addrs_V_full_n == 1'b0) & (ap_predicate_op201_write_state4 == 1'b1)) | ((dma_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op200_write_state4 == 1'b1)) | ((dma_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op199_write_state4 == 1'b1)) | ((device_write_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op197_write_state4 == 1'b1)) | ((device_read_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op197_write_state4 == 1'b1)) | ((drive_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op196_write_state4 == 1'b1)) | ((drive_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op195_write_state4 == 1'b1)) | ((write_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op193_write_state4 == 1'b1)) | ((read_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op193_write_state4 == 1'b1)) | ((app_free_buf_V_full_n == 1'b0) & (ap_predicate_op192_write_state4 == 1'b1)) | ((app_input_params_V_full_n == 1'b0) & (ap_predicate_op191_write_state4 == 1'b1)) | ((reset_sigs_V_full_n == 1'b0) & (ap_predicate_op190_write_state4 == 1'b1)) | ((app_commit_write_buf_V_full_n == 1'b0) & (ap_predicate_op189_write_state4 == 1'b1)) | ((app_write_total_len_V_full_n == 1'b0) & (ap_predicate_op187_write_state4 == 1'b1)) | ((app_is_write_mode_2_V_full_n == 1'b0) & (ap_predicate_op176_write_state4 == 1'b1)) | ((app_is_write_mode_1_V_full_n == 1'b0) & (ap_predicate_op176_write_state4 == 1'b1)) | ((app_is_write_mode_0_V_full_n == 1'b0) & (ap_predicate_op176_write_state4 == 1'b1)) | ((dbg_peek_req_V_full_n == 1'b0) & (ap_predicate_op173_write_state4 == 1'b1))));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = (((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op221_write_state4 == 1'b1)) | ((reqs_incoming_V_rw1_status == 1'b0) & (ap_predicate_op211_write_state4 == 1'b1)) | ((kbuf_addrs_V_full_n == 1'b0) & (ap_predicate_op201_write_state4 == 1'b1)) | ((dma_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op200_write_state4 == 1'b1)) | ((dma_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op199_write_state4 == 1'b1)) | ((device_write_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op197_write_state4 == 1'b1)) | ((device_read_delay_cycle_cnts_V_full_n == 1'b0) & (ap_predicate_op197_write_state4 == 1'b1)) | ((drive_read_throttle_params_V_full_n == 1'b0) & (ap_predicate_op196_write_state4 == 1'b1)) | ((drive_write_throttle_params_V_full_n == 1'b0) & (ap_predicate_op195_write_state4 == 1'b1)) | ((write_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op193_write_state4 == 1'b1)) | ((read_mode_app_buf_addrs_V_full_n == 1'b0) & (ap_predicate_op193_write_state4 == 1'b1)) | ((app_free_buf_V_full_n == 1'b0) & (ap_predicate_op192_write_state4 == 1'b1)) | ((app_input_params_V_full_n == 1'b0) & (ap_predicate_op191_write_state4 == 1'b1)) | ((reset_sigs_V_full_n == 1'b0) & (ap_predicate_op190_write_state4 == 1'b1)) | ((app_commit_write_buf_V_full_n == 1'b0) & (ap_predicate_op189_write_state4 == 1'b1)) | ((app_write_total_len_V_full_n == 1'b0) & (ap_predicate_op187_write_state4 == 1'b1)) | ((app_is_write_mode_2_V_full_n == 1'b0) & (ap_predicate_op176_write_state4 == 1'b1)) | ((app_is_write_mode_1_V_full_n == 1'b0) & (ap_predicate_op176_write_state4 == 1'b1)) | ((app_is_write_mode_0_V_full_n == 1'b0) & (ap_predicate_op176_write_state4 == 1'b1)) | ((dbg_peek_req_V_full_n == 1'b0) & (ap_predicate_op173_write_state4 == 1'b1)));
end

always @ (*) begin
    ap_condition_600 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_610 = ((icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (icmp3_fu_831_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_616 = ((tmp_3_fu_837_p2 == 1'd1) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1));
end

always @ (*) begin
    ap_condition_623 = ((tmp_4_fu_843_p2 == 1'd1) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_3_fu_837_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_631 = ((tmp_5_fu_849_p2 == 1'd1) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_640 = ((tmp_6_fu_855_p2 == 1'd1) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_650 = ((tmp_7_fu_861_p2 == 1'd1) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_661 = ((tmp_8_fu_867_p2 == 1'd1) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_7_fu_861_p2 == 1'd0) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_673 = ((tmp_9_fu_873_p2 == 1'd1) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_8_fu_867_p2 == 1'd0) & (tmp_7_fu_861_p2 == 1'd0) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_686 = ((tmp_s_fu_879_p2 == 1'd1) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_9_fu_873_p2 == 1'd0) & (tmp_8_fu_867_p2 == 1'd0) & (tmp_7_fu_861_p2 == 1'd0) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_700 = ((tmp_10_fu_885_p2 == 1'd1) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_s_fu_879_p2 == 1'd0) & (tmp_9_fu_873_p2 == 1'd0) & (tmp_8_fu_867_p2 == 1'd0) & (tmp_7_fu_861_p2 == 1'd0) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_715 = ((tmp_11_fu_891_p2 == 1'd1) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_10_fu_885_p2 == 1'd0) & (tmp_s_fu_879_p2 == 1'd0) & (tmp_9_fu_873_p2 == 1'd0) & (tmp_8_fu_867_p2 == 1'd0) & (tmp_7_fu_861_p2 == 1'd0) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_731 = ((tmp_12_fu_897_p2 == 1'd1) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_11_fu_891_p2 == 1'd0) & (tmp_10_fu_885_p2 == 1'd0) & (tmp_s_fu_879_p2 == 1'd0) & (tmp_9_fu_873_p2 == 1'd0) & (tmp_8_fu_867_p2 == 1'd0) & (tmp_7_fu_861_p2 == 1'd0) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_748 = ((tmp_13_fu_903_p2 == 1'd1) & (icmp3_fu_831_p2 == 1'd1) & (icmp_fu_815_p2 == 1'd1) & (empty_n_1_fu_789_p1 == 1'd1) & (tmp_12_fu_897_p2 == 1'd0) & (tmp_11_fu_891_p2 == 1'd0) & (tmp_10_fu_885_p2 == 1'd0) & (tmp_s_fu_879_p2 == 1'd0) & (tmp_9_fu_873_p2 == 1'd0) & (tmp_8_fu_867_p2 == 1'd0) & (tmp_7_fu_861_p2 == 1'd0) & (tmp_6_fu_855_p2 == 1'd0) & (tmp_5_fu_849_p2 == 1'd0) & (tmp_4_fu_843_p2 == 1'd0) & (tmp_3_fu_837_p2 == 1'd0));
end

assign ap_done = 1'b0;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_state_s_reg_684 = 'bx;

always @ (*) begin
    ap_predicate_op173_write_state4 = ((tmp_40_reg_1350 == 1'd1) & (tmp_34_reg_1346 == 1'd0) & (tmp_33_reg_1342 == 1'd0) & (tmp_32_reg_1338 == 1'd0) & (tmp_31_reg_1334 == 1'd0) & (tmp_30_reg_1330 == 1'd0) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op176_write_state4 = ((tmp_34_reg_1346 == 1'd1) & (tmp_33_reg_1342 == 1'd0) & (tmp_32_reg_1338 == 1'd0) & (tmp_31_reg_1334 == 1'd0) & (tmp_30_reg_1330 == 1'd0) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op187_write_state4 = ((has_half_write_total_len_load_reg_1354 == 1'd1) & (tmp_33_reg_1342 == 1'd1) & (tmp_32_reg_1338 == 1'd0) & (tmp_31_reg_1334 == 1'd0) & (tmp_30_reg_1330 == 1'd0) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op189_write_state4 = ((tmp_32_reg_1338 == 1'd1) & (tmp_31_reg_1334 == 1'd0) & (tmp_30_reg_1330 == 1'd0) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op190_write_state4 = ((tmp_31_reg_1334 == 1'd1) & (tmp_30_reg_1330 == 1'd0) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op191_write_state4 = ((tmp_30_reg_1330 == 1'd1) & (tmp_29_reg_1326 == 1'd0) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op192_write_state4 = ((tmp_29_reg_1326 == 1'd1) & (tmp_28_reg_1322 == 1'd0) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op193_write_state4 = ((tmp_28_reg_1322 == 1'd1) & (tmp_24_reg_1318 == 1'd0) & (tmp_23_reg_1314 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op195_write_state4 = ((tmp_23_reg_1314 == 1'd1) & (is_read_device_throttle_params_load_reg_1358 == 1'd0) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op196_write_state4 = ((is_read_device_throttle_params_load_reg_1358 == 1'd1) & (tmp_23_reg_1314 == 1'd1) & (tmp_22_reg_1310 == 1'd0) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op197_write_state4 = ((tmp_22_reg_1310 == 1'd1) & (tmp_21_reg_1306 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op199_write_state4 = ((tmp_21_reg_1306 == 1'd1) & (is_read_host_throttle_params_load_reg_1362 == 1'd0) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op200_write_state4 = ((is_read_host_throttle_params_load_reg_1362 == 1'd1) & (tmp_21_reg_1306 == 1'd1) & (tmp_19_reg_1302 == 1'd0) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op201_write_state4 = ((tmp_19_reg_1302 == 1'd1) & (tmp_18_reg_1298 == 1'd0) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op211_write_state4 = ((tmp_18_reg_1298 == 1'd1) & (tmp_16_reg_1294 == 1'd0) & (tmp_15_reg_1290 == 1'd0));
end

always @ (*) begin
    ap_predicate_op221_write_state4 = ((tmp_16_reg_1294 == 1'd1) & (tmp_15_reg_1290 == 1'd0));
end

assign ap_ready = 1'b0;

assign app_commit_write_buf_V_din = ap_reg_pp0_iter1_tmp_data_reg_1206;

assign app_file_infos_0_V_din = tmp_data_reg_1206;

assign app_file_infos_1_V_din = tmp_data_reg_1206;

assign app_free_buf_V_din = 1'd0;

assign app_input_params_V_din = ap_reg_pp0_iter1_tmp_data_reg_1206;

assign app_is_write_mode_0_V_din = tmp_39_fu_1043_p2;

assign app_is_write_mode_1_V_din = tmp_39_fu_1043_p2;

assign app_is_write_mode_2_V_din = tmp_39_fu_1043_p2;

assign app_write_total_len_V_din = {{tmp_37_fu_1075_p4}, {tmp_36_fu_1070_p2}};

assign dbg_peek_req_V_din = ap_reg_pp0_iter1_tmp_data_reg_1206;

assign device_read_delay_cycle_cnts_V_din = ap_reg_pp0_iter1_tmp_data_reg_1206;

assign device_write_delay_cycle_cnts_V_din = ap_reg_pp0_iter1_tmp_data_reg_1206;

assign dma_read_throttle_params_V_din = ap_reg_pp0_iter1_tmp_data_reg_1206;

assign dma_write_throttle_params_V_din = ap_reg_pp0_iter1_tmp_data_reg_1206;

assign drive_read_throttle_params_V_din = ap_reg_pp0_iter1_tmp_data_reg_1206;

assign drive_write_throttle_params_V_din = ap_reg_pp0_iter1_tmp_data_reg_1206;

assign empty_n_1_fu_789_p1 = empty_n_nbread_fu_516_p3_0;

assign empty_n_nbread_fu_516_p3_0 = (poke_V_tag_empty_n & poke_V_data_empty_n);

assign grp_fu_766_p4 = {{ap_reg_pp0_iter1_tmp_data_reg_1206[31:3]}};

assign grp_fu_775_p4 = {{ap_reg_pp0_iter1_tmp_tag_4_reg_1200[31:2]}};

assign has_half_write_total_len_load_load_fu_1019_p1 = has_half_write_total_len_fu_500;

assign icmp3_fu_831_p2 = ((tmp_25_fu_821_p4 == 24'd0) ? 1'b1 : 1'b0);

assign icmp_fu_815_p2 = ((tmp_17_fu_805_p4 == 23'd0) ? 1'b1 : 1'b0);

assign is_read_device_throttle_params_load_load_fu_1027_p1 = is_read_device_throttle_params_fu_504;

assign is_read_host_throttle_params_load_load_fu_1035_p1 = is_read_host_throttle_params_fu_508;

assign kbuf_addrs_V_din = ap_reg_pp0_iter1_tmp_data_reg_1206;

assign p_s_fu_914_p3 = ((tmp_14_fu_909_p2[0:0] === 1'b1) ? 5'd17 : 5'd0);

assign poke_V_data_read = poke_V_tag0_update;

assign poke_V_tag_read = poke_V_tag0_update;

assign read_mode_app_buf_addrs_V_din = ap_reg_pp0_iter1_tmp_data_reg_1206;

assign req_sector_num_1_fu_1107_p2 = (tmp_20_cast_fu_1104_p1 + 4'd1);

assign req_sector_num_fu_1141_p2 = (tmp_17_cast_fu_1138_p1 + 4'd1);

assign req_sector_off_4_fu_1133_p1 = grp_fu_766_p4;

assign req_sector_off_5_fu_1099_p1 = grp_fu_766_p4;

assign req_tag_1_fu_1122_p2 = ($signed(tmp_21_cast_fu_1118_p1) + $signed(31'd2147483584));

assign req_tag_fu_1156_p2 = ($signed(tmp_18_cast_fu_1152_p1) + $signed(31'd2147483520));

assign reqs_incoming_V_rw1_status = (reqs_incoming_V_tag_full_n & reqs_incoming_V_sector_off_full_n & reqs_incoming_V_sector_num_full_n & reqs_incoming_V_rw_full_n);

assign reqs_incoming_V_rw_write = reqs_incoming_V_rw1_update;

assign reqs_incoming_V_sector_num_write = reqs_incoming_V_rw1_update;

assign reqs_incoming_V_sector_off_write = reqs_incoming_V_rw1_update;

assign reqs_incoming_V_tag_write = reqs_incoming_V_rw1_update;

assign reset_sigs_V_din = 1'd0;

assign tmp_10_fu_885_p2 = ((poke_V_tag_dout == 32'd56) ? 1'b1 : 1'b0);

assign tmp_11_fu_891_p2 = ((poke_V_tag_dout == 32'd64) ? 1'b1 : 1'b0);

assign tmp_12_fu_897_p2 = ((poke_V_tag_dout == 32'd68) ? 1'b1 : 1'b0);

assign tmp_13_fu_903_p2 = ((poke_V_tag_dout == 32'd72) ? 1'b1 : 1'b0);

assign tmp_14_fu_909_p2 = ((tmp_tag_4_reg_1200 == 32'd88) ? 1'b1 : 1'b0);

assign tmp_15_fu_923_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd0) ? 1'b1 : 1'b0);

assign tmp_16_fu_929_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd1) ? 1'b1 : 1'b0);

assign tmp_17_cast_fu_1138_p1 = ap_reg_pp0_iter1_tmp_2_reg_1228;

assign tmp_17_fu_805_p4 = {{poke_V_tag_dout[31:9]}};

assign tmp_18_cast_fu_1152_p1 = grp_fu_775_p4;

assign tmp_18_fu_935_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd2) ? 1'b1 : 1'b0);

assign tmp_19_fu_941_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd3) ? 1'b1 : 1'b0);

assign tmp_20_cast_fu_1104_p1 = ap_reg_pp0_iter1_tmp_2_reg_1228;

assign tmp_21_cast_fu_1118_p1 = grp_fu_775_p4;

assign tmp_21_fu_947_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd5) ? 1'b1 : 1'b0);

assign tmp_22_fu_953_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd6) ? 1'b1 : 1'b0);

assign tmp_23_fu_959_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd7) ? 1'b1 : 1'b0);

assign tmp_24_fu_965_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd9) ? 1'b1 : 1'b0);

assign tmp_25_fu_821_p4 = {{poke_V_tag_dout[31:8]}};

assign tmp_28_fu_971_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd10) ? 1'b1 : 1'b0);

assign tmp_29_fu_977_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd11) ? 1'b1 : 1'b0);

assign tmp_2_fu_801_p1 = poke_V_data_dout[2:0];

assign tmp_30_fu_983_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd12) ? 1'b1 : 1'b0);

assign tmp_31_fu_989_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd13) ? 1'b1 : 1'b0);

assign tmp_32_fu_995_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd14) ? 1'b1 : 1'b0);

assign tmp_33_fu_1001_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd15) ? 1'b1 : 1'b0);

assign tmp_34_fu_1007_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd16) ? 1'b1 : 1'b0);

assign tmp_35_fu_1066_p1 = tmp_fu_512[31:0];

assign tmp_36_fu_1070_p2 = (tmp_35_fu_1066_p1 | ap_reg_pp0_iter1_tmp_data_reg_1206);

assign tmp_37_fu_1075_p4 = {{tmp_fu_512[63:32]}};

assign tmp_39_fu_1043_p2 = ((ap_reg_pp0_iter1_tmp_data_reg_1206 != 32'd0) ? 1'b1 : 1'b0);

assign tmp_3_fu_837_p2 = ((poke_V_tag_dout == 32'd16) ? 1'b1 : 1'b0);

assign tmp_40_fu_1013_p2 = ((ap_phi_mux_state_s_phi_fu_702_p32 == 5'd17) ? 1'b1 : 1'b0);

assign tmp_4_fu_843_p2 = ((poke_V_tag_dout == 32'd24) ? 1'b1 : 1'b0);

assign tmp_5_fu_849_p2 = ((poke_V_tag_dout == 32'd28) ? 1'b1 : 1'b0);

assign tmp_6_fu_855_p2 = ((poke_V_tag_dout == 32'd32) ? 1'b1 : 1'b0);

assign tmp_7_fu_861_p2 = ((poke_V_tag_dout == 32'd40) ? 1'b1 : 1'b0);

assign tmp_8_fu_867_p2 = ((poke_V_tag_dout == 32'd44) ? 1'b1 : 1'b0);

assign tmp_9_fu_873_p2 = ((poke_V_tag_dout == 32'd48) ? 1'b1 : 1'b0);

assign tmp_s_fu_879_p2 = ((poke_V_tag_dout == 32'd52) ? 1'b1 : 1'b0);

assign tmp_sector_num_1_fu_1147_p1 = req_sector_num_fu_1141_p2;

assign tmp_sector_num_3_fu_1113_p1 = req_sector_num_1_fu_1107_p2;

assign tmp_tag_1_fu_1162_p1 = $signed(req_tag_fu_1156_p2);

assign tmp_tag_3_fu_1128_p1 = $signed(req_tag_1_fu_1122_p2);

assign write_mode_app_buf_addrs_V_din = ap_reg_pp0_iter1_tmp_data_reg_1206;

assign write_total_len_2_fu_1085_p3 = {{tmp_37_fu_1075_p4}, {tmp_36_fu_1070_p2}};

assign write_total_len_fu_1051_p3 = {{ap_reg_pp0_iter1_tmp_data_reg_1206}, {32'd0}};

endmodule //poke_handler
