// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.op
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pipe1_dram_dispatcher,hls_ip_2017_4_op,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.828250,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2228,HLS_SYN_LUT=1438}" *)

module pipe1_dram_dispatcher (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
ap_continue,
        ap_idle,
        ap_ready,
        unified_dram_read_resp_V_last_din,
        unified_dram_read_resp_V_last_full_n,
        unified_dram_read_resp_V_last_write,
        unified_dram_read_resp_V_data_V_din,
        unified_dram_read_resp_V_data_V_full_n,
        unified_dram_read_resp_V_data_V_write,
        unified_dram_write_req_data_V_last_dout,
        unified_dram_write_req_data_V_last_empty_n,
        unified_dram_write_req_data_V_last_read,
        unified_dram_write_req_data_V_data_V_dout,
        unified_dram_write_req_data_V_data_V_empty_n,
        unified_dram_write_req_data_V_data_V_read,
        dramA_read_resp_V_last_dout,
        dramA_read_resp_V_last_empty_n,
        dramA_read_resp_V_last_read,
        dramA_read_resp_V_data_V_dout,
        dramA_read_resp_V_data_V_empty_n,
        dramA_read_resp_V_data_V_read,
        dramA_write_req_data_V_last_din,
        dramA_write_req_data_V_last_full_n,
        dramA_write_req_data_V_last_write,
        dramA_write_req_data_V_data_V_din,
        dramA_write_req_data_V_data_V_full_n,
        dramA_write_req_data_V_data_V_write,
        dramB_read_resp_V_last_dout,
        dramB_read_resp_V_last_empty_n,
        dramB_read_resp_V_last_read,
        dramB_read_resp_V_data_V_dout,
        dramB_read_resp_V_data_V_empty_n,
        dramB_read_resp_V_data_V_read,
        dramB_write_req_data_V_last_din,
        dramB_write_req_data_V_last_full_n,
        dramB_write_req_data_V_last_write,
        dramB_write_req_data_V_data_V_din,
        dramB_write_req_data_V_data_V_full_n,
        dramB_write_req_data_V_data_V_write,
        unified_dram_dispatcher_write_context_V_bank_id_dout,
        unified_dram_dispatcher_write_context_V_bank_id_empty_n,
        unified_dram_dispatcher_write_context_V_bank_id_read,
        unified_dram_dispatcher_write_context_V_end_bank_id_dout,
        unified_dram_dispatcher_write_context_V_end_bank_id_empty_n,
        unified_dram_dispatcher_write_context_V_end_bank_id_read,
        unified_dram_dispatcher_write_context_V_before_boundry_num_dout,
        unified_dram_dispatcher_write_context_V_before_boundry_num_empty_n,
        unified_dram_dispatcher_write_context_V_before_boundry_num_read,
        unified_dram_dispatcher_write_context_V_cmd_num_dout,
        unified_dram_dispatcher_write_context_V_cmd_num_empty_n,
        unified_dram_dispatcher_write_context_V_cmd_num_read,
        unified_dram_dispatcher_read_context_V_bank_id_dout,
        unified_dram_dispatcher_read_context_V_bank_id_empty_n,
        unified_dram_dispatcher_read_context_V_bank_id_read,
        unified_dram_dispatcher_read_context_V_end_bank_id_dout,
        unified_dram_dispatcher_read_context_V_end_bank_id_empty_n,
        unified_dram_dispatcher_read_context_V_end_bank_id_read,
        unified_dram_dispatcher_read_context_V_cmd_num_dout,
        unified_dram_dispatcher_read_context_V_cmd_num_empty_n,
        unified_dram_dispatcher_read_context_V_cmd_num_read,
        host_wrcmd_fin_pcie_write_req_data_V_last_din,
        host_wrcmd_fin_pcie_write_req_data_V_last_full_n,
        host_wrcmd_fin_pcie_write_req_data_V_last_write,
        host_wrcmd_fin_pcie_write_req_data_V_data_V_din,
        host_wrcmd_fin_pcie_write_req_data_V_data_V_full_n,
        host_wrcmd_fin_pcie_write_req_data_V_data_V_write,
        host_wrcmd_fin_pcie_write_req_apply_V_num_din,
        host_wrcmd_fin_pcie_write_req_apply_V_num_full_n,
        host_wrcmd_fin_pcie_write_req_apply_V_num_write,
        host_wrcmd_fin_pcie_write_req_apply_V_addr_din,
        host_wrcmd_fin_pcie_write_req_apply_V_addr_full_n,
        host_wrcmd_fin_pcie_write_req_apply_V_addr_write,
        wrcmd_kbuf_addrs_V_dout,
        wrcmd_kbuf_addrs_V_empty_n,
        wrcmd_kbuf_addrs_V_read
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output ap_ready; output ap_continue;
output   unified_dram_read_resp_V_last_din;
input   unified_dram_read_resp_V_last_full_n;
output   unified_dram_read_resp_V_last_write;
output  [511:0] unified_dram_read_resp_V_data_V_din;
input   unified_dram_read_resp_V_data_V_full_n;
output   unified_dram_read_resp_V_data_V_write;
input   unified_dram_write_req_data_V_last_dout;
input   unified_dram_write_req_data_V_last_empty_n;
output   unified_dram_write_req_data_V_last_read;
input  [511:0] unified_dram_write_req_data_V_data_V_dout;
input   unified_dram_write_req_data_V_data_V_empty_n;
output   unified_dram_write_req_data_V_data_V_read;
input   dramA_read_resp_V_last_dout;
input   dramA_read_resp_V_last_empty_n;
output   dramA_read_resp_V_last_read;
input  [511:0] dramA_read_resp_V_data_V_dout;
input   dramA_read_resp_V_data_V_empty_n;
output   dramA_read_resp_V_data_V_read;
output   dramA_write_req_data_V_last_din;
input   dramA_write_req_data_V_last_full_n;
output   dramA_write_req_data_V_last_write;
output  [511:0] dramA_write_req_data_V_data_V_din;
input   dramA_write_req_data_V_data_V_full_n;
output   dramA_write_req_data_V_data_V_write;
input   dramB_read_resp_V_last_dout;
input   dramB_read_resp_V_last_empty_n;
output   dramB_read_resp_V_last_read;
input  [511:0] dramB_read_resp_V_data_V_dout;
input   dramB_read_resp_V_data_V_empty_n;
output   dramB_read_resp_V_data_V_read;
output   dramB_write_req_data_V_last_din;
input   dramB_write_req_data_V_last_full_n;
output   dramB_write_req_data_V_last_write;
output  [511:0] dramB_write_req_data_V_data_V_din;
input   dramB_write_req_data_V_data_V_full_n;
output   dramB_write_req_data_V_data_V_write;
input  [7:0] unified_dram_dispatcher_write_context_V_bank_id_dout;
input   unified_dram_dispatcher_write_context_V_bank_id_empty_n;
output   unified_dram_dispatcher_write_context_V_bank_id_read;
input  [7:0] unified_dram_dispatcher_write_context_V_end_bank_id_dout;
input   unified_dram_dispatcher_write_context_V_end_bank_id_empty_n;
output   unified_dram_dispatcher_write_context_V_end_bank_id_read;
input  [31:0] unified_dram_dispatcher_write_context_V_before_boundry_num_dout;
input   unified_dram_dispatcher_write_context_V_before_boundry_num_empty_n;
output   unified_dram_dispatcher_write_context_V_before_boundry_num_read;
input  [31:0] unified_dram_dispatcher_write_context_V_cmd_num_dout;
input   unified_dram_dispatcher_write_context_V_cmd_num_empty_n;
output   unified_dram_dispatcher_write_context_V_cmd_num_read;
input  [7:0] unified_dram_dispatcher_read_context_V_bank_id_dout;
input   unified_dram_dispatcher_read_context_V_bank_id_empty_n;
output   unified_dram_dispatcher_read_context_V_bank_id_read;
input  [7:0] unified_dram_dispatcher_read_context_V_end_bank_id_dout;
input   unified_dram_dispatcher_read_context_V_end_bank_id_empty_n;
output   unified_dram_dispatcher_read_context_V_end_bank_id_read;
input  [31:0] unified_dram_dispatcher_read_context_V_cmd_num_dout;
input   unified_dram_dispatcher_read_context_V_cmd_num_empty_n;
output   unified_dram_dispatcher_read_context_V_cmd_num_read;
output   host_wrcmd_fin_pcie_write_req_data_V_last_din;
input   host_wrcmd_fin_pcie_write_req_data_V_last_full_n;
output   host_wrcmd_fin_pcie_write_req_data_V_last_write;
output  [511:0] host_wrcmd_fin_pcie_write_req_data_V_data_V_din;
input   host_wrcmd_fin_pcie_write_req_data_V_data_V_full_n;
output   host_wrcmd_fin_pcie_write_req_data_V_data_V_write;
output  [7:0] host_wrcmd_fin_pcie_write_req_apply_V_num_din;
input   host_wrcmd_fin_pcie_write_req_apply_V_num_full_n;
output   host_wrcmd_fin_pcie_write_req_apply_V_num_write;
output  [63:0] host_wrcmd_fin_pcie_write_req_apply_V_addr_din;
input   host_wrcmd_fin_pcie_write_req_apply_V_addr_full_n;
output   host_wrcmd_fin_pcie_write_req_apply_V_addr_write;
input  [63:0] wrcmd_kbuf_addrs_V_dout;
input   wrcmd_kbuf_addrs_V_empty_n;
output   wrcmd_kbuf_addrs_V_read;

reg ap_idle;
reg unified_dram_read_resp_V_last_din;
reg[511:0] unified_dram_read_resp_V_data_V_din;
reg wrcmd_kbuf_addrs_V_read;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    unified_dram_read_resp_V_last_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] has_read_req_2_reg_634;
reg   [0:0] brmerge_reg_1445;
reg   [0:0] empty_n_6_reg_1453;
reg   [0:0] brmerge1_reg_1449;
reg   [0:0] brmerge2_reg_1467;
reg   [0:0] empty_n_7_reg_1475;
reg   [0:0] brmerge3_reg_1471;
reg    unified_dram_read_resp_V_data_V_blk_n;
reg    dramA_write_req_data_V_last_blk_n;
reg   [0:0] has_write_req_2_reg_593;
reg   [0:0] ap_reg_pp0_iter1_has_write_req_2_reg_593;
reg   [0:0] empty_n_9_reg_1419;
reg   [0:0] ap_reg_pp0_iter1_empty_n_9_reg_1419;
reg   [0:0] brmerge4_reg_1494;
reg   [0:0] brmerge5_reg_1498;
reg    dramA_write_req_data_V_data_V_blk_n;
reg    dramB_write_req_data_V_last_blk_n;
reg   [0:0] brmerge6_reg_1507;
reg   [0:0] brmerge7_reg_1511;
reg    dramB_write_req_data_V_data_V_blk_n;
reg    host_wrcmd_fin_pcie_write_req_data_V_last_blk_n;
reg   [0:0] tmp_last_8_reg_1423;
reg   [0:0] ap_reg_pp0_iter1_tmp_last_8_reg_1423;
reg    host_wrcmd_fin_pcie_write_req_data_V_data_V_blk_n;
reg    host_wrcmd_fin_pcie_write_req_apply_V_num_blk_n;
reg    host_wrcmd_fin_pcie_write_req_apply_V_addr_blk_n;
reg   [6:0] p_s_reg_531;
reg   [0:0] write_is_before_boundry_reg_542;
reg   [0:0] has_read_req_reg_554;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    unified_dram_read_resp_V_last1_status;
reg    ap_predicate_op236_write_state4;
reg    ap_predicate_op237_write_state4;
wire    host_wrcmd_fin_pcie_write_req_apply_V_num1_status;
reg    ap_predicate_op238_write_state4;
wire    host_wrcmd_fin_pcie_write_req_data_V_last1_status;
wire    dramA_write_req_data_V_last1_status;
reg    ap_predicate_op241_write_state4;
wire    dramB_write_req_data_V_last1_status;
reg    ap_predicate_op242_write_state4;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] has_write_req_reg_566;
reg   [6:0] p_0120_2_reg_578;
reg   [0:0] read_is_before_boundry_reg_608;
reg   [0:0] read_is_before_boundry_s_reg_650;
wire   [0:0] empty_n_5_fu_849_p1;
reg   [0:0] empty_n_5_reg_1411;
reg   [0:0] ap_phi_mux_has_read_req_phi_fu_558_p4;
wire   [0:0] empty_n_8_fu_892_p1;
reg   [0:0] ap_phi_mux_has_write_req_phi_fu_570_p4;
wire   [0:0] empty_n_9_fu_948_p1;
reg   [0:0] ap_phi_mux_has_write_req_2_phi_fu_596_p6;
reg   [511:0] tmp_data_V_4_reg_1430;
reg   [511:0] ap_reg_pp0_iter1_tmp_data_V_4_reg_1430;
wire   [6:0] dram_write_times_V_fu_960_p2;
reg   [6:0] dram_write_times_V_reg_1436;
wire   [0:0] brmerge_fu_981_p2;
reg   [0:0] ap_phi_mux_has_read_req_2_phi_fu_638_p6;
wire   [0:0] brmerge1_fu_996_p2;
wire   [0:0] empty_n_6_fu_1002_p1;
reg   [511:0] tmp_data_V_reg_1457;
wire   [0:0] tmp_last_fu_1046_p2;
reg   [0:0] tmp_last_reg_1462;
wire   [0:0] brmerge2_fu_1094_p2;
wire   [0:0] brmerge3_fu_1109_p2;
wire   [0:0] empty_n_7_fu_1115_p1;
reg   [511:0] tmp_data_V_2_reg_1479;
wire   [0:0] tmp_last_2_fu_1159_p2;
reg   [0:0] tmp_last_2_reg_1484;
wire   [63:0] fin_write_apply_addr_fu_1202_p2;
reg   [63:0] fin_write_apply_addr_reg_1489;
wire   [0:0] brmerge4_fu_1223_p2;
wire   [0:0] brmerge5_fu_1238_p2;
wire   [0:0] tmp_last_4_fu_1263_p2;
reg   [0:0] tmp_last_4_reg_1502;
wire   [0:0] brmerge6_fu_1293_p2;
wire   [0:0] brmerge7_fu_1308_p2;
wire   [0:0] tmp_last_5_fu_1333_p2;
reg   [0:0] tmp_last_5_reg_1515;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg   [6:0] ap_phi_mux_p_s_phi_fu_535_p4;
reg   [6:0] ap_phi_mux_p_0120_8_phi_fu_715_p10;
reg   [0:0] ap_phi_mux_write_is_before_boundry_phi_fu_546_p4;
reg   [0:0] ap_phi_mux_write_is_before_boundry_s_phi_fu_734_p10;
reg   [0:0] ap_phi_mux_has_read_req_s_phi_fu_677_p12;
reg   [0:0] ap_phi_mux_has_write_req_8_phi_fu_754_p10;
reg   [6:0] ap_phi_mux_p_0120_2_phi_fu_581_p6;
wire   [6:0] ap_phi_reg_pp0_iter0_p_0120_2_reg_578;
wire   [0:0] ap_phi_reg_pp0_iter0_has_write_req_2_reg_593;
reg   [0:0] ap_phi_mux_read_is_before_boundry_phi_fu_612_p4;
reg   [0:0] ap_phi_mux_read_is_before_boundry_2_phi_fu_623_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_read_is_before_boundry_2_reg_619;
reg   [0:0] ap_phi_reg_pp0_iter1_read_is_before_boundry_2_reg_619;
wire   [0:0] ap_phi_reg_pp0_iter0_has_read_req_2_reg_634;
reg   [0:0] ap_phi_reg_pp0_iter1_has_read_req_2_reg_634;
wire   [0:0] read_is_before_boundry_4_fu_1066_p2;
wire   [0:0] ap_phi_reg_pp0_iter1_read_is_before_boundry_s_reg_650;
wire   [0:0] read_is_before_boundry_7_fu_1179_p2;
wire   [0:0] has_read_req_4_fu_1073_p2;
wire   [0:0] ap_phi_reg_pp0_iter1_has_read_req_s_reg_673;
wire   [0:0] has_read_req_7_fu_1186_p2;
wire   [0:0] ap_phi_reg_pp0_iter0_write_is_before_boundry_2_reg_696;
reg   [0:0] ap_phi_reg_pp0_iter1_write_is_before_boundry_2_reg_696;
wire   [6:0] p_0120_4_fu_1338_p3;
wire   [6:0] ap_phi_reg_pp0_iter1_p_0120_8_reg_711;
wire   [6:0] p_0120_3_fu_1268_p3;
wire   [0:0] write_is_before_boundry_6_fu_1347_p2;
wire   [0:0] ap_phi_reg_pp0_iter1_write_is_before_boundry_s_reg_730;
wire   [0:0] write_is_before_boundry_4_fu_1277_p2;
wire   [0:0] grp_fu_821_p2;
wire   [0:0] ap_phi_reg_pp0_iter1_has_write_req_8_reg_750;
reg    unified_dram_dispatcher_read_context_V_bank_id0_update;
wire   [0:0] empty_n_nbread_fu_426_p4_0;
reg    unified_dram_dispatcher_write_context_V_bank_id0_update;
reg    ap_condition_546;
wire   [0:0] empty_n_3_nbread_fu_436_p5_0;
reg    unified_dram_write_req_data_V_last0_update;
wire   [0:0] empty_n_4_nbread_fu_448_p3_0;
reg    dramA_read_resp_V_last0_update;
wire   [0:0] empty_n_1_nbread_fu_456_p3_0;
reg    dramB_read_resp_V_last0_update;
wire   [0:0] empty_n_2_nbread_fu_464_p3_0;
reg    unified_dram_read_resp_V_last1_update;
reg    ap_block_pp0_stage0_01001;
reg    host_wrcmd_fin_pcie_write_req_apply_V_num1_update;
reg    host_wrcmd_fin_pcie_write_req_data_V_last1_update;
reg    dramA_write_req_data_V_last1_update;
reg    dramB_write_req_data_V_last1_update;
reg   [6:0] dram_read_times_V_6_fu_394;
wire   [6:0] dram_read_times_V_4_fu_1052_p3;
wire   [6:0] dram_read_times_V_5_fu_1165_p3;
reg   [31:0] write_end_bank_id_1_fu_398;
wire   [31:0] write_end_bank_id_fu_916_p1;
reg   [31:0] read_end_bank_id_1_fu_402;
wire   [31:0] read_end_bank_id_fu_869_p1;
reg   [31:0] write_bank_id_1_fu_406;
wire   [31:0] write_bank_id_fu_912_p1;
reg   [31:0] read_bank_id_1_fu_410;
wire   [31:0] read_bank_id_fu_865_p1;
reg   [6:0] read_cmd_num_V_fu_414;
wire   [6:0] read_cmd_num_V_1_fu_873_p1;
reg   [6:0] write_cmd_num_V_fu_418;
wire   [6:0] write_cmd_num_V_1_fu_924_p1;
reg   [6:0] before_boundry_len_V_fu_422;
wire   [6:0] before_boundry_len_V_1_fu_920_p1;
wire   [6:0] grp_fu_776_p2;
wire   [0:0] grp_fu_800_p2;
wire   [0:0] grp_fu_810_p2;
wire   [0:0] grp_fu_805_p2;
wire   [0:0] p_not_fu_969_p2;
wire   [0:0] read_is_before_boundry_2_not_fu_975_p2;
wire   [0:0] p_not1_fu_990_p2;
wire   [0:0] or_cond_fu_1014_p0;
wire   [0:0] grp_fu_782_p2;
wire   [0:0] or_cond1_fu_1020_p0;
wire   [0:0] grp_fu_788_p2;
wire   [0:0] or_cond1_fu_1020_p2;
wire   [0:0] tmp_last_fu_1046_p0;
wire   [0:0] or_cond_fu_1014_p2;
wire   [6:0] dram_read_times_V_1_fu_1026_p3;
wire   [0:0] read_is_before_boundry_3_fu_1034_p2;
wire   [0:0] not_or_cond7_fu_1060_p2;
wire   [0:0] not_or_cond_fu_1040_p2;
wire   [0:0] p_not2_fu_1088_p2;
wire   [0:0] p_not3_fu_1103_p2;
wire   [0:0] or_cond2_fu_1127_p0;
wire   [0:0] or_cond3_fu_1133_p0;
wire   [0:0] or_cond3_fu_1133_p2;
wire   [0:0] tmp_last_2_fu_1159_p0;
wire   [0:0] or_cond2_fu_1127_p2;
wire   [6:0] dram_read_times_V_3_fu_1139_p3;
wire   [0:0] read_is_before_boundry_6_fu_1147_p2;
wire   [0:0] not_or_cond2_fu_1173_p2;
wire   [0:0] not_or_cond1_fu_1153_p2;
wire   [0:0] p_not4_fu_1211_p2;
wire   [0:0] write_is_before_boundry_2_not_fu_1217_p2;
wire   [0:0] p_not5_fu_1232_p2;
wire   [0:0] grp_fu_815_p2;
wire   [0:0] p_write_data_last_fu_1257_p2;
wire   [6:0] p_0134_2_dram_write_times_V_fu_1244_p3;
wire   [0:0] p_write_is_before_boundry_2_fu_1251_p2;
wire   [0:0] p_not6_fu_1287_p2;
wire   [0:0] p_not7_fu_1302_p2;
wire   [0:0] p_write_data_last1_fu_1327_p2;
wire   [6:0] p_0134_2_dram_write_times_V2_fu_1314_p3;
wire   [0:0] p_write_is_before_boundry_s_fu_1321_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_403;
reg    ap_condition_416;
reg    ap_condition_412;
reg    ap_condition_402;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_412)) begin
        if (((ap_phi_mux_has_read_req_phi_fu_558_p4 == 1'd0) & (empty_n_5_fu_849_p1 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_has_read_req_2_reg_634 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_has_read_req_2_reg_634 <= ap_phi_reg_pp0_iter0_has_read_req_2_reg_634;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_412)) begin
        if (((ap_phi_mux_has_read_req_phi_fu_558_p4 == 1'd0) & (empty_n_5_fu_849_p1 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_read_is_before_boundry_2_reg_619 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_read_is_before_boundry_2_reg_619 <= ap_phi_reg_pp0_iter0_read_is_before_boundry_2_reg_619;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd0) & (empty_n_8_fu_892_p1 == 1'd0)))) begin
        ap_phi_reg_pp0_iter1_write_is_before_boundry_2_reg_696 <= ap_phi_mux_write_is_before_boundry_phi_fu_546_p4;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd0) & (empty_n_8_fu_892_p1 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_write_is_before_boundry_2_reg_696 <= 1'd1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_write_is_before_boundry_2_reg_696 <= ap_phi_reg_pp0_iter0_write_is_before_boundry_2_reg_696;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd0) & (empty_n_8_fu_892_p1 == 1'd1))) begin
        before_boundry_len_V_fu_422 <= before_boundry_len_V_1_fu_920_p1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        before_boundry_len_V_fu_422 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((brmerge3_fu_1109_p2 == 1'd0) & (empty_n_7_fu_1115_p1 == 1'd1) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1)) | ((brmerge2_fu_1094_p2 == 1'd0) & (empty_n_7_fu_1115_p1 == 1'd1) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1))))) begin
        dram_read_times_V_6_fu_394 <= dram_read_times_V_5_fu_1165_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((brmerge1_fu_996_p2 == 1'd0) & (empty_n_6_fu_1002_p1 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1)) | ((brmerge_fu_981_p2 == 1'd0) & (empty_n_6_fu_1002_p1 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1))))) begin
        dram_read_times_V_6_fu_394 <= dram_read_times_V_4_fu_1052_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        dram_read_times_V_6_fu_394 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_402)) begin
        if (((empty_n_5_reg_1411 == 1'd0) & (has_read_req_reg_554 == 1'd0))) begin
            has_read_req_2_reg_634 <= 1'd0;
        end else if ((has_read_req_reg_554 == 1'd1)) begin
            has_read_req_2_reg_634 <= has_read_req_reg_554;
        end else if ((1'b1 == 1'b1)) begin
            has_read_req_2_reg_634 <= ap_phi_reg_pp0_iter1_has_read_req_2_reg_634;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        has_read_req_reg_554 <= ap_phi_mux_has_read_req_s_phi_fu_677_p12;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        has_read_req_reg_554 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_412)) begin
        if (((ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd0) & (empty_n_8_fu_892_p1 == 1'd0))) begin
            has_write_req_2_reg_593 <= 1'd0;
        end else if ((ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd1)) begin
            has_write_req_2_reg_593 <= ap_phi_mux_has_write_req_phi_fu_570_p4;
        end else if (((ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd0) & (empty_n_8_fu_892_p1 == 1'd1))) begin
            has_write_req_2_reg_593 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            has_write_req_2_reg_593 <= ap_phi_reg_pp0_iter0_has_write_req_2_reg_593;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        has_write_req_reg_566 <= ap_phi_mux_has_write_req_8_phi_fu_754_p10;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        has_write_req_reg_566 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd0) & (empty_n_8_fu_892_p1 == 1'd0)))) begin
        p_0120_2_reg_578 <= ap_phi_mux_p_s_phi_fu_535_p4;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd0) & (empty_n_8_fu_892_p1 == 1'd1))) begin
        p_0120_2_reg_578 <= 7'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0120_2_reg_578 <= ap_phi_reg_pp0_iter0_p_0120_2_reg_578;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_s_reg_531 <= ap_phi_mux_p_0120_8_phi_fu_715_p10;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_s_reg_531 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_read_req_phi_fu_558_p4 == 1'd0) & (empty_n_5_fu_849_p1 == 1'd1))) begin
        read_cmd_num_V_fu_414 <= read_cmd_num_V_1_fu_873_p1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        read_cmd_num_V_fu_414 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        read_is_before_boundry_reg_608 <= read_is_before_boundry_s_reg_650;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        read_is_before_boundry_reg_608 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((empty_n_7_fu_1115_p1 == 1'd0) & (brmerge3_fu_1109_p2 == 1'd0) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1)) | ((empty_n_7_fu_1115_p1 == 1'd0) & (brmerge2_fu_1094_p2 == 1'd0) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((empty_n_6_fu_1002_p1 == 1'd0) & (brmerge1_fu_996_p2 == 1'd0) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1)) | ((empty_n_6_fu_1002_p1 == 1'd0) & (brmerge_fu_981_p2 == 1'd0) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (brmerge3_fu_1109_p2 == 1'd1) & (brmerge2_fu_1094_p2 == 1'd1) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1)))) begin
        read_is_before_boundry_s_reg_650 <= ap_phi_mux_read_is_before_boundry_2_phi_fu_623_p6;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((brmerge3_fu_1109_p2 == 1'd0) & (empty_n_7_fu_1115_p1 == 1'd1) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1)) | ((brmerge2_fu_1094_p2 == 1'd0) & (empty_n_7_fu_1115_p1 == 1'd1) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1))))) begin
        read_is_before_boundry_s_reg_650 <= read_is_before_boundry_7_fu_1179_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((brmerge1_fu_996_p2 == 1'd0) & (empty_n_6_fu_1002_p1 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1)) | ((brmerge_fu_981_p2 == 1'd0) & (empty_n_6_fu_1002_p1 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1))))) begin
        read_is_before_boundry_s_reg_650 <= read_is_before_boundry_4_fu_1066_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        read_is_before_boundry_s_reg_650 <= ap_phi_reg_pp0_iter1_read_is_before_boundry_s_reg_650;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd0) & (empty_n_8_fu_892_p1 == 1'd1))) begin
        write_cmd_num_V_fu_418 <= write_cmd_num_V_1_fu_924_p1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_cmd_num_V_fu_418 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        write_is_before_boundry_reg_542 <= ap_phi_mux_write_is_before_boundry_s_phi_fu_734_p10;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        write_is_before_boundry_reg_542 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_reg_pp0_iter1_empty_n_9_reg_1419 <= empty_n_9_reg_1419;
        ap_reg_pp0_iter1_has_write_req_2_reg_593 <= has_write_req_2_reg_593;
        ap_reg_pp0_iter1_tmp_data_V_4_reg_1430 <= tmp_data_V_4_reg_1430;
        ap_reg_pp0_iter1_tmp_last_8_reg_1423 <= tmp_last_8_reg_1423;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1))) begin
        brmerge1_reg_1449 <= brmerge1_fu_996_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1))) begin
        brmerge2_reg_1467 <= brmerge2_fu_1094_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (brmerge2_fu_1094_p2 == 1'd1) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1))) begin
        brmerge3_reg_1471 <= brmerge3_fu_1109_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1))) begin
        brmerge4_reg_1494 <= brmerge4_fu_1223_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (brmerge4_fu_1223_p2 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1))) begin
        brmerge5_reg_1498 <= brmerge5_fu_1238_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (brmerge5_fu_1238_p2 == 1'd1) & (brmerge4_fu_1223_p2 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1))) begin
        brmerge6_reg_1507 <= brmerge6_fu_1293_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (brmerge6_fu_1293_p2 == 1'd1) & (brmerge5_fu_1238_p2 == 1'd1) & (brmerge4_fu_1223_p2 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1))) begin
        brmerge7_reg_1511 <= brmerge7_fu_1308_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1))) begin
        brmerge_reg_1445 <= brmerge_fu_981_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_2_phi_fu_596_p6 == 1'd1) & (empty_n_9_fu_948_p1 == 1'd1))) begin
        dram_write_times_V_reg_1436 <= dram_write_times_V_fu_960_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_read_req_phi_fu_558_p4 == 1'd0))) begin
        empty_n_5_reg_1411 <= empty_n_nbread_fu_426_p4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((brmerge1_fu_996_p2 == 1'd0) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1)) | ((brmerge_fu_981_p2 == 1'd0) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1))))) begin
        empty_n_6_reg_1453 <= empty_n_1_nbread_fu_456_p3_0;
        tmp_data_V_reg_1457 <= dramA_read_resp_V_data_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((brmerge3_fu_1109_p2 == 1'd0) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1)) | ((brmerge2_fu_1094_p2 == 1'd0) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1))))) begin
        empty_n_7_reg_1475 <= empty_n_2_nbread_fu_464_p3_0;
        tmp_data_V_2_reg_1479 <= dramB_read_resp_V_data_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_2_phi_fu_596_p6 == 1'd1))) begin
        empty_n_9_reg_1419 <= empty_n_4_nbread_fu_448_p3_0;
        tmp_data_V_4_reg_1430 <= unified_dram_write_req_data_V_data_V_dout;
        tmp_last_8_reg_1423 <= unified_dram_write_req_data_V_last_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_last_8_reg_1423 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1))) begin
        fin_write_apply_addr_reg_1489 <= fin_write_apply_addr_fu_1202_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_read_req_phi_fu_558_p4 == 1'd0) & (empty_n_5_fu_849_p1 == 1'd1))) begin
        read_bank_id_1_fu_410[7 : 0] <= read_bank_id_fu_865_p1[7 : 0];
        read_end_bank_id_1_fu_402[7 : 0] <= read_end_bank_id_fu_869_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((brmerge3_fu_1109_p2 == 1'd0) & (empty_n_7_fu_1115_p1 == 1'd1) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1)) | ((brmerge2_fu_1094_p2 == 1'd0) & (empty_n_7_fu_1115_p1 == 1'd1) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1))))) begin
        tmp_last_2_reg_1484 <= tmp_last_2_fu_1159_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((brmerge5_fu_1238_p2 == 1'd0) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1)) | ((brmerge4_fu_1223_p2 == 1'd0) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1))))) begin
        tmp_last_4_reg_1502 <= tmp_last_4_fu_1263_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((brmerge7_fu_1308_p2 == 1'd0) & (brmerge5_fu_1238_p2 == 1'd1) & (brmerge4_fu_1223_p2 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1)) | ((brmerge6_fu_1293_p2 == 1'd0) & (brmerge5_fu_1238_p2 == 1'd1) & (brmerge4_fu_1223_p2 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1))))) begin
        tmp_last_5_reg_1515 <= tmp_last_5_fu_1333_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((brmerge1_fu_996_p2 == 1'd0) & (empty_n_6_fu_1002_p1 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1)) | ((brmerge_fu_981_p2 == 1'd0) & (empty_n_6_fu_1002_p1 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1))))) begin
        tmp_last_reg_1462 <= tmp_last_fu_1046_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd0) & (empty_n_8_fu_892_p1 == 1'd1))) begin
        write_bank_id_1_fu_406[7 : 0] <= write_bank_id_fu_912_p1[7 : 0];
        write_end_bank_id_1_fu_398[7 : 0] <= write_end_bank_id_fu_916_p1[7 : 0];
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_403)) begin
        if (((empty_n_5_reg_1411 == 1'd0) & (has_read_req_reg_554 == 1'd0))) begin
            ap_phi_mux_has_read_req_2_phi_fu_638_p6 = 1'd0;
        end else if ((has_read_req_reg_554 == 1'd1)) begin
            ap_phi_mux_has_read_req_2_phi_fu_638_p6 = has_read_req_reg_554;
        end else begin
            ap_phi_mux_has_read_req_2_phi_fu_638_p6 = ap_phi_reg_pp0_iter1_has_read_req_2_reg_634;
        end
    end else begin
        ap_phi_mux_has_read_req_2_phi_fu_638_p6 = ap_phi_reg_pp0_iter1_has_read_req_2_reg_634;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_has_read_req_phi_fu_558_p4 = ap_phi_mux_has_read_req_s_phi_fu_677_p12;
    end else begin
        ap_phi_mux_has_read_req_phi_fu_558_p4 = has_read_req_reg_554;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (((empty_n_7_fu_1115_p1 == 1'd0) & (brmerge3_fu_1109_p2 == 1'd0) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1)) | ((empty_n_7_fu_1115_p1 == 1'd0) & (brmerge2_fu_1094_p2 == 1'd0) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (((empty_n_6_fu_1002_p1 == 1'd0) & (brmerge1_fu_996_p2 == 1'd0) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1)) | ((empty_n_6_fu_1002_p1 == 1'd0) & (brmerge_fu_981_p2 == 1'd0) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (brmerge3_fu_1109_p2 == 1'd1) & (brmerge2_fu_1094_p2 == 1'd1) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0)))) begin
        ap_phi_mux_has_read_req_s_phi_fu_677_p12 = 1'd1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_has_read_req_s_phi_fu_677_p12 = ap_phi_mux_has_read_req_2_phi_fu_638_p6;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (((brmerge3_fu_1109_p2 == 1'd0) & (empty_n_7_fu_1115_p1 == 1'd1) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1)) | ((brmerge2_fu_1094_p2 == 1'd0) & (empty_n_7_fu_1115_p1 == 1'd1) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1))))) begin
        ap_phi_mux_has_read_req_s_phi_fu_677_p12 = has_read_req_7_fu_1186_p2;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (((brmerge1_fu_996_p2 == 1'd0) & (empty_n_6_fu_1002_p1 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1)) | ((brmerge_fu_981_p2 == 1'd0) & (empty_n_6_fu_1002_p1 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1))))) begin
        ap_phi_mux_has_read_req_s_phi_fu_677_p12 = has_read_req_4_fu_1073_p2;
    end else begin
        ap_phi_mux_has_read_req_s_phi_fu_677_p12 = ap_phi_reg_pp0_iter1_has_read_req_s_reg_673;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_416)) begin
        if (((ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd0) & (empty_n_8_fu_892_p1 == 1'd0))) begin
            ap_phi_mux_has_write_req_2_phi_fu_596_p6 = 1'd0;
        end else if ((ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd1)) begin
            ap_phi_mux_has_write_req_2_phi_fu_596_p6 = ap_phi_mux_has_write_req_phi_fu_570_p4;
        end else if (((ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd0) & (empty_n_8_fu_892_p1 == 1'd1))) begin
            ap_phi_mux_has_write_req_2_phi_fu_596_p6 = 1'd1;
        end else begin
            ap_phi_mux_has_write_req_2_phi_fu_596_p6 = ap_phi_reg_pp0_iter0_has_write_req_2_reg_593;
        end
    end else begin
        ap_phi_mux_has_write_req_2_phi_fu_596_p6 = ap_phi_reg_pp0_iter0_has_write_req_2_reg_593;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (empty_n_9_reg_1419 == 1'd0) & (has_write_req_2_reg_593 == 1'd1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (brmerge7_fu_1308_p2 == 1'd1) & (brmerge6_fu_1293_p2 == 1'd1) & (brmerge5_fu_1238_p2 == 1'd1) & (brmerge4_fu_1223_p2 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1) & (1'b0 == ap_block_pp0_stage0)))) begin
        ap_phi_mux_has_write_req_8_phi_fu_754_p10 = 1'd1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (has_write_req_2_reg_593 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_has_write_req_8_phi_fu_754_p10 = has_write_req_2_reg_593;
    end else if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (((brmerge7_fu_1308_p2 == 1'd0) & (brmerge5_fu_1238_p2 == 1'd1) & (brmerge4_fu_1223_p2 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1)) | ((brmerge6_fu_1293_p2 == 1'd0) & (brmerge5_fu_1238_p2 == 1'd1) & (brmerge4_fu_1223_p2 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (((brmerge5_fu_1238_p2 == 1'd0) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1)) | ((brmerge4_fu_1223_p2 == 1'd0) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1)))))) begin
        ap_phi_mux_has_write_req_8_phi_fu_754_p10 = grp_fu_821_p2;
    end else begin
        ap_phi_mux_has_write_req_8_phi_fu_754_p10 = ap_phi_reg_pp0_iter1_has_write_req_8_reg_750;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_has_write_req_phi_fu_570_p4 = ap_phi_mux_has_write_req_8_phi_fu_754_p10;
    end else begin
        ap_phi_mux_has_write_req_phi_fu_570_p4 = has_write_req_reg_566;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd0) & (empty_n_8_fu_892_p1 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        ap_phi_mux_p_0120_2_phi_fu_581_p6 = ap_phi_mux_p_s_phi_fu_535_p4;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd0) & (empty_n_8_fu_892_p1 == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_p_0120_2_phi_fu_581_p6 = 7'd0;
    end else begin
        ap_phi_mux_p_0120_2_phi_fu_581_p6 = ap_phi_reg_pp0_iter0_p_0120_2_reg_578;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (brmerge7_fu_1308_p2 == 1'd1) & (brmerge6_fu_1293_p2 == 1'd1) & (brmerge5_fu_1238_p2 == 1'd1) & (brmerge4_fu_1223_p2 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_p_0120_8_phi_fu_715_p10 = dram_write_times_V_reg_1436;
    end else if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (has_write_req_2_reg_593 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (empty_n_9_reg_1419 == 1'd0) & (has_write_req_2_reg_593 == 1'd1) & (1'b0 == ap_block_pp0_stage0)))) begin
        ap_phi_mux_p_0120_8_phi_fu_715_p10 = p_0120_2_reg_578;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (((brmerge5_fu_1238_p2 == 1'd0) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1)) | ((brmerge4_fu_1223_p2 == 1'd0) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1))))) begin
        ap_phi_mux_p_0120_8_phi_fu_715_p10 = p_0120_3_fu_1268_p3;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (((brmerge7_fu_1308_p2 == 1'd0) & (brmerge5_fu_1238_p2 == 1'd1) & (brmerge4_fu_1223_p2 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1)) | ((brmerge6_fu_1293_p2 == 1'd0) & (brmerge5_fu_1238_p2 == 1'd1) & (brmerge4_fu_1223_p2 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1))))) begin
        ap_phi_mux_p_0120_8_phi_fu_715_p10 = p_0120_4_fu_1338_p3;
    end else begin
        ap_phi_mux_p_0120_8_phi_fu_715_p10 = ap_phi_reg_pp0_iter1_p_0120_8_reg_711;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_p_s_phi_fu_535_p4 = ap_phi_mux_p_0120_8_phi_fu_715_p10;
    end else begin
        ap_phi_mux_p_s_phi_fu_535_p4 = p_s_reg_531;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (empty_n_5_reg_1411 == 1'd0) & (has_read_req_reg_554 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (has_read_req_reg_554 == 1'd1) & (1'b0 == ap_block_pp0_stage0)))) begin
        ap_phi_mux_read_is_before_boundry_2_phi_fu_623_p6 = ap_phi_mux_read_is_before_boundry_phi_fu_612_p4;
    end else begin
        ap_phi_mux_read_is_before_boundry_2_phi_fu_623_p6 = ap_phi_reg_pp0_iter1_read_is_before_boundry_2_reg_619;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_read_is_before_boundry_phi_fu_612_p4 = read_is_before_boundry_s_reg_650;
    end else begin
        ap_phi_mux_read_is_before_boundry_phi_fu_612_p4 = read_is_before_boundry_reg_608;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_write_is_before_boundry_phi_fu_546_p4 = ap_phi_mux_write_is_before_boundry_s_phi_fu_734_p10;
    end else begin
        ap_phi_mux_write_is_before_boundry_phi_fu_546_p4 = write_is_before_boundry_reg_542;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (has_write_req_2_reg_593 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (empty_n_9_reg_1419 == 1'd0) & (has_write_req_2_reg_593 == 1'd1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (brmerge7_fu_1308_p2 == 1'd1) & (brmerge6_fu_1293_p2 == 1'd1) & (brmerge5_fu_1238_p2 == 1'd1) & (brmerge4_fu_1223_p2 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1) & (1'b0 == ap_block_pp0_stage0)))) begin
        ap_phi_mux_write_is_before_boundry_s_phi_fu_734_p10 = ap_phi_reg_pp0_iter1_write_is_before_boundry_2_reg_696;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (((brmerge5_fu_1238_p2 == 1'd0) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1)) | ((brmerge4_fu_1223_p2 == 1'd0) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1))))) begin
        ap_phi_mux_write_is_before_boundry_s_phi_fu_734_p10 = write_is_before_boundry_4_fu_1277_p2;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (((brmerge7_fu_1308_p2 == 1'd0) & (brmerge5_fu_1238_p2 == 1'd1) & (brmerge4_fu_1223_p2 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1)) | ((brmerge6_fu_1293_p2 == 1'd0) & (brmerge5_fu_1238_p2 == 1'd1) & (brmerge4_fu_1223_p2 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1))))) begin
        ap_phi_mux_write_is_before_boundry_s_phi_fu_734_p10 = write_is_before_boundry_6_fu_1347_p2;
    end else begin
        ap_phi_mux_write_is_before_boundry_s_phi_fu_734_p10 = ap_phi_reg_pp0_iter1_write_is_before_boundry_s_reg_730;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & ((dramA_read_resp_V_last_empty_n & dramA_read_resp_V_data_V_empty_n) == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((brmerge1_fu_996_p2 == 1'd0) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1)) | ((brmerge_fu_981_p2 == 1'd0) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1))))) begin
        dramA_read_resp_V_last0_update = 1'b1;
    end else begin
        dramA_read_resp_V_last0_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (((brmerge5_reg_1498 == 1'd0) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1)) | ((brmerge4_reg_1494 == 1'd0) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1))))) begin
        dramA_write_req_data_V_data_V_blk_n = dramA_write_req_data_V_data_V_full_n;
    end else begin
        dramA_write_req_data_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op241_write_state4 == 1'b1))) begin
        dramA_write_req_data_V_last1_update = 1'b1;
    end else begin
        dramA_write_req_data_V_last1_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (((brmerge5_reg_1498 == 1'd0) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1)) | ((brmerge4_reg_1494 == 1'd0) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1))))) begin
        dramA_write_req_data_V_last_blk_n = dramA_write_req_data_V_last_full_n;
    end else begin
        dramA_write_req_data_V_last_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & ((dramB_read_resp_V_last_empty_n & dramB_read_resp_V_data_V_empty_n) == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((brmerge3_fu_1109_p2 == 1'd0) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1)) | ((brmerge2_fu_1094_p2 == 1'd0) & (brmerge1_fu_996_p2 == 1'd1) & (ap_phi_mux_has_read_req_2_phi_fu_638_p6 == 1'd1) & (brmerge_fu_981_p2 == 1'd1))))) begin
        dramB_read_resp_V_last0_update = 1'b1;
    end else begin
        dramB_read_resp_V_last0_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (((brmerge7_reg_1511 == 1'd0) & (brmerge5_reg_1498 == 1'd1) & (brmerge4_reg_1494 == 1'd1) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1)) | ((brmerge6_reg_1507 == 1'd0) & (brmerge5_reg_1498 == 1'd1) & (brmerge4_reg_1494 == 1'd1) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1))))) begin
        dramB_write_req_data_V_data_V_blk_n = dramB_write_req_data_V_data_V_full_n;
    end else begin
        dramB_write_req_data_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op242_write_state4 == 1'b1))) begin
        dramB_write_req_data_V_last1_update = 1'b1;
    end else begin
        dramB_write_req_data_V_last1_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (((brmerge7_reg_1511 == 1'd0) & (brmerge5_reg_1498 == 1'd1) & (brmerge4_reg_1494 == 1'd1) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1)) | ((brmerge6_reg_1507 == 1'd0) & (brmerge5_reg_1498 == 1'd1) & (brmerge4_reg_1494 == 1'd1) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1))))) begin
        dramB_write_req_data_V_last_blk_n = dramB_write_req_data_V_last_full_n;
    end else begin
        dramB_write_req_data_V_last_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_tmp_last_8_reg_1423 == 1'd1) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        host_wrcmd_fin_pcie_write_req_apply_V_addr_blk_n = host_wrcmd_fin_pcie_write_req_apply_V_addr_full_n;
    end else begin
        host_wrcmd_fin_pcie_write_req_apply_V_addr_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op238_write_state4 == 1'b1))) begin
        host_wrcmd_fin_pcie_write_req_apply_V_num1_update = 1'b1;
    end else begin
        host_wrcmd_fin_pcie_write_req_apply_V_num1_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_tmp_last_8_reg_1423 == 1'd1) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        host_wrcmd_fin_pcie_write_req_apply_V_num_blk_n = host_wrcmd_fin_pcie_write_req_apply_V_num_full_n;
    end else begin
        host_wrcmd_fin_pcie_write_req_apply_V_num_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_tmp_last_8_reg_1423 == 1'd1) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        host_wrcmd_fin_pcie_write_req_data_V_data_V_blk_n = host_wrcmd_fin_pcie_write_req_data_V_data_V_full_n;
    end else begin
        host_wrcmd_fin_pcie_write_req_data_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op238_write_state4 == 1'b1))) begin
        host_wrcmd_fin_pcie_write_req_data_V_last1_update = 1'b1;
    end else begin
        host_wrcmd_fin_pcie_write_req_data_V_last1_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_reg_pp0_iter1_tmp_last_8_reg_1423 == 1'd1) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        host_wrcmd_fin_pcie_write_req_data_V_last_blk_n = host_wrcmd_fin_pcie_write_req_data_V_last_full_n;
    end else begin
        host_wrcmd_fin_pcie_write_req_data_V_last_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & ((unified_dram_dispatcher_read_context_V_end_bank_id_empty_n & unified_dram_dispatcher_read_context_V_cmd_num_empty_n & unified_dram_dispatcher_read_context_V_bank_id_empty_n) == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_read_req_phi_fu_558_p4 == 1'd0))) begin
        unified_dram_dispatcher_read_context_V_bank_id0_update = 1'b1;
    end else begin
        unified_dram_dispatcher_read_context_V_bank_id0_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_condition_546) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_phi_fu_570_p4 == 1'd0))) begin
        unified_dram_dispatcher_write_context_V_bank_id0_update = 1'b1;
    end else begin
        unified_dram_dispatcher_write_context_V_bank_id0_update = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (((brmerge3_reg_1471 == 1'd0) & (empty_n_7_reg_1475 == 1'd1) & (brmerge1_reg_1449 == 1'd1) & (brmerge_reg_1445 == 1'd1) & (has_read_req_2_reg_634 == 1'd1)) | ((brmerge2_reg_1467 == 1'd0) & (empty_n_7_reg_1475 == 1'd1) & (brmerge1_reg_1449 == 1'd1) & (brmerge_reg_1445 == 1'd1) & (has_read_req_2_reg_634 == 1'd1)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (((brmerge1_reg_1449 == 1'd0) & (empty_n_6_reg_1453 == 1'd1) & (has_read_req_2_reg_634 == 1'd1)) | ((brmerge_reg_1445 == 1'd0) & (empty_n_6_reg_1453 == 1'd1) & (has_read_req_2_reg_634 == 1'd1)))))) begin
        unified_dram_read_resp_V_data_V_blk_n = unified_dram_read_resp_V_data_V_full_n;
    end else begin
        unified_dram_read_resp_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op237_write_state4 == 1'b1)) begin
            unified_dram_read_resp_V_data_V_din = tmp_data_V_2_reg_1479;
        end else if ((ap_predicate_op236_write_state4 == 1'b1)) begin
            unified_dram_read_resp_V_data_V_din = tmp_data_V_reg_1457;
        end else begin
            unified_dram_read_resp_V_data_V_din = 'bx;
        end
    end else begin
        unified_dram_read_resp_V_data_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op237_write_state4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op236_write_state4 == 1'b1)))) begin
        unified_dram_read_resp_V_last1_update = 1'b1;
    end else begin
        unified_dram_read_resp_V_last1_update = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (((brmerge3_reg_1471 == 1'd0) & (empty_n_7_reg_1475 == 1'd1) & (brmerge1_reg_1449 == 1'd1) & (brmerge_reg_1445 == 1'd1) & (has_read_req_2_reg_634 == 1'd1)) | ((brmerge2_reg_1467 == 1'd0) & (empty_n_7_reg_1475 == 1'd1) & (brmerge1_reg_1449 == 1'd1) & (brmerge_reg_1445 == 1'd1) & (has_read_req_2_reg_634 == 1'd1)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (((brmerge1_reg_1449 == 1'd0) & (empty_n_6_reg_1453 == 1'd1) & (has_read_req_2_reg_634 == 1'd1)) | ((brmerge_reg_1445 == 1'd0) & (empty_n_6_reg_1453 == 1'd1) & (has_read_req_2_reg_634 == 1'd1)))))) begin
        unified_dram_read_resp_V_last_blk_n = unified_dram_read_resp_V_last_full_n;
    end else begin
        unified_dram_read_resp_V_last_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op237_write_state4 == 1'b1)) begin
            unified_dram_read_resp_V_last_din = tmp_last_2_reg_1484;
        end else if ((ap_predicate_op236_write_state4 == 1'b1)) begin
            unified_dram_read_resp_V_last_din = tmp_last_reg_1462;
        end else begin
            unified_dram_read_resp_V_last_din = 'bx;
        end
    end else begin
        unified_dram_read_resp_V_last_din = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & ((unified_dram_write_req_data_V_last_empty_n & unified_dram_write_req_data_V_data_V_empty_n) == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_has_write_req_2_phi_fu_596_p6 == 1'd1))) begin
        unified_dram_write_req_data_V_last0_update = 1'b1;
    end else begin
        unified_dram_write_req_data_V_last0_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (wrcmd_kbuf_addrs_V_empty_n == 1'b1) & (tmp_last_8_reg_1423 == 1'd1) & (empty_n_9_reg_1419 == 1'd1) & (has_write_req_2_reg_593 == 1'd1))) begin
        wrcmd_kbuf_addrs_V_read = 1'b1;
    end else begin
        wrcmd_kbuf_addrs_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((dramB_write_req_data_V_last1_status == 1'b0) & (ap_predicate_op242_write_state4 == 1'b1)) | ((dramA_write_req_data_V_last1_status == 1'b0) & (ap_predicate_op241_write_state4 == 1'b1)) | ((host_wrcmd_fin_pcie_write_req_data_V_last1_status == 1'b0) & (ap_predicate_op238_write_state4 == 1'b1)) | ((host_wrcmd_fin_pcie_write_req_apply_V_num1_status == 1'b0) & (ap_predicate_op238_write_state4 == 1'b1)) | ((unified_dram_read_resp_V_last1_status == 1'b0) & (ap_predicate_op237_write_state4 == 1'b1)) | ((unified_dram_read_resp_V_last1_status == 1'b0) & (ap_predicate_op236_write_state4 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((dramB_write_req_data_V_last1_status == 1'b0) & (ap_predicate_op242_write_state4 == 1'b1)) | ((dramA_write_req_data_V_last1_status == 1'b0) & (ap_predicate_op241_write_state4 == 1'b1)) | ((host_wrcmd_fin_pcie_write_req_data_V_last1_status == 1'b0) & (ap_predicate_op238_write_state4 == 1'b1)) | ((host_wrcmd_fin_pcie_write_req_apply_V_num1_status == 1'b0) & (ap_predicate_op238_write_state4 == 1'b1)) | ((unified_dram_read_resp_V_last1_status == 1'b0) & (ap_predicate_op237_write_state4 == 1'b1)) | ((unified_dram_read_resp_V_last1_status == 1'b0) & (ap_predicate_op236_write_state4 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (((dramB_write_req_data_V_last1_status == 1'b0) & (ap_predicate_op242_write_state4 == 1'b1)) | ((dramA_write_req_data_V_last1_status == 1'b0) & (ap_predicate_op241_write_state4 == 1'b1)) | ((host_wrcmd_fin_pcie_write_req_data_V_last1_status == 1'b0) & (ap_predicate_op238_write_state4 == 1'b1)) | ((host_wrcmd_fin_pcie_write_req_apply_V_num1_status == 1'b0) & (ap_predicate_op238_write_state4 == 1'b1)) | ((unified_dram_read_resp_V_last1_status == 1'b0) & (ap_predicate_op237_write_state4 == 1'b1)) | ((unified_dram_read_resp_V_last1_status == 1'b0) & (ap_predicate_op236_write_state4 == 1'b1))));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = (((dramB_write_req_data_V_last1_status == 1'b0) & (ap_predicate_op242_write_state4 == 1'b1)) | ((dramA_write_req_data_V_last1_status == 1'b0) & (ap_predicate_op241_write_state4 == 1'b1)) | ((host_wrcmd_fin_pcie_write_req_data_V_last1_status == 1'b0) & (ap_predicate_op238_write_state4 == 1'b1)) | ((host_wrcmd_fin_pcie_write_req_apply_V_num1_status == 1'b0) & (ap_predicate_op238_write_state4 == 1'b1)) | ((unified_dram_read_resp_V_last1_status == 1'b0) & (ap_predicate_op237_write_state4 == 1'b1)) | ((unified_dram_read_resp_V_last1_status == 1'b0) & (ap_predicate_op236_write_state4 == 1'b1)));
end

always @ (*) begin
    ap_condition_402 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_403 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_412 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_416 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_546 = ((unified_dram_dispatcher_write_context_V_end_bank_id_empty_n & unified_dram_dispatcher_write_context_V_cmd_num_empty_n & unified_dram_dispatcher_write_context_V_before_boundry_num_empty_n & unified_dram_dispatcher_write_context_V_bank_id_empty_n) == 1'b1);
end

assign ap_done = 1'b0;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_has_read_req_2_reg_634 = 'bx;

assign ap_phi_reg_pp0_iter0_has_write_req_2_reg_593 = 'bx;

assign ap_phi_reg_pp0_iter0_p_0120_2_reg_578 = 'bx;

assign ap_phi_reg_pp0_iter0_read_is_before_boundry_2_reg_619 = 'bx;

assign ap_phi_reg_pp0_iter0_write_is_before_boundry_2_reg_696 = 'bx;

assign ap_phi_reg_pp0_iter1_has_read_req_s_reg_673 = 'bx;

assign ap_phi_reg_pp0_iter1_has_write_req_8_reg_750 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0120_8_reg_711 = 'bx;

assign ap_phi_reg_pp0_iter1_read_is_before_boundry_s_reg_650 = 'bx;

assign ap_phi_reg_pp0_iter1_write_is_before_boundry_s_reg_730 = 'bx;

always @ (*) begin
    ap_predicate_op236_write_state4 = (((brmerge1_reg_1449 == 1'd0) & (empty_n_6_reg_1453 == 1'd1) & (has_read_req_2_reg_634 == 1'd1)) | ((brmerge_reg_1445 == 1'd0) & (empty_n_6_reg_1453 == 1'd1) & (has_read_req_2_reg_634 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op237_write_state4 = (((brmerge3_reg_1471 == 1'd0) & (empty_n_7_reg_1475 == 1'd1) & (brmerge1_reg_1449 == 1'd1) & (brmerge_reg_1445 == 1'd1) & (has_read_req_2_reg_634 == 1'd1)) | ((brmerge2_reg_1467 == 1'd0) & (empty_n_7_reg_1475 == 1'd1) & (brmerge1_reg_1449 == 1'd1) & (brmerge_reg_1445 == 1'd1) & (has_read_req_2_reg_634 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op238_write_state4 = ((ap_reg_pp0_iter1_tmp_last_8_reg_1423 == 1'd1) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1));
end

always @ (*) begin
    ap_predicate_op241_write_state4 = (((brmerge5_reg_1498 == 1'd0) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1)) | ((brmerge4_reg_1494 == 1'd0) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op242_write_state4 = (((brmerge7_reg_1511 == 1'd0) & (brmerge5_reg_1498 == 1'd1) & (brmerge4_reg_1494 == 1'd1) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1)) | ((brmerge6_reg_1507 == 1'd0) & (brmerge5_reg_1498 == 1'd1) & (brmerge4_reg_1494 == 1'd1) & (ap_reg_pp0_iter1_empty_n_9_reg_1419 == 1'd1) & (ap_reg_pp0_iter1_has_write_req_2_reg_593 == 1'd1)));
end

assign ap_ready = 1'b0;

assign before_boundry_len_V_1_fu_920_p1 = unified_dram_dispatcher_write_context_V_before_boundry_num_dout[6:0];

assign brmerge1_fu_996_p2 = (p_not1_fu_990_p2 | ap_phi_mux_read_is_before_boundry_2_phi_fu_623_p6);

assign brmerge2_fu_1094_p2 = (read_is_before_boundry_2_not_fu_975_p2 | p_not2_fu_1088_p2);

assign brmerge3_fu_1109_p2 = (p_not3_fu_1103_p2 | ap_phi_mux_read_is_before_boundry_2_phi_fu_623_p6);

assign brmerge4_fu_1223_p2 = (write_is_before_boundry_2_not_fu_1217_p2 | p_not4_fu_1211_p2);

assign brmerge5_fu_1238_p2 = (p_not5_fu_1232_p2 | ap_phi_reg_pp0_iter1_write_is_before_boundry_2_reg_696);

assign brmerge6_fu_1293_p2 = (write_is_before_boundry_2_not_fu_1217_p2 | p_not6_fu_1287_p2);

assign brmerge7_fu_1308_p2 = (p_not7_fu_1302_p2 | ap_phi_reg_pp0_iter1_write_is_before_boundry_2_reg_696);

assign brmerge_fu_981_p2 = (read_is_before_boundry_2_not_fu_975_p2 | p_not_fu_969_p2);

assign dramA_read_resp_V_data_V_read = dramA_read_resp_V_last0_update;

assign dramA_read_resp_V_last_read = dramA_read_resp_V_last0_update;

assign dramA_write_req_data_V_data_V_din = ap_reg_pp0_iter1_tmp_data_V_4_reg_1430;

assign dramA_write_req_data_V_data_V_write = dramA_write_req_data_V_last1_update;

assign dramA_write_req_data_V_last1_status = (dramA_write_req_data_V_last_full_n & dramA_write_req_data_V_data_V_full_n);

assign dramA_write_req_data_V_last_din = tmp_last_4_reg_1502;

assign dramA_write_req_data_V_last_write = dramA_write_req_data_V_last1_update;

assign dramB_read_resp_V_data_V_read = dramB_read_resp_V_last0_update;

assign dramB_read_resp_V_last_read = dramB_read_resp_V_last0_update;

assign dramB_write_req_data_V_data_V_din = ap_reg_pp0_iter1_tmp_data_V_4_reg_1430;

assign dramB_write_req_data_V_data_V_write = dramB_write_req_data_V_last1_update;

assign dramB_write_req_data_V_last1_status = (dramB_write_req_data_V_last_full_n & dramB_write_req_data_V_data_V_full_n);

assign dramB_write_req_data_V_last_din = tmp_last_5_reg_1515;

assign dramB_write_req_data_V_last_write = dramB_write_req_data_V_last1_update;

assign dram_read_times_V_1_fu_1026_p3 = ((or_cond1_fu_1020_p2[0:0] === 1'b1) ? 7'd0 : grp_fu_776_p2);

assign dram_read_times_V_3_fu_1139_p3 = ((or_cond3_fu_1133_p2[0:0] === 1'b1) ? 7'd0 : grp_fu_776_p2);

assign dram_read_times_V_4_fu_1052_p3 = ((or_cond_fu_1014_p2[0:0] === 1'b1) ? grp_fu_776_p2 : dram_read_times_V_1_fu_1026_p3);

assign dram_read_times_V_5_fu_1165_p3 = ((or_cond2_fu_1127_p2[0:0] === 1'b1) ? grp_fu_776_p2 : dram_read_times_V_3_fu_1139_p3);

assign dram_write_times_V_fu_960_p2 = (ap_phi_mux_p_0120_2_phi_fu_581_p6 + 7'd1);

assign empty_n_1_nbread_fu_456_p3_0 = (dramA_read_resp_V_last_empty_n & dramA_read_resp_V_data_V_empty_n);

assign empty_n_2_nbread_fu_464_p3_0 = (dramB_read_resp_V_last_empty_n & dramB_read_resp_V_data_V_empty_n);

assign empty_n_3_nbread_fu_436_p5_0 = (unified_dram_dispatcher_write_context_V_end_bank_id_empty_n & unified_dram_dispatcher_write_context_V_cmd_num_empty_n & unified_dram_dispatcher_write_context_V_before_boundry_num_empty_n & unified_dram_dispatcher_write_context_V_bank_id_empty_n);

assign empty_n_4_nbread_fu_448_p3_0 = (unified_dram_write_req_data_V_last_empty_n & unified_dram_write_req_data_V_data_V_empty_n);

assign empty_n_5_fu_849_p1 = empty_n_nbread_fu_426_p4_0;

assign empty_n_6_fu_1002_p1 = empty_n_1_nbread_fu_456_p3_0;

assign empty_n_7_fu_1115_p1 = empty_n_2_nbread_fu_464_p3_0;

assign empty_n_8_fu_892_p1 = empty_n_3_nbread_fu_436_p5_0;

assign empty_n_9_fu_948_p1 = empty_n_4_nbread_fu_448_p3_0;

assign empty_n_nbread_fu_426_p4_0 = (unified_dram_dispatcher_read_context_V_end_bank_id_empty_n & unified_dram_dispatcher_read_context_V_cmd_num_empty_n & unified_dram_dispatcher_read_context_V_bank_id_empty_n);

assign fin_write_apply_addr_fu_1202_p2 = (wrcmd_kbuf_addrs_V_dout + 64'd4096);

assign grp_fu_776_p2 = (dram_read_times_V_6_fu_394 + 7'd1);

assign grp_fu_782_p2 = ((grp_fu_776_p2 < read_cmd_num_V_fu_414) ? 1'b1 : 1'b0);

assign grp_fu_788_p2 = ((grp_fu_776_p2 == read_cmd_num_V_fu_414) ? 1'b1 : 1'b0);

assign grp_fu_800_p2 = ((dram_write_times_V_reg_1436 == write_cmd_num_V_fu_418) ? 1'b1 : 1'b0);

assign grp_fu_805_p2 = (tmp_last_8_reg_1423 & grp_fu_800_p2);

assign grp_fu_810_p2 = ((dram_write_times_V_reg_1436 == before_boundry_len_V_fu_422) ? 1'b1 : 1'b0);

assign grp_fu_815_p2 = (grp_fu_810_p2 & ap_phi_reg_pp0_iter1_write_is_before_boundry_2_reg_696);

assign grp_fu_821_p2 = (grp_fu_805_p2 ^ 1'd1);

assign has_read_req_4_fu_1073_p2 = (or_cond_fu_1014_p2 | not_or_cond_fu_1040_p2);

assign has_read_req_7_fu_1186_p2 = (or_cond2_fu_1127_p2 | not_or_cond1_fu_1153_p2);

assign host_wrcmd_fin_pcie_write_req_apply_V_addr_din = fin_write_apply_addr_reg_1489;

assign host_wrcmd_fin_pcie_write_req_apply_V_addr_write = host_wrcmd_fin_pcie_write_req_apply_V_num1_update;

assign host_wrcmd_fin_pcie_write_req_apply_V_num1_status = (host_wrcmd_fin_pcie_write_req_apply_V_num_full_n & host_wrcmd_fin_pcie_write_req_apply_V_addr_full_n);

assign host_wrcmd_fin_pcie_write_req_apply_V_num_din = 8'd1;

assign host_wrcmd_fin_pcie_write_req_apply_V_num_write = host_wrcmd_fin_pcie_write_req_apply_V_num1_update;

assign host_wrcmd_fin_pcie_write_req_data_V_data_V_din = 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095;

assign host_wrcmd_fin_pcie_write_req_data_V_data_V_write = host_wrcmd_fin_pcie_write_req_data_V_last1_update;

assign host_wrcmd_fin_pcie_write_req_data_V_last1_status = (host_wrcmd_fin_pcie_write_req_data_V_last_full_n & host_wrcmd_fin_pcie_write_req_data_V_data_V_full_n);

assign host_wrcmd_fin_pcie_write_req_data_V_last_din = 1'd1;

assign host_wrcmd_fin_pcie_write_req_data_V_last_write = host_wrcmd_fin_pcie_write_req_data_V_last1_update;

assign not_or_cond1_fu_1153_p2 = (or_cond3_fu_1133_p2 ^ 1'd1);

assign not_or_cond2_fu_1173_p2 = (or_cond2_fu_1127_p2 ^ 1'd1);

assign not_or_cond7_fu_1060_p2 = (or_cond_fu_1014_p2 ^ 1'd1);

assign not_or_cond_fu_1040_p2 = (or_cond1_fu_1020_p2 ^ 1'd1);

assign or_cond1_fu_1020_p0 = dramA_read_resp_V_last_dout;

assign or_cond1_fu_1020_p2 = (or_cond1_fu_1020_p0 & grp_fu_788_p2);

assign or_cond2_fu_1127_p0 = dramB_read_resp_V_last_dout;

assign or_cond2_fu_1127_p2 = (or_cond2_fu_1127_p0 & grp_fu_782_p2);

assign or_cond3_fu_1133_p0 = dramB_read_resp_V_last_dout;

assign or_cond3_fu_1133_p2 = (or_cond3_fu_1133_p0 & grp_fu_788_p2);

assign or_cond_fu_1014_p0 = dramA_read_resp_V_last_dout;

assign or_cond_fu_1014_p2 = (or_cond_fu_1014_p0 & grp_fu_782_p2);

assign p_0120_3_fu_1268_p3 = ((grp_fu_805_p2[0:0] === 1'b1) ? 7'd0 : p_0134_2_dram_write_times_V_fu_1244_p3);

assign p_0120_4_fu_1338_p3 = ((grp_fu_805_p2[0:0] === 1'b1) ? 7'd0 : p_0134_2_dram_write_times_V2_fu_1314_p3);

assign p_0134_2_dram_write_times_V2_fu_1314_p3 = ((grp_fu_815_p2[0:0] === 1'b1) ? before_boundry_len_V_fu_422 : dram_write_times_V_reg_1436);

assign p_0134_2_dram_write_times_V_fu_1244_p3 = ((grp_fu_815_p2[0:0] === 1'b1) ? before_boundry_len_V_fu_422 : dram_write_times_V_reg_1436);

assign p_not1_fu_990_p2 = ((read_end_bank_id_1_fu_402 != 32'd0) ? 1'b1 : 1'b0);

assign p_not2_fu_1088_p2 = ((read_bank_id_1_fu_410 != 32'd1) ? 1'b1 : 1'b0);

assign p_not3_fu_1103_p2 = ((read_end_bank_id_1_fu_402 != 32'd1) ? 1'b1 : 1'b0);

assign p_not4_fu_1211_p2 = ((write_bank_id_1_fu_406 != 32'd0) ? 1'b1 : 1'b0);

assign p_not5_fu_1232_p2 = ((write_end_bank_id_1_fu_398 != 32'd0) ? 1'b1 : 1'b0);

assign p_not6_fu_1287_p2 = ((write_bank_id_1_fu_406 != 32'd1) ? 1'b1 : 1'b0);

assign p_not7_fu_1302_p2 = ((write_end_bank_id_1_fu_398 != 32'd1) ? 1'b1 : 1'b0);

assign p_not_fu_969_p2 = ((read_bank_id_1_fu_410 != 32'd0) ? 1'b1 : 1'b0);

assign p_write_data_last1_fu_1327_p2 = (grp_fu_821_p2 & grp_fu_815_p2);

assign p_write_data_last_fu_1257_p2 = (grp_fu_821_p2 & grp_fu_815_p2);

assign p_write_is_before_boundry_2_fu_1251_p2 = (grp_fu_815_p2 ^ ap_phi_reg_pp0_iter1_write_is_before_boundry_2_reg_696);

assign p_write_is_before_boundry_s_fu_1321_p2 = (grp_fu_815_p2 ^ ap_phi_reg_pp0_iter1_write_is_before_boundry_2_reg_696);

assign read_bank_id_fu_865_p1 = unified_dram_dispatcher_read_context_V_bank_id_dout;

assign read_cmd_num_V_1_fu_873_p1 = unified_dram_dispatcher_read_context_V_cmd_num_dout[6:0];

assign read_end_bank_id_fu_869_p1 = unified_dram_dispatcher_read_context_V_end_bank_id_dout;

assign read_is_before_boundry_2_not_fu_975_p2 = (ap_phi_mux_read_is_before_boundry_2_phi_fu_623_p6 ^ 1'd1);

assign read_is_before_boundry_3_fu_1034_p2 = (or_cond1_fu_1020_p2 | ap_phi_mux_read_is_before_boundry_2_phi_fu_623_p6);

assign read_is_before_boundry_4_fu_1066_p2 = (read_is_before_boundry_3_fu_1034_p2 & not_or_cond7_fu_1060_p2);

assign read_is_before_boundry_6_fu_1147_p2 = (or_cond3_fu_1133_p2 | ap_phi_mux_read_is_before_boundry_2_phi_fu_623_p6);

assign read_is_before_boundry_7_fu_1179_p2 = (read_is_before_boundry_6_fu_1147_p2 & not_or_cond2_fu_1173_p2);

assign tmp_last_2_fu_1159_p0 = dramB_read_resp_V_last_dout;

assign tmp_last_2_fu_1159_p2 = (tmp_last_2_fu_1159_p0 ^ or_cond2_fu_1127_p2);

assign tmp_last_4_fu_1263_p2 = (tmp_last_8_reg_1423 | p_write_data_last_fu_1257_p2);

assign tmp_last_5_fu_1333_p2 = (tmp_last_8_reg_1423 | p_write_data_last1_fu_1327_p2);

assign tmp_last_fu_1046_p0 = dramA_read_resp_V_last_dout;

assign tmp_last_fu_1046_p2 = (tmp_last_fu_1046_p0 ^ or_cond_fu_1014_p2);

assign unified_dram_dispatcher_read_context_V_bank_id_read = unified_dram_dispatcher_read_context_V_bank_id0_update;

assign unified_dram_dispatcher_read_context_V_cmd_num_read = unified_dram_dispatcher_read_context_V_bank_id0_update;

assign unified_dram_dispatcher_read_context_V_end_bank_id_read = unified_dram_dispatcher_read_context_V_bank_id0_update;

assign unified_dram_dispatcher_write_context_V_bank_id_read = unified_dram_dispatcher_write_context_V_bank_id0_update;

assign unified_dram_dispatcher_write_context_V_before_boundry_num_read = unified_dram_dispatcher_write_context_V_bank_id0_update;

assign unified_dram_dispatcher_write_context_V_cmd_num_read = unified_dram_dispatcher_write_context_V_bank_id0_update;

assign unified_dram_dispatcher_write_context_V_end_bank_id_read = unified_dram_dispatcher_write_context_V_bank_id0_update;

assign unified_dram_read_resp_V_data_V_write = unified_dram_read_resp_V_last1_update;

assign unified_dram_read_resp_V_last1_status = (unified_dram_read_resp_V_last_full_n & unified_dram_read_resp_V_data_V_full_n);

assign unified_dram_read_resp_V_last_write = unified_dram_read_resp_V_last1_update;

assign unified_dram_write_req_data_V_data_V_read = unified_dram_write_req_data_V_last0_update;

assign unified_dram_write_req_data_V_last_read = unified_dram_write_req_data_V_last0_update;

assign write_bank_id_fu_912_p1 = unified_dram_dispatcher_write_context_V_bank_id_dout;

assign write_cmd_num_V_1_fu_924_p1 = unified_dram_dispatcher_write_context_V_cmd_num_dout[6:0];

assign write_end_bank_id_fu_916_p1 = unified_dram_dispatcher_write_context_V_end_bank_id_dout;

assign write_is_before_boundry_2_not_fu_1217_p2 = (ap_phi_reg_pp0_iter1_write_is_before_boundry_2_reg_696 ^ 1'd1);

assign write_is_before_boundry_4_fu_1277_p2 = (p_write_is_before_boundry_2_fu_1251_p2 | grp_fu_805_p2);

assign write_is_before_boundry_6_fu_1347_p2 = (p_write_is_before_boundry_s_fu_1321_p2 | grp_fu_805_p2);

always @ (posedge ap_clk) begin
    write_end_bank_id_1_fu_398[31:8] <= 24'b000000000000000000000000;
    read_end_bank_id_1_fu_402[31:8] <= 24'b000000000000000000000000;
    write_bank_id_1_fu_406[31:8] <= 24'b000000000000000000000000;
    read_bank_id_1_fu_410[31:8] <= 24'b000000000000000000000000;
end

endmodule //pipe1_dram_dispatcher
